Repository open-learning-exchange/myplanet, pull requests merged in 2018-06, with the labels that each got.

#55 Adds sync settings on login activity (fixes #49)
  app/src/main/res/layout/activity_login.xml
Labels: review

#61 fixed duplicated attr (fixes #60)
  .idea/misc.xml
  app/src/main/res/layout/activity_login.xml
Labels: review

#67 Insert data from couchdb to realm db
  .idea/misc.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/ole/planet/takeout/LoginActivity.java
  app/src/main/java/org/ole/planet/takeout/SyncActivity.java
  app/src/main/java/org/ole/planet/takeout/dbSetup.java
Labels: review

#65 changed sync to image button and made sync and settings buttons bigger (fixes #64)
  app/src/main/java/org/ole/planet/takeout/LoginActivity.java
  app/src/main/res/drawable/ic_sync_black_16dp.xml
  app/src/main/res/drawable/ic_sync_black_24dp.xml
  app/src/main/res/drawable/ic_sync_black_36dp.xml
  app/src/main/res/layout-large-land/activity_login.xml
  app/src/main/res/layout-normal-land/activity_login.xml
  app/src/main/res/layout-small-land/activity_login.xml
  app/src/main/res/layout-xlarge-land/activity_login.xml
  app/src/main/res/layout/activity_login.xml
Labels: review

#70 login authentication
  .idea/misc.xml
  app/build.gradle
  app/libs/PBKDF2-1.0.4.jar
  app/src/main/java/org/ole/planet/takeout/AndroidDecrypter.java
  app/src/main/java/org/ole/planet/takeout/LoginActivity.java
  app/src/main/java/org/ole/planet/takeout/ProcessUserData.java
  app/src/main/java/org/ole/planet/takeout/SyncActivity.java
  app/src/main/res/values/strings.xml
Labels: review

#68 Fixing Takeout App drawer
  app/src/main/java/org/ole/planet/takeout/Dashboard.java
  app/src/main/res/drawable/courses_blue.xml
  app/src/main/res/drawable/home_blue.xml
  app/src/main/res/drawable/library_blue.xml
  app/src/main/res/drawable/meetups_blue.xml
  app/src/main/res/drawable/survey_blue.xml
  app/src/main/res/layout/activity_dashboard.xml
  app/src/main/res/menu/menu_dashboard.xml
Labels: in progress

#87 data sync
  app/build.gradle
  app/libs/PBKDF2-1.0.4.jar
  app/src/main/java/org/ole/planet/takeout/CustomDataProcessing.java
  app/src/main/java/org/ole/planet/takeout/DashboardFragment.java
  app/src/main/java/org/ole/planet/takeout/Data/SourceFile.java
  app/src/main/java/org/ole/planet/takeout/Data/realm_UserModel.java
  app/src/main/java/org/ole/planet/takeout/Data/realm_courseSteps.java
  app/src/main/java/org/ole/planet/takeout/Data/realm_meetups.java
  app/src/main/java/org/ole/planet/takeout/Data/realm_myCourses.java
  app/src/main/java/org/ole/planet/takeout/Data/realm_myLibrary.java
  app/src/main/java/org/ole/planet/takeout/Data/realm_offlineActivities.java
  app/src/main/java/org/ole/planet/takeout/Data/realm_stepResources.java
  app/src/main/java/org/ole/planet/takeout/LoginActivity.java
  app/src/main/java/org/ole/planet/takeout/PDFReaderActivity.java
  app/src/main/java/org/ole/planet/takeout/ProcessUserData.java
  app/src/main/java/org/ole/planet/takeout/SyncActivity.java
  app/src/main/res/drawable/dark_rect.xml
  app/src/main/res/drawable/light_rect.xml
  app/src/main/res/layout-large-land/fragment_dashboard.xml
  app/src/main/res/layout-large/fragment_dashboard.xml
  app/src/main/res/layout-normal-land/fragment_dashboard.xml
  app/src/main/res/layout-normal/fragment_dashboard.xml
  app/src/main/res/layout-small-land/fragment_dashboard.xml
  app/src/main/res/layout-small/fragment_dashboard.xml
  app/src/main/res/layout-xlarge-land/fragment_dashboard.xml
  app/src/main/res/layout/fragment_dashboard.xml
  app/src/main/res/values/colors.xml
  build.gradle
Labels: in progress, review

#89 made all the imagebutton clickable (Fixes #88)
  .idea/misc.xml
  app/src/main/java/org/ole/planet/takeout/DashboardFragment.java
  app/src/main/res/layout-large-land/fragment_dashboard.xml
  app/src/main/res/layout-large/fragment_dashboard.xml
  app/src/main/res/layout-normal-land/fragment_dashboard.xml
  app/src/main/res/layout-normal/fragment_dashboard.xml
  app/src/main/res/layout-xlarge-land/fragment_dashboard.xml
  app/src/main/res/layout/fragment_dashboard.xml
Labels: review

#100 App now called "Planet Learning" in both App Drawer and Recent Apps menu
  app/src/main/AndroidManifest.xml
Labels: review
