Repository open-learning-exchange/myplanet, pull requests merged in 2018-08, with the labels that each got.

#158 fix myCourse list on dashboardFragment (fixes #157)
  app/src/main/java/org/ole/planet/takeout/DashboardFragment.java
Labels: review

#159 added logout feature (fixes #141)
  app/src/main/java/org/ole/planet/takeout/Dashboard.java
Labels: review

#160 updating dashboard.java after fixing code climate issue
  app/src/main/java/org/ole/planet/takeout/Dashboard.java
Labels: review

#163 duplicate method removed
  .idea/misc.xml
  app/src/main/java/org/ole/planet/takeout/Dashboard.java
Labels: review

#148 Embedded Video Player using Exoplayer (Issue #58)
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/ole/planet/takeout/Dashboard.java
  app/src/main/java/org/ole/planet/takeout/DashboardFragment.java
  app/src/main/java/org/ole/planet/takeout/ExoPlayerVideo.java
  app/src/main/java/org/ole/planet/takeout/datamanager/MyDownloadService.java
  app/src/main/java/org/ole/planet/takeout/userprofile/UserProfileDbHandler.java
  app/src/main/res/layout/activity_exo_player_video.xml
Labels: review

#170 show only add to myCourses on top bar (Fixes #168)
  .idea/misc.xml
  app/src/main/java/org/ole/planet/takeout/courses/MyCourseFragment.java
  app/src/main/res/layout/fragment_my_course.xml
Labels: review

#178 Changed Home to myPlanet (Issue #177)
  app/src/main/java/org/ole/planet/takeout/Dashboard.java
  app/src/main/res/drawable/myplanet.xml
  app/src/main/res/values/strings.xml
Labels: review

#180 Download error in dialog for large files (#Fixes #167)
  app/src/main/java/org/ole/planet/takeout/Dashboard.java
  app/src/main/java/org/ole/planet/takeout/DashboardFragment.java
  app/src/main/java/org/ole/planet/takeout/Data/Download.java
  app/src/main/java/org/ole/planet/takeout/Data/realm_myLibrary.java
  app/src/main/java/org/ole/planet/takeout/LoginActivity.java
  app/src/main/java/org/ole/planet/takeout/datamanager/ApiInterface.java
  app/src/main/java/org/ole/planet/takeout/datamanager/MyDownloadService.java
  app/src/main/java/org/ole/planet/takeout/utilities/DialogUtils.java
  app/src/main/java/org/ole/planet/takeout/utilities/FileUtils.java
  app/src/main/java/org/ole/planet/takeout/utilities/Utilities.java
Labels: review

#185 User image on dashboard (Fixes #176)
  app/build.gradle
  app/src/main/java/org/ole/planet/takeout/DashboardFragment.java
  app/src/main/java/org/ole/planet/takeout/Data/realm_UserModel.java
  app/src/main/java/org/ole/planet/takeout/ProcessUserData.java
  app/src/main/java/org/ole/planet/takeout/userprofile/UserProfileFragment.java
  app/src/main/java/org/ole/planet/takeout/utilities/Utilities.java
Labels: review

#184 myTeam list on dashboard (Fixes #169)
  app/src/main/java/org/ole/planet/takeout/Dashboard.java
  app/src/main/java/org/ole/planet/takeout/DashboardFragment.java
  app/src/main/java/org/ole/planet/takeout/Data/realm_meetups.java
  app/src/main/java/org/ole/planet/takeout/Data/realm_myTeams.java
  app/src/main/java/org/ole/planet/takeout/Data/realm_stepResources.java
  app/src/main/java/org/ole/planet/takeout/service/SyncManager.java
  app/src/main/java/org/ole/planet/takeout/utilities/Constants.java
  app/src/main/res/layout-large-land/fragment_dashboard.xml
  app/src/main/res/layout-large/fragment_dashboard.xml
  app/src/main/res/layout-normal-land/fragment_dashboard.xml
  app/src/main/res/layout-normal/fragment_dashboard.xml
  app/src/main/res/layout-small-land/fragment_dashboard.xml
  app/src/main/res/layout-small/fragment_dashboard.xml
  app/src/main/res/layout-xlarge-land/fragment_dashboard.xml
  app/src/main/res/layout/fragment_dashboard.xml
Labels: review

#190 code formatting for .java files
  app/src/main/java/org/ole/planet/takeout/AndroidDecrypter.java
  app/src/main/java/org/ole/planet/takeout/AuthSessionUpdater.java
  app/src/main/java/org/ole/planet/takeout/CSVViewerActivity.java
  app/src/main/java/org/ole/planet/takeout/Dashboard.java
  app/src/main/java/org/ole/planet/takeout/DashboardElements.java
  app/src/main/java/org/ole/planet/takeout/Data/Download.java
  app/src/main/java/org/ole/planet/takeout/Data/SourceFile.java
  app/src/main/java/org/ole/planet/takeout/Data/realm_UserModel.java
  app/src/main/java/org/ole/planet/takeout/Data/realm_answerChoices.java
  app/src/main/java/org/ole/planet/takeout/Data/realm_courseSteps.java
  app/src/main/java/org/ole/planet/takeout/Data/realm_courses.java
  app/src/main/java/org/ole/planet/takeout/Data/realm_examQuestion.java
  app/src/main/java/org/ole/planet/takeout/Data/realm_meetups.java
  app/src/main/java/org/ole/planet/takeout/Data/realm_myCourses.java
  app/src/main/java/org/ole/planet/takeout/Data/realm_myLibrary.java
  app/src/main/java/org/ole/planet/takeout/Data/realm_myTeams.java
  app/src/main/java/org/ole/planet/takeout/Data/realm_resources.java
  app/src/main/java/org/ole/planet/takeout/Data/realm_stepExam.java
  app/src/main/java/org/ole/planet/takeout/Data/realm_stepResources.java
  app/src/main/java/org/ole/planet/takeout/DownloadFiles.java
  app/src/main/java/org/ole/planet/takeout/ExoPlayerVideo.java
  app/src/main/java/org/ole/planet/takeout/LoginActivity.java
  app/src/main/java/org/ole/planet/takeout/MainApplication.java
  app/src/main/java/org/ole/planet/takeout/MarkdownViewerActivity.java
  app/src/main/java/org/ole/planet/takeout/OfflineVisits.java
  app/src/main/java/org/ole/planet/takeout/PDFReaderActivity.java
  app/src/main/java/org/ole/planet/takeout/ProcessUserData.java
  app/src/main/java/org/ole/planet/takeout/SyncActivity.java
  app/src/main/java/org/ole/planet/takeout/TextFileViewerActivity.java
  app/src/main/java/org/ole/planet/takeout/base/BaseRecyclerFragment.java
  app/src/main/java/org/ole/planet/takeout/callback/ProgressBroadcastReceiver.java
  app/src/main/java/org/ole/planet/takeout/courses/AdapterCourses.java
  app/src/main/java/org/ole/planet/takeout/courses/MyCourseFragment.java
  app/src/main/java/org/ole/planet/takeout/datamanager/ApiClient.java
  app/src/main/java/org/ole/planet/takeout/datamanager/ApiInterface.java
  app/src/main/java/org/ole/planet/takeout/datamanager/DatabaseService.java
  app/src/main/java/org/ole/planet/takeout/datamanager/MyDownloadService.java
  app/src/main/java/org/ole/planet/takeout/library/AdapterLibrary.java
  app/src/main/java/org/ole/planet/takeout/library/MyLibraryFragment.java
  app/src/main/java/org/ole/planet/takeout/service/AutoSyncService.java
  app/src/main/java/org/ole/planet/takeout/service/SyncManager.java
  app/src/main/java/org/ole/planet/takeout/service/TransactionSyncManager.java
  app/src/main/java/org/ole/planet/takeout/userprofile/UserProfileDbHandler.java
  app/src/main/java/org/ole/planet/takeout/userprofile/UserProfileFragment.java
  app/src/main/java/org/ole/planet/takeout/utilities/Constants.java
  app/src/main/java/org/ole/planet/takeout/utilities/NotificationUtil.java
  app/src/main/java/org/ole/planet/takeout/utilities/Utilities.java
Labels: review

#138 Adding a README.md for the Takeout project
  README.md
Labels: review

#193 Download course material (Fixes #183 and #189)
  app/src/main/java/org/ole/planet/takeout/DashboardFragment.java
  app/src/main/java/org/ole/planet/takeout/Data/realm_courseSteps.java
  app/src/main/java/org/ole/planet/takeout/Data/realm_myLibrary.java
  app/src/main/java/org/ole/planet/takeout/Data/realm_resources.java
  app/src/main/java/org/ole/planet/takeout/Data/realm_stepResources.java
  app/src/main/java/org/ole/planet/takeout/base/BaseRecyclerFragment.java
  app/src/main/java/org/ole/planet/takeout/callback/OnLibraryItemSelected.java
  app/src/main/java/org/ole/planet/takeout/datamanager/MyDownloadService.java
  app/src/main/java/org/ole/planet/takeout/library/AdapterLibrary.java
  app/src/main/java/org/ole/planet/takeout/library/MyLibraryFragment.java
  app/src/main/java/org/ole/planet/takeout/service/SyncManager.java
  app/src/main/java/org/ole/planet/takeout/utilities/DialogUtils.java
  app/src/main/java/org/ole/planet/takeout/utilities/Utilities.java
Labels: review

#195 Filter download dialog items (Fixes #194)
  app/src/main/java/org/ole/planet/takeout/DashboardFragment.java
  app/src/main/java/org/ole/planet/takeout/Data/realm_meetups.java
  app/src/main/java/org/ole/planet/takeout/Data/realm_myCourses.java
  app/src/main/java/org/ole/planet/takeout/Data/realm_myLibrary.java
  app/src/main/java/org/ole/planet/takeout/base/BaseRecyclerFragment.java
  app/src/main/java/org/ole/planet/takeout/datamanager/MyDownloadService.java
  app/src/main/java/org/ole/planet/takeout/service/SyncManager.java
Labels: review

#198 Added take course and step detail (Fixes #182)
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/ole/planet/takeout/DashboardFragment.java
  app/src/main/java/org/ole/planet/takeout/Data/realm_courseSteps.java
  app/src/main/java/org/ole/planet/takeout/Data/realm_stepExam.java
  app/src/main/java/org/ole/planet/takeout/base/BaseContainerFragment.java
  app/src/main/java/org/ole/planet/takeout/courses/AdapterCourses.java
  app/src/main/java/org/ole/planet/takeout/courses/CourseDetailFragment.java
  app/src/main/java/org/ole/planet/takeout/courses/CoursePagerAdapter.java
  app/src/main/java/org/ole/planet/takeout/courses/CourseStepFragment.java
  app/src/main/java/org/ole/planet/takeout/courses/TakeCourseFragment.java
  app/src/main/res/drawable-hdpi/ic_left_arrow.png
  app/src/main/res/drawable-hdpi/ic_right_arrow.png
  app/src/main/res/drawable-hdpi/ic_tick.png
  app/src/main/res/drawable-mdpi/ic_left_arrow.png
  app/src/main/res/drawable-mdpi/ic_right_arrow.png
  app/src/main/res/drawable-mdpi/ic_tick.png
  app/src/main/res/drawable-xhdpi/ic_left_arrow.png
  app/src/main/res/drawable-xhdpi/ic_right_arrow.png
  app/src/main/res/drawable-xhdpi/ic_tick.png
  app/src/main/res/drawable-xxhdpi/ic_left_arrow.png
  app/src/main/res/drawable-xxhdpi/ic_right_arrow.png
  app/src/main/res/drawable-xxhdpi/ic_tick.png
  app/src/main/res/layout-land/course_detail_content.xml
  app/src/main/res/layout/card_course_detail.xml
  app/src/main/res/layout/course_detail_content.xml
  app/src/main/res/layout/fragment_course_detail.xml
  app/src/main/res/layout/fragment_course_step.xml
  app/src/main/res/layout/fragment_take_course.xml
  app/src/main/res/values/attrs.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: in progress, review

#199 Dashboard UI Changees
  .travis.yml
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/ole/planet/takeout/DashboardFragment.java
  app/src/main/java/org/ole/planet/takeout/base/BaseContainerFragment.java
  app/src/main/java/org/ole/planet/takeout/utilities/Utilities.java
  app/src/main/res/drawable/oval_white.xml
  app/src/main/res/layout-large-land/fragment_dashboard.xml
  app/src/main/res/layout-large/fragment_dashboard.xml
  app/src/main/res/layout-normal-land/fragment_dashboard.xml
  app/src/main/res/layout-normal/fragment_dashboard.xml
  app/src/main/res/layout-small-land/fragment_dashboard.xml
  app/src/main/res/layout-small/fragment_dashboard.xml
  app/src/main/res/layout-xlarge-land/fragment_dashboard.xml
  app/src/main/res/layout/card_profile.xml
  app/src/main/res/layout/fragment_dashboard.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/home_card_courses.xml
  app/src/main/res/layout/home_card_library.xml
  app/src/main/res/layout/home_card_meetups.xml
  app/src/main/res/layout/home_card_teams.xml
  app/src/main/res/values-land/dimens.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
  build.gradle
Labels: review

#201 alertdialogboxupdate fixes #171 and #174
  app/src/main/java/org/ole/planet/takeout/base/BaseContainerFragment.java
  app/src/main/res/layout/my_library_alertdialog.xml
  app/src/main/res/layout/rowlayout.xml
  build.gradle
Labels: review

#207 version control for realease
  app/build.gradle
  app/src/main/res/layout-large-land/activity_login.xml
  app/src/main/res/layout-normal-land/activity_login.xml
  app/src/main/res/layout-small-land/activity_login.xml
  app/src/main/res/layout-xlarge-land/activity_login.xml
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/values/strings.xml
Labels: review

#208 v0.2.9
  app/build.gradle
  app/src/main/res/layout-large-land/activity_login.xml
  app/src/main/res/layout-normal-land/activity_login.xml
  app/src/main/res/layout-small-land/activity_login.xml
  app/src/main/res/layout-xlarge-land/activity_login.xml
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/values/strings.xml
  set_tags.sh
Labels: review

#206 Take exam (Fixes #205)
  app/src/main/java/org/ole/planet/takeout/Dashboard.java
  app/src/main/java/org/ole/planet/takeout/Data/realm_answer.java
  app/src/main/java/org/ole/planet/takeout/Data/realm_answerChoices.java
  app/src/main/java/org/ole/planet/takeout/Data/realm_examQuestion.java
  app/src/main/java/org/ole/planet/takeout/Data/realm_submissions.java
  app/src/main/java/org/ole/planet/takeout/courses/CourseStepFragment.java
  app/src/main/java/org/ole/planet/takeout/courses/exam/TakeExamFragment.java
  app/src/main/java/org/ole/planet/takeout/datamanager/DatabaseService.java
  app/src/main/java/org/ole/planet/takeout/survey/AdapterSurvey.java
  app/src/main/java/org/ole/planet/takeout/survey/SurveyFragment.java
  app/src/main/res/layout/fragment_survey.xml
  app/src/main/res/layout/fragment_take_exam.xml
  app/src/main/res/layout/item_radio_btn.xml
  app/src/main/res/layout/row_survey.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: in progress, review

#210 Finish button on last question page (Fixes #209)
  app/src/main/java/org/ole/planet/takeout/courses/exam/TakeExamFragment.java
Labels: review

#214 Travis release fix4
  app/build.gradle
  app/src/main/res/values/strings.xml
  scripts/tag.sh
Labels: review

#217 Travis fix6
  app/build.gradle
  app/src/main/res/values/strings.xml
  scripts/tag.sh
Labels: review

#218 Added my meetup detail fragment with leave and join button (Fixes #216)
  .idea/misc.xml
  app/build.gradle
  app/src/main/java/org/ole/planet/takeout/DashboardFragment.java
  app/src/main/java/org/ole/planet/takeout/Data/realm_UserModel.java
  app/src/main/java/org/ole/planet/takeout/Data/realm_meetups.java
  app/src/main/java/org/ole/planet/takeout/courses/TakeCourseFragment.java
  app/src/main/java/org/ole/planet/takeout/mymeetup/MyMeetupDetailFragment.java
  app/src/main/java/org/ole/planet/takeout/utilities/TimeUtils.java
  app/src/main/res/layout/content_meetup_detail.xml
  app/src/main/res/layout/fragment_my_meetup_detail.xml
  app/src/main/res/layout/row_description.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: review

#219 My teams detail fragment (Fixes #212)
  .idea/misc.xml
  app/src/main/java/org/ole/planet/takeout/DashboardFragment.java
  app/src/main/java/org/ole/planet/takeout/Data/realm_UserModel.java
  app/src/main/java/org/ole/planet/takeout/Data/realm_courseSteps.java
  app/src/main/java/org/ole/planet/takeout/mymeetup/MyMeetupDetailFragment.java
  app/src/main/java/org/ole/planet/takeout/teams/MyTeamsDetailFragment.java
  app/src/main/res/layout/content_teams_detail.xml
  app/src/main/res/layout/fragment_my_teams_detail.xml
Labels: review

#220 Library click bug fix (Fixes #202)
  app/src/main/java/org/ole/planet/takeout/DashboardFragment.java
  app/src/main/java/org/ole/planet/takeout/Data/realm_stepExam.java
  app/src/main/java/org/ole/planet/takeout/service/SyncManager.java
  app/src/main/java/org/ole/planet/takeout/service/TransactionSyncManager.java
  app/src/main/java/org/ole/planet/takeout/survey/SurveyFragment.java
  app/src/main/java/org/ole/planet/takeout/utilities/TimeUtils.java
  app/src/main/res/drawable-hdpi/ic_add.png
  app/src/main/res/drawable-mdpi/ic_add.png
  app/src/main/res/drawable-xhdpi/ic_add.png
  app/src/main/res/drawable-xxhdpi/ic_add.png
  app/src/main/res/layout/fragment_survey.xml
  scripts/tag.sh
Labels: review

#222 change from _users to tablet_users database
  app/src/main/java/org/ole/planet/takeout/DashboardFragment.java
  app/src/main/java/org/ole/planet/takeout/LoginActivity.java
  app/src/main/java/org/ole/planet/takeout/SyncActivity.java
  app/src/main/java/org/ole/planet/takeout/base/BaseRecyclerFragment.java
  app/src/main/java/org/ole/planet/takeout/service/SyncManager.java
Labels: review

#225 Sync with pin
  .idea/modules.xml
  app/build.gradle
  app/src/main/java/org/ole/planet/takeout/AuthSessionUpdater.java
  app/src/main/java/org/ole/planet/takeout/Data/realm_myLibrary.java
  app/src/main/java/org/ole/planet/takeout/LoginActivity.java
  app/src/main/java/org/ole/planet/takeout/SyncActivity.java
  app/src/main/java/org/ole/planet/takeout/service/SyncManager.java
  app/src/main/java/org/ole/planet/takeout/service/TransactionSyncManager.java
  app/src/main/res/layout/dialog_server_url_.xml
  app/src/main/res/values/strings.xml
Labels: in progress

#188 Add dropdown menu
  .idea/misc.xml
  app/src/main/java/org/ole/planet/takeout/SyncActivity.java
  app/src/main/res/menu/menu_dashboard.xml
  gradle.properties
Labels: review

#236 Sync course/exam result to planet
  app/src/main/java/org/ole/planet/takeout/Data/realm_UserModel.java
  app/src/main/java/org/ole/planet/takeout/Data/realm_answer.java
  app/src/main/java/org/ole/planet/takeout/Data/realm_answerChoices.java
  app/src/main/java/org/ole/planet/takeout/Data/realm_courseSteps.java
  app/src/main/java/org/ole/planet/takeout/Data/realm_courses.java
  app/src/main/java/org/ole/planet/takeout/Data/realm_examQuestion.java
  app/src/main/java/org/ole/planet/takeout/Data/realm_myCourses.java
  app/src/main/java/org/ole/planet/takeout/Data/realm_stepExam.java
  app/src/main/java/org/ole/planet/takeout/Data/realm_submissions.java
  app/src/main/java/org/ole/planet/takeout/LoginActivity.java
  app/src/main/java/org/ole/planet/takeout/base/BaseContainerFragment.java
  app/src/main/java/org/ole/planet/takeout/base/BaseRecyclerFragment.java
  app/src/main/java/org/ole/planet/takeout/callback/OnCourseItemSelected.java
  app/src/main/java/org/ole/planet/takeout/courses/AdapterCourses.java
  app/src/main/java/org/ole/planet/takeout/courses/MyCourseFragment.java
  app/src/main/java/org/ole/planet/takeout/service/SyncManager.java
  app/src/main/java/org/ole/planet/takeout/service/TransactionSyncManager.java
  app/src/main/java/org/ole/planet/takeout/service/UploadManager.java
Labels: review
