Repository open-learning-exchange/myplanet, pull requests merged in 2023-10, with the labels that each got.

#2558 login: stabilize `WindowManager` (fixes #2553)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/sync/LoginActivity.java
  app/src/main/java/org/ole/planet/myplanet/utilities/DialogUtils.java
Labels: resolved?

#2411 courses: requires grading test status (fixes #2410)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/exam/BaseExamFragment.java
  app/src/main/java/org/ole/planet/myplanet/ui/exam/TakeExamFragment.java
  app/src/main/java/org/ole/planet/myplanet/ui/exam/UserInformationFragment.java
Labels: ready to merge

#2552 resources: instant search (fixes #2547)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/course/CourseFragment.java
  app/src/main/java/org/ole/planet/myplanet/ui/library/LibraryFragment.java
  app/src/main/res/layout/layout_search.xml
Labels: peer review

#2562 courses: use `markwon` for all markdowns (fixes #2561)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/course/CourseDetailFragment.java
  app/src/main/java/org/ole/planet/myplanet/ui/course/CourseStepFragment.java
  app/src/main/java/org/ole/planet/myplanet/ui/viewer/MarkdownViewerActivity.java
  app/src/main/res/layout/activity_markdown_viewer.xml
  app/src/main/res/layout/fragment_course_detail.xml
  app/src/main/res/layout/fragment_course_step.xml
Labels: peer review

#2554 resources: back from detail page added (fixes #2049)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/library/LibraryDetailFragment.java
  app/src/main/res/layout/fragment_library_detail.xml
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-ne/strings.xml
  app/src/main/res/values-so/strings.xml
  app/src/main/res/values/strings.xml
Labels: review

#2577 actions: remove unused base `BaseAdapterWithTag` (fixes #2575)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/base/BaseAdapterWithTag.java
Labels: review

#2572 about: refactor to fragment with navigation (fixes #2570)
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/ole/planet/myplanet/ui/dashboard/AboutActivity.kt
  app/src/main/java/org/ole/planet/myplanet/ui/dashboard/AboutFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardActivity.java
  app/src/main/res/layout/fragment_about.xml
Labels: peer review

#2573 disclaimer: refactor to fragment with navigation (fixes #2571)
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardActivity.java
  app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DisclaimerActivity.kt
  app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DisclaimerFragment.kt
  app/src/main/res/layout/fragment_disclaimer.xml
Labels: peer review

#2436 courses: improve details layout (fixes #2402)
  app/build.gradle
  app/src/main/res/layout/fragment_course_detail.xml
Labels: review

#2574 addons: viewbinding in myHealth module (fixes #2565)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/myhealth/AdapterHealthExamination.java
  app/src/main/java/org/ole/planet/myplanet/ui/myhealth/AddExaminationActivity.java
  app/src/main/java/org/ole/planet/myplanet/ui/myhealth/AddMyHealthActivity.java
  app/src/main/java/org/ole/planet/myplanet/ui/myhealth/MyHealthFragment.kt
Labels: peer review

#2578 teams: viewbinding refactor (fixes #2576)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/team/AdapterTeam.java
  app/src/main/java/org/ole/planet/myplanet/ui/team/AdapterTeamList.kt
  app/src/main/java/org/ole/planet/myplanet/ui/team/MyTeamsDetailFragment.java
  app/src/main/java/org/ole/planet/myplanet/ui/team/PlanFragment.java
  app/src/main/java/org/ole/planet/myplanet/ui/team/TeamDetailFragment.java
  app/src/main/java/org/ole/planet/myplanet/ui/team/TeamFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/team/teamCourse/TeamCourseFragment.java
  app/src/main/java/org/ole/planet/myplanet/ui/team/teamDiscussion/DiscussionListFragment.java
  app/src/main/java/org/ole/planet/myplanet/ui/team/teamMember/AdapterJoinedMember.java
  app/src/main/java/org/ole/planet/myplanet/ui/team/teamMember/AdapterMemberRequest.java
  app/src/main/java/org/ole/planet/myplanet/ui/team/teamResource/AdapterTeamResource.java
  app/src/main/java/org/ole/planet/myplanet/ui/team/teamResource/TeamResourceFragment.java
  app/src/main/java/org/ole/planet/myplanet/ui/team/teamTask/AdapterTask.java
  app/src/main/java/org/ole/planet/myplanet/ui/team/teamTask/TeamTaskFragment.java
  app/src/main/res/layout/fragment_my_teams_detail.xml
Labels: peer review

#2591 about: display app version (fixes #2550)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/dashboard/AboutFragment.kt
Labels: peer review

#2567 addons: viewbinding in myMeetups (fixes #2563)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/mymeetup/MyMeetUpsFragment.java
  app/src/main/java/org/ole/planet/myplanet/ui/mymeetup/MyMeetupDetailFragment.java
Labels: ready to merge, peer review

#2595 courses: improved `select all` responsiveness (fixes #2594)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/course/AdapterCourses.java
  app/src/main/java/org/ole/planet/myplanet/ui/course/CourseFragment.java
Labels: ready to merge

#2585 navigation: reduce size of logo (fixes #2584)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardActivity.java
Labels: peer review

#2523 login: guest until sign up on third login (fixes #2522)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardActivity.java
  app/src/main/java/org/ole/planet/myplanet/ui/sync/LoginActivity.java
  app/src/main/java/org/ole/planet/myplanet/ui/userprofile/BecomeMemberActivity.kt
  app/src/main/res/layout/activity_become_member.xml
Labels: peer review

#2598 news: implement viewbinding (fixes #2535)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/news/AdapterNews.java
  app/src/main/java/org/ole/planet/myplanet/ui/news/NewsDetailActivity.kt
  app/src/main/java/org/ole/planet/myplanet/ui/news/NewsFragment.java
  app/src/main/java/org/ole/planet/myplanet/ui/news/ReplyActivity.java
  app/src/main/res/layout/activity_news_detail.xml
  app/src/main/res/layout/content_news_detail.xml
Labels: peer review

#2592 courses: implement viewbinding (fixes #2590)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/course/AdapterCourses.java
Labels: peer review

#2600 team: improve stability with realm (fixes #2599)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/team/AdapterTeam.java
Labels: review

#2604 courses: more padding in overview description (fixes #2603)
  app/build.gradle
  app/src/main/res/layout/fragment_course_detail.xml
Labels: peer review

#2602 news: buttons visibility only for creators (fixes #2601)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/news/AdapterNews.java
Labels: peer review

#2608 news: cleanup `NewsFragment` (fixes #2607)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/news/NewsFragment.java
Labels: review

#2606 login: remember all returning users (fixes #2605)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/model/User.kt
  app/src/main/java/org/ole/planet/myplanet/ui/sync/LoginActivity.java
  app/src/main/java/org/ole/planet/myplanet/ui/sync/UserListAdapter.java
  app/src/main/java/org/ole/planet/myplanet/utilities/SharedPrefManager.kt
Labels: peer review

#2610 news: more message stability (fixes #2609)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/news/AdapterNews.java
  app/src/main/java/org/ole/planet/myplanet/utilities/SharedPrefManager.kt
Labels: peer review

#2614 chat: new API structure (fixes #2612)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/chat/ChatActivity.kt
  app/src/main/java/org/ole/planet/myplanet/ui/chat/ChatAdapter.kt
  app/src/main/java/org/ole/planet/myplanet/ui/chat/ChatModel.kt
  app/src/main/java/org/ole/planet/myplanet/ui/chat/ChatRequestModel.kt
Labels: ready to merge

#2621 courses: improve stability (fixes #2620)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/course/CourseStepFragment.java
Labels: review

#2613 login: refactor towards viewbinding (fixes #2611)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/sync/LoginActivity.java
Labels: peer review

#2624 home: refactor towards viewbinding (fixes #2622)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/dashboard/BaseDashboardFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/dashboard/BaseDashboardFragmentPlugin.kt
  app/src/main/java/org/ole/planet/myplanet/ui/dashboard/BellDashboardFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardActivity.java
  app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardFragment.java
  app/src/main/java/org/ole/planet/myplanet/ui/dashboard/InactiveDashboardFragment.java
  app/src/main/java/org/ole/planet/myplanet/ui/dashboard/MyActivityFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/dashboard/notification/AdapterNotification.kt
  app/src/main/java/org/ole/planet/myplanet/ui/dashboard/notification/NotificationFragment.kt
  app/src/main/res/layout/activity_dashboard.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_home_bell.xml
Labels: peer review

#2628 enterprises: refactor calendar towards viewbinding (fixes #2627)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/enterprises/EnterpriseCalendarFragment.kt
Labels: peer review

#2629 courses: refactor progress towards viewbinding (fixes #2626)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/course/CourseProgressActivity.kt
Labels: peer review

#2625 resources: refactor webview towards viewbinding (fixes #2623)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/viewer/WebViewActivity.java
  app/src/main/res/layout/activity_web_view.xml
Labels: peer review

#2635 profile: accessibility enhancements (fixes #2632)
  app/build.gradle
  app/src/main/res/layout/activity_become_member.xml
  app/src/main/res/layout/fragment_achievement.xml
  app/src/main/res/layout/fragment_edit_achievement.xml
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-ne/strings.xml
  app/src/main/res/values-so/strings.xml
  app/src/main/res/values/strings.xml
Labels: review

#2647 settings: show only `cloud` services (fixes #2642)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/datamanager/Service.java
  app/src/main/java/org/ole/planet/myplanet/ui/sync/LoginActivity.java
Labels: ready to merge

#2646 courses: better code quality (fixes #2644)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/course/CourseFragment.java
Labels: ready to merge

#2655 settings: refactor towards more stability (fixes #2649)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/datamanager/Service.java
  app/src/main/java/org/ole/planet/myplanet/ui/sync/LoginActivity.java
Labels: review

#2641 resources: select all fully working (fixes #2640)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/library/AdapterLibrary.java
  app/src/main/java/org/ole/planet/myplanet/ui/library/LibraryFragment.java
Labels: ready to merge

#2645 settings: new default server `planet learning` (fixes #2643)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/datamanager/Service.java
  app/src/main/java/org/ole/planet/myplanet/ui/sync/LoginActivity.java
Labels: ready to merge

#2660 settings: more realm stability (fixes #2656)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/sync/LoginActivity.java
Labels: review
