Repository open-learning-exchange/myplanet, pull requests merged in 2023-11, with the labels that each got.

#2669 login: more realm stability (fixes #2664)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/sync/LoginActivity.java
Labels: review

#2661 login: restrict diacritic characters (fixes #2659)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/sync/LoginActivity.java
  app/src/main/java/org/ole/planet/myplanet/ui/userprofile/BecomeMemberActivity.kt
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-ne/strings.xml
  app/src/main/res/values-so/strings.xml
  app/src/main/res/values/strings.xml
Labels: peer review

#2671 settings: more realm stability (fixes #2670)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/sync/LoginActivity.java
Labels: review

#2678 login: learner conversion cleanup (fixes #2677)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/sync/LoginActivity.java
  app/src/main/java/org/ole/planet/myplanet/ui/userprofile/BecomeMemberActivity.kt
Labels: peer review

#2637 resources: more accessibility in viewer (fixes #2631)
  app/build.gradle
  app/src/main/res/layout/activity_audio_player.xml
  app/src/main/res/layout/activity_exo_player_video.xml
  app/src/main/res/layout/activity_image_viewer.xml
  app/src/main/res/layout/activity_pdfreader.xml
  app/src/main/res/layout/content_web_view.xml
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-ne/strings.xml
  app/src/main/res/values-so/strings.xml
  app/src/main/res/values/strings.xml
Labels: review

#2685 courses: refresh myCourses on change (fixes #2684)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/course/CourseFragment.java
Labels: peer review

#2683 resources: refresh after myLibrary change (fixes #2682)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/library/LibraryFragment.java
Labels: peer review

#2688 settings: redesign configurations (fixes #2676)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/sync/LoginActivity.java
  app/src/main/res/layout/dialog_server_url_.xml
Labels: peer review

#2694 dashboard: show pending survey (fixes #2693)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/dashboard/BellDashboardFragment.kt
Labels: peer review

#2695 dashboard: no health sync popup (fixes #2692)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/dashboard/BellDashboardFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/myhealth/MyHealthFragment.kt
Labels: peer review

#2698 news: more stability (fixes #2697)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/base/BaseResourceFragment.java
Labels: review

#2705 courses: more responsive navigation (fixes #2704)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/course/CourseFragment.java
  app/src/main/res/layout/fragment_my_course.xml
Labels: peer review

#2707 resources: more responsive navigation (fixes #2706)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/model/RealmMyLibrary.java
  app/src/main/java/org/ole/planet/myplanet/ui/library/AdapterLibrary.java
  app/src/main/java/org/ole/planet/myplanet/ui/library/AddResourceActivity.java
  app/src/main/java/org/ole/planet/myplanet/ui/library/LibraryFragment.java
  app/src/main/res/layout/fragment_my_library.xml
Labels: peer review

#2709 courses: add webview for links (fixes #2708)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/course/CourseStepFragment.java
  app/src/main/java/org/ole/planet/myplanet/utilities/CustomClickableSpan.java
Labels: peer review

#2712 resources: re-enable handling of apk (fixes #2711)
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/ole/planet/myplanet/base/BaseContainerFragment.kt
  app/src/main/java/org/ole/planet/myplanet/base/PermissionActivity.java
  app/src/main/java/org/ole/planet/myplanet/utilities/FileUtils.java
Labels: peer review

#2717 actions: `REQUEST_INSTALL_PACKAGES` only on request (fixes #2716)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/base/BaseContainerFragment.kt
  app/src/main/java/org/ole/planet/myplanet/base/PermissionActivity.java
  app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardActivity.java
Labels: peer review

#2719 actions: archive `REQUEST_INSTALL_PACKAGES` permission (fixes #2718)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/base/BaseContainerFragment.kt
  app/src/main/java/org/ole/planet/myplanet/base/PermissionActivity.java
  app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardActivity.java
Labels: review

#2721 actions: comment `REQUEST_INSTALL_PACKAGES` in manifest (fixes #2720)
  app/build.gradle
  app/src/main/AndroidManifest.xml
Labels: review

#2723 settings: more cloud switch stability (fixes #2722)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/sync/LoginActivity.java
Labels: peer review

#2734 courses: add finish at test end (fixes #1957)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/course/TakeCourseFragment.java
  app/src/main/res/layout/fragment_take_course.xml
Labels: ready to merge

#2731 courses: display images as on planet (fixes #2730)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/model/RealmCourseStep.java
  app/src/main/java/org/ole/planet/myplanet/model/RealmMyCourse.java
  app/src/main/java/org/ole/planet/myplanet/ui/course/CourseDetailFragment.java
  app/src/main/java/org/ole/planet/myplanet/ui/course/CourseStepFragment.java
Labels: peer review

#2745 actions: refactor `download` model to kotlin (fixes #2741)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/base/BaseResourceFragment.java
  app/src/main/java/org/ole/planet/myplanet/callback/ProgressBroadcastReceiver.java
  app/src/main/java/org/ole/planet/myplanet/datamanager/MyDownloadService.java
  app/src/main/java/org/ole/planet/myplanet/model/Download.java
  app/src/main/java/org/ole/planet/myplanet/model/Download.kt
  app/src/main/java/org/ole/planet/myplanet/service/AutoSyncWorker.java
  app/src/main/java/org/ole/planet/myplanet/ui/sync/ProcessUserDataActivity.java
Labels: peer review

#2746 actions: refactor `FeedbackReply` model to kotlin (fixes #2742)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/model/FeedbackReply.java
  app/src/main/java/org/ole/planet/myplanet/model/FeedbackReply.kt
  app/src/main/java/org/ole/planet/myplanet/ui/feedback/FeedbackDetailActivity.java
Labels: peer review

#2758 actions: refactor `RealmCourseActivity` to kotlin (fixes #2754)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/model/RealmCourseActivity.java
  app/src/main/java/org/ole/planet/myplanet/model/RealmCourseActivity.kt
Labels: peer review

#2762 myLife: async background transactions (fixes #2748)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/mylife/AdapterMyLife.java
Labels: review

#2760 actions: refactor `RealmApkLog` model to kotlin (fixes #2756)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/MainApplication.java
  app/src/main/java/org/ole/planet/myplanet/model/RealmApkLog.java
  app/src/main/java/org/ole/planet/myplanet/model/RealmApkLog.kt
Labels: peer review
