Repository open-learning-exchange/myplanet, pull requests merged in 2023-09, with the labels that each got.

#2407 resources: bump `com.opencsv:opencsv` to 5.8 (fixes #2406)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/viewer/CSVViewerActivity.java
  app/src/main/res/values/versions.xml
Labels: review

#2427 actions: refactor `AndroidManifest.xml` (fixes #2423)
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/res/values/versions.xml
Labels: review, ready to merge

#2430 actions: bump `versionName` only in `build.gradle` (fixes #2429)
  .gitignore
  app/build.gradle
  app/src/main/res/values/versions.xml
Labels: priority

#2393 resources: no empty rating submission (fixes #2391)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/rating/RatingFragment.java
  app/src/main/res/layout/fragment_rating.xml
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-ne/strings.xml
  app/src/main/res/values-so/strings.xml
  app/src/main/res/values/strings.xml
Labels: review

#2477 actions: unbump `com.mikepenz:*-typeface` to uncrashing (fixes #2475)
  app/build.gradle
Labels: priority, ready to merge

#2375 addons: refactor reference activity (fixes #2369)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/references/ReferenceFragment.java
Labels: review, ready to merge

#2469 login: improve check version (fixes #2474)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/datamanager/Service.java
  app/src/main/res/values/strings.xml
Labels: ready to merge

#2490 courses: refactor take exam module (fixes #2484)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/exam/TakeExamFragment.java
  app/src/main/java/org/ole/planet/myplanet/ui/exam/UserInformationFragment.java
Labels: review, peer review

#2394 resources: refactor viewer modules (fixes #2390)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/viewer/AudioPlayerActivity.java
  app/src/main/java/org/ole/planet/myplanet/ui/viewer/CSVViewerActivity.java
  app/src/main/java/org/ole/planet/myplanet/ui/viewer/ImageViewerActivity.java
  app/src/main/java/org/ole/planet/myplanet/ui/viewer/MarkdownViewerActivity.java
  app/src/main/java/org/ole/planet/myplanet/ui/viewer/PDFReaderActivity.java
  app/src/main/java/org/ole/planet/myplanet/ui/viewer/TextFileViewerActivity.java
  app/src/main/java/org/ole/planet/myplanet/ui/viewer/VideoPlayerActivity.java
Labels: review, peer review

#2459 enterprises: refactor module (fixes #2458)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/enterprises/AdapterCalendar.java
  app/src/main/java/org/ole/planet/myplanet/ui/enterprises/AdapterFinance.java
  app/src/main/java/org/ole/planet/myplanet/ui/enterprises/EnterpriseCalendarFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/enterprises/FinanceFragment.java
Labels: review, peer review

#2398 resources: capture and add image (fixes #2370)
  .github/dependabot.yml
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/library/AddResourceFragment.java
  app/src/main/java/org/ole/planet/myplanet/ui/viewer/ImageViewerActivity.java
Labels: review, peer review

#2408 addons: record and add an audio to resources (fixes #2376)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/service/AudioRecorderService.java
  app/src/main/java/org/ole/planet/myplanet/ui/library/AddResourceFragment.java
  app/src/main/java/org/ole/planet/myplanet/ui/viewer/AudioPlayerActivity.java
Labels: review, peer review

#2500 chat: refactor towards more stability (fixes #2485)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/chat/ChatActivity.kt
Labels: ready to merge

#2501 chat: refactor and cleanup (fixes #2498)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/chat/ChatActivity.kt
Labels: ready to merge

#2507 sync: harden realm towards null exceptions (fixes #2506)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/service/UploadManager.java
Labels: review

#2497 feedback: refactor using viewbinding (fixes #2491)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/feedback/AdapterFeedback.java
  app/src/main/java/org/ole/planet/myplanet/ui/feedback/FeedbackDetailActivity.java
  app/src/main/java/org/ole/planet/myplanet/ui/feedback/FeedbackFragment.java
  app/src/main/java/org/ole/planet/myplanet/ui/feedback/FeedbackListFragment.java
Labels: peer review

#2503 enterprises: only future dates for deadlines (fixes #2496)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/team/teamTask/TeamTaskFragment.java
Labels: peer review

#2502 enterprises: show only for community news (fixes #2495)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/news/AdapterNews.java
Labels: peer review

#2504 enterprises: show username when no fullname (fixes #2499)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/team/teamMember/AdapterJoinedMember.java
  app/src/main/java/org/ole/planet/myplanet/ui/team/teamMember/AdapterMemberRequest.java
Labels: peer review

#2508 profile: implement viewbinding (fixes #2409)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/team/teamCourse/AdapterTeamCourse.java
  app/src/main/java/org/ole/planet/myplanet/ui/team/teamMember/AdapterJoinedMember.java
  app/src/main/java/org/ole/planet/myplanet/ui/userprofile/AchievementFragment.java
  app/src/main/java/org/ole/planet/myplanet/ui/userprofile/AdapterOtherInfo.java
  app/src/main/java/org/ole/planet/myplanet/ui/userprofile/BecomeMemberActivity.kt
  app/src/main/java/org/ole/planet/myplanet/ui/userprofile/EditAchievementFragment.java
  app/src/main/java/org/ole/planet/myplanet/ui/userprofile/UserDetailFragment.java
  app/src/main/java/org/ole/planet/myplanet/ui/userprofile/UserProfileFragment.java
Labels: peer review

#2356 courses: add select all button (fixes #2355)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/course/AdapterCourses.java
  app/src/main/java/org/ole/planet/myplanet/ui/course/CourseFragment.java
  app/src/main/res/layout/fragment_my_course.xml
  app/src/main/res/layout/layout_search.xml
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-ne/strings.xml
  app/src/main/res/values-so/strings.xml
  app/src/main/res/values/strings.xml
Labels: in progress, review

#2520 sync: close realm properly after sync (fixes #2518)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/datamanager/Service.java
Labels: review

#2521 notification: initialize callback (fixes #2303)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/dashboard/notification/NotificationFragment.kt
Labels: review

#2527 login: improve realm instance management (fixes #2526)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/sync/LoginActivity.java
  app/src/main/java/org/ole/planet/myplanet/ui/team/AdapterTeam.java
Labels: review

#2537 login: stable realm while settings dialog (fixes #2532)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/sync/LoginActivity.java
  app/src/main/java/org/ole/planet/myplanet/ui/sync/SyncActivity.java
Labels: review

#2531 addons: move functions into EditAchievementFragment (fixes #2530)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/userprofile/BaseAchievementFragment.java
  app/src/main/java/org/ole/planet/myplanet/ui/userprofile/EditAchievementFragment.java
Labels: peer review

#2540 news: move functions into adapterNews (fixes #2536)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/base/BaseNewsAdapter.java
  app/src/main/java/org/ole/planet/myplanet/ui/news/AdapterNews.java
Labels: peer review

#2545 resources: more stability with optimized list (fixes #2544)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/base/BaseRecyclerFragment.java
Labels: peer review

#2543 login: better sync and realm handling (fixes #2541)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/sync/LoginActivity.java
Labels: review

#2542 resources: better markdown handling (fixes #2378)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/course/AdapterCourses.java
  app/src/main/java/org/ole/planet/myplanet/ui/library/AdapterLibrary.java
Labels: peer review

#2539 survey: implement viewbinding in submission module (fixes #2534)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/submission/AdapterMySubmission.java
  app/src/main/java/org/ole/planet/myplanet/ui/submission/MySubmissionFragment.java
  app/src/main/java/org/ole/planet/myplanet/ui/submission/SubmissionDetailFragment.java
Labels: peer review

#2529 resources: rearrange second navbar (fixes #2528)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/library/AdapterLibrary.java
  app/src/main/java/org/ole/planet/myplanet/ui/library/LibraryFragment.java
  app/src/main/res/layout/fragment_my_library.xml
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-ne/strings.xml
  app/src/main/res/values-so/strings.xml
  app/src/main/res/values/strings.xml
Labels: peer review

#2525 login: remember logged in users (fixes #2524)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/model/User.kt
  app/src/main/java/org/ole/planet/myplanet/ui/sync/LoginActivity.java
  app/src/main/java/org/ole/planet/myplanet/ui/sync/UserListAdapter.java
  app/src/main/java/org/ole/planet/myplanet/utilities/SharedPrefManager.kt
  app/src/main/res/layout-large-land/activity_child_login.xml
  app/src/main/res/layout-large-land/activity_login.xml
  app/src/main/res/layout-normal-land/activity_child_login.xml
  app/src/main/res/layout-normal-land/activity_login.xml
  app/src/main/res/layout-small-land/activity_child_login.xml
  app/src/main/res/layout-small-land/activity_login.xml
  app/src/main/res/layout-xlarge-land/activity_child_login.xml
  app/src/main/res/layout-xlarge-land/activity_login.xml
  app/src/main/res/layout/activity_child_login.xml
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/user_list_item.xml
Labels: peer review

#2538 survey: refactor towards viewbinding (fixes #2533)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/survey/AdapterSurvey.java
  app/src/main/java/org/ole/planet/myplanet/ui/survey/SendSurveyFragment.java
Labels: peer review
