Repository open-learning-exchange/myplanet, pull requests merged in 2023-12, with the labels that each got.

#2751 login: beyond easy mode (fixes #2667)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/SplashActivity.java
  app/src/main/java/org/ole/planet/myplanet/ui/sync/LoginActivity.java
  app/src/main/java/org/ole/planet/myplanet/ui/sync/SyncActivity.java
  app/src/main/java/org/ole/planet/myplanet/ui/sync/TeamLoginActivity.kt
  app/src/main/java/org/ole/planet/myplanet/utilities/SharedPrefManager.kt
  app/src/main/res/layout-large-land/activity_child_login.xml
  app/src/main/res/layout-large-land/activity_login.xml
  app/src/main/res/layout-normal-land/activity_child_login.xml
  app/src/main/res/layout-normal-land/activity_login.xml
  app/src/main/res/layout-small-land/activity_child_login.xml
  app/src/main/res/layout-small-land/activity_login.xml
  app/src/main/res/layout-xlarge-land/activity_child_login.xml
  app/src/main/res/layout-xlarge-land/activity_login.xml
  app/src/main/res/layout/activity_child_login.xml
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_splash.xml
Labels: peer review

#2747 actions: refactor `MyPlanet` model to kotlin (fixes #2743)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/datamanager/Service.java
  app/src/main/java/org/ole/planet/myplanet/model/MyPlanet.java
  app/src/main/java/org/ole/planet/myplanet/model/MyPlanet.kt
  app/src/main/java/org/ole/planet/myplanet/service/AutoSyncWorker.java
  app/src/main/java/org/ole/planet/myplanet/utilities/DialogUtils.java
Labels: peer review

#2744 actions: refactor `DocumentResponse` model to kotlin (fixes #2740)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/model/DocumentResponse.java
  app/src/main/java/org/ole/planet/myplanet/model/DocumentResponse.kt
  app/src/main/java/org/ole/planet/myplanet/service/SyncManager.java
  app/src/main/java/org/ole/planet/myplanet/service/TransactionSyncManager.java
Labels: peer review

#2767 login: one for all (fixes #2766)
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/ole/planet/myplanet/ui/SplashActivity.java
  app/src/main/java/org/ole/planet/myplanet/ui/sync/DashboardElementActivity.java
  app/src/main/java/org/ole/planet/myplanet/ui/sync/LoginActivity.java
  app/src/main/java/org/ole/planet/myplanet/ui/sync/LoginActivity.kt
  app/src/main/java/org/ole/planet/myplanet/ui/sync/SyncActivity.java
  app/src/main/java/org/ole/planet/myplanet/ui/sync/UserListAdapter.java
  app/src/main/java/org/ole/planet/myplanet/utilities/SharedPrefManager.kt
  app/src/main/res/layout-large-land/activity_login.xml
  app/src/main/res/layout-normal-land/activity_login.xml
  app/src/main/res/layout-small-land/activity_login.xml
  app/src/main/res/layout-xlarge-land/activity_login.xml
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_team_login.xml
Labels: peer review

#2789 courses: improve stability (fixes #2788)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/model/RealmCourseActivity.kt
Labels: peer review

#2782 courses: better course step display (fixes #2771)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/course/CourseStepFragment.java
  app/src/main/res/layout/fragment_course_step.xml
Labels: peer review

#2787 courses: better empty data handling (fixes #2786)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/course/AdapterCourses.java
  app/src/main/java/org/ole/planet/myplanet/ui/course/CourseDetailFragment.java
  app/src/main/res/layout/fragment_course_detail.xml
Labels: peer review

#2791 actions: reactivate `REQUEST_INSTALL_PACKAGES` permission (fixes #2790)
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/ole/planet/myplanet/base/BaseContainerFragment.kt
  app/src/main/java/org/ole/planet/myplanet/base/PermissionActivity.java
  app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardActivity.java
Labels: review

#2794 courses: auto image size (fixes #2793)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/course/CourseDetailFragment.java
  app/src/main/java/org/ole/planet/myplanet/ui/course/CourseStepFragment.java
Labels: peer review

#2806 resources: more stability (fixes #2805)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/base/BaseResourceFragment.java
Labels: review

#2781 actions: migrate `RealmFeedback` model to kotlin (fixes #2776)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/model/RealmFeedback.java
  app/src/main/java/org/ole/planet/myplanet/model/RealmFeedback.kt
  app/src/main/java/org/ole/planet/myplanet/ui/feedback/AdapterFeedback.java
  app/src/main/java/org/ole/planet/myplanet/ui/feedback/FeedbackDetailActivity.java
  app/src/main/java/org/ole/planet/myplanet/ui/feedback/FeedbackFragment.java
Labels: peer review

#2761 actions: refactor `RealmAchievement` model to kotlin (fixes #2757)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/model/RealmAchievement.java
  app/src/main/java/org/ole/planet/myplanet/model/RealmAchievement.kt
  app/src/main/java/org/ole/planet/myplanet/ui/userprofile/AchievementFragment.java
  app/src/main/java/org/ole/planet/myplanet/ui/userprofile/EditAchievementFragment.java
Labels: peer review

#2803 actions: refactor `RealmMyHealth` model to kotlin (fixes #2798)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/model/RealmMyHealth.java
  app/src/main/java/org/ole/planet/myplanet/model/RealmMyHealth.kt
  app/src/main/java/org/ole/planet/myplanet/model/RealmMyHealthPojo.java
  app/src/main/java/org/ole/planet/myplanet/model/RealmMyHealthPojo.kt
  app/src/main/java/org/ole/planet/myplanet/service/UploadToShelfService.java
  app/src/main/java/org/ole/planet/myplanet/ui/myhealth/AdapterHealthExamination.java
  app/src/main/java/org/ole/planet/myplanet/ui/myhealth/AddExaminationActivity.java
  app/src/main/java/org/ole/planet/myplanet/ui/myhealth/AddMyHealthActivity.java
  app/src/main/java/org/ole/planet/myplanet/ui/myhealth/MyHealthFragment.kt
Labels: peer review

#2800 actions: refactor `RealmMeetup` model to kotlin (fixes #2795)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/model/RealmMeetup.java
  app/src/main/java/org/ole/planet/myplanet/model/RealmMeetup.kt
  app/src/main/java/org/ole/planet/myplanet/ui/enterprises/AdapterCalendar.java
  app/src/main/java/org/ole/planet/myplanet/ui/mymeetup/MyMeetupDetailFragment.java
Labels: peer review

#2801 actions: refactor `RealmMessage` model to kotlin (fixes #2796)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/model/RealmMessage.java
  app/src/main/java/org/ole/planet/myplanet/model/RealmMessage.kt
Labels: peer review

#2816 dashboard: sync on user creation (fixes #2737)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/datamanager/Service.java
Labels: peer review

#2802 actions: refactor `RealmMyCourse` model to kotlin (fixes #2797)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/base/BaseRecyclerFragment.java
  app/src/main/java/org/ole/planet/myplanet/base/BaseResourceFragment.java
  app/src/main/java/org/ole/planet/myplanet/model/RealmCourseProgress.java
  app/src/main/java/org/ole/planet/myplanet/model/RealmMyCourse.java
  app/src/main/java/org/ole/planet/myplanet/model/RealmMyCourse.kt
  app/src/main/java/org/ole/planet/myplanet/ui/course/AdapterCourses.java
  app/src/main/java/org/ole/planet/myplanet/ui/course/CourseDetailFragment.java
  app/src/main/java/org/ole/planet/myplanet/ui/course/CourseFragment.java
  app/src/main/java/org/ole/planet/myplanet/ui/course/TakeCourseFragment.java
  app/src/main/java/org/ole/planet/myplanet/ui/team/MyTeamsDetailFragment.java
  app/src/main/java/org/ole/planet/myplanet/ui/team/teamCourse/AdapterTeamCourse.java
Labels: peer review

#2778 actions: refactor `RealmCourseProgress` model to kotlin (fixes #2773)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/model/RealmCourseProgress.java
  app/src/main/java/org/ole/planet/myplanet/model/RealmCourseProgress.kt
  app/src/main/java/org/ole/planet/myplanet/service/UploadManager.java
  app/src/main/java/org/ole/planet/myplanet/ui/course/CourseStepFragment.java
  app/src/main/java/org/ole/planet/myplanet/ui/exam/BaseExamFragment.java
Labels: peer review

#2823 actions: refactor `Service` class (fixes #2818)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/datamanager/Service.java
Labels: review

#2814 actions: refactor `RealmMyPersonal` model to kotlin (fixes #2808)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/datamanager/FileUploadService.java
  app/src/main/java/org/ole/planet/myplanet/model/RealmMyPersonal.java
  app/src/main/java/org/ole/planet/myplanet/model/RealmMyPersonal.kt
  app/src/main/java/org/ole/planet/myplanet/ui/library/AddResourceFragment.java
  app/src/main/java/org/ole/planet/myplanet/ui/myPersonals/AdapterMyPersonal.java
Labels: peer review

#2826 actions: pause `REQUEST_INSTALL_PACKAGES` permission (fixes #2825)
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/ole/planet/myplanet/base/BaseContainerFragment.kt
  app/src/main/java/org/ole/planet/myplanet/base/PermissionActivity.java
  app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardActivity.java
Labels: review, ready to merge

#2859 courses: text when filter results empty (fixes #1952)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/base/BaseRecyclerFragment.java
  app/src/main/java/org/ole/planet/myplanet/ui/course/CourseFragment.java
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-ne/strings.xml
  app/src/main/res/values-so/strings.xml
  app/src/main/res/values/strings.xml
Labels: ready to merge

#2822 courses: better markdown tables (fixes #2820)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/course/CourseStepFragment.java
Labels: peer review

#2759 actions: refactor `RealmCertification` model to kotlin (fixes #2755)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/model/RealmCertification.java
  app/src/main/java/org/ole/planet/myplanet/model/RealmCertification.kt
Labels: peer review

#2777 actions: refactor `RealmAnswer` model to kotlin (fixes #2772)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/model/RealmAnswer.java
  app/src/main/java/org/ole/planet/myplanet/model/RealmAnswer.kt
  app/src/main/java/org/ole/planet/myplanet/ui/exam/TakeExamFragment.java
Labels: peer review

#2812 actions: refactor `RealmOfflineActivity` model to kotlin (fixes #2810)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/model/RealmOfflineActivity.java
  app/src/main/java/org/ole/planet/myplanet/model/RealmOfflineActivity.kt
  app/src/main/java/org/ole/planet/myplanet/service/UploadManager.java
  app/src/main/java/org/ole/planet/myplanet/service/UserProfileDbHandler.java
Labels: peer review

#2813 actions: refactor `RealmNews` model to kotlin (fixes #2809)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/base/BaseNewsFragment.java
  app/src/main/java/org/ole/planet/myplanet/model/RealmNews.java
  app/src/main/java/org/ole/planet/myplanet/model/RealmNews.kt
  app/src/main/java/org/ole/planet/myplanet/service/UploadManager.java
  app/src/main/java/org/ole/planet/myplanet/ui/news/AdapterNews.java
  app/src/main/java/org/ole/planet/myplanet/ui/news/NewsDetailActivity.kt
  app/src/main/java/org/ole/planet/myplanet/ui/news/NewsFragment.java
  app/src/main/java/org/ole/planet/myplanet/ui/news/ReplyActivity.java
  app/src/main/java/org/ole/planet/myplanet/ui/team/teamDiscussion/DiscussionListFragment.java
Labels: peer review

#2817 actions: refactor `RealmRating` model to kotlin (fixes #2811)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/model/RealmRating.java
  app/src/main/java/org/ole/planet/myplanet/model/RealmRating.kt
  app/src/main/java/org/ole/planet/myplanet/service/UploadManager.java
  app/src/main/java/org/ole/planet/myplanet/ui/rating/RatingFragment.java
Labels: peer review

#2834 actions: refactor `RealmResourceActivity` model to kotlin (fixes #2829)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/model/RealmResourceActivity.java
  app/src/main/java/org/ole/planet/myplanet/model/RealmResourceActivity.kt
  app/src/main/java/org/ole/planet/myplanet/service/UploadManager.java
  app/src/main/java/org/ole/planet/myplanet/service/UserProfileDbHandler.java
Labels: peer review

#2861 actions: refactor `callback` interfaces to kotlin (fixes #2858)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/callback/NotificationCallback.java
  app/src/main/java/org/ole/planet/myplanet/callback/NotificationCallback.kt
  app/src/main/java/org/ole/planet/myplanet/callback/OnCourseItemSelected.java
  app/src/main/java/org/ole/planet/myplanet/callback/OnCourseItemSelected.kt
  app/src/main/java/org/ole/planet/myplanet/callback/OnFilterListener.java
  app/src/main/java/org/ole/planet/myplanet/callback/OnFilterListener.kt
  app/src/main/java/org/ole/planet/myplanet/callback/OnHomeItemClickListener.java
  app/src/main/java/org/ole/planet/myplanet/callback/OnHomeItemClickListener.kt
  app/src/main/java/org/ole/planet/myplanet/callback/OnLibraryItemSelected.java
  app/src/main/java/org/ole/planet/myplanet/callback/OnLibraryItemSelected.kt
  app/src/main/java/org/ole/planet/myplanet/callback/OnMyLifeItemSelected.java
  app/src/main/java/org/ole/planet/myplanet/callback/OnMyLifeItemSelected.kt
  app/src/main/java/org/ole/planet/myplanet/callback/OnRatingChangeListener.java
  app/src/main/java/org/ole/planet/myplanet/callback/OnRatingChangeListener.kt
  app/src/main/java/org/ole/planet/myplanet/callback/OnSelectedMyPersonal.java
  app/src/main/java/org/ole/planet/myplanet/callback/OnSelectedMyPersonal.kt
  app/src/main/java/org/ole/planet/myplanet/callback/ProgressBroadcastReceiver.java
  app/src/main/java/org/ole/planet/myplanet/callback/ProgressBroadcastReceiver.kt
  app/src/main/java/org/ole/planet/myplanet/callback/SuccessListener.java
  app/src/main/java/org/ole/planet/myplanet/callback/SuccessListener.kt
  app/src/main/java/org/ole/planet/myplanet/callback/SyncListener.java
  app/src/main/java/org/ole/planet/myplanet/callback/SyncListener.kt
  app/src/main/java/org/ole/planet/myplanet/callback/TagClickListener.java
  app/src/main/java/org/ole/planet/myplanet/callback/TagClickListener.kt
  app/src/main/java/org/ole/planet/myplanet/callback/UploadAttachmentListener.java
  app/src/main/java/org/ole/planet/myplanet/callback/UploadAttachmentListener.kt
Labels: peer review

#2828 actions: refactor `Markdown` utilities to kotlin (fixes #2827)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/course/AdapterCourses.java
  app/src/main/java/org/ole/planet/myplanet/ui/course/CourseDetailFragment.java
  app/src/main/java/org/ole/planet/myplanet/ui/course/CourseStepFragment.java
  app/src/main/java/org/ole/planet/myplanet/ui/exam/TakeExamFragment.java
  app/src/main/java/org/ole/planet/myplanet/ui/library/AdapterLibrary.java
  app/src/main/java/org/ole/planet/myplanet/ui/viewer/MarkdownViewerActivity.java
  app/src/main/java/org/ole/planet/myplanet/utilities/Markdown.kt
Labels: peer review

#2824 actions: refactor all `RealmTeam` models to kotlin (fixes #2821)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/model/RealmTeamLog.java
  app/src/main/java/org/ole/planet/myplanet/model/RealmTeamLog.kt
  app/src/main/java/org/ole/planet/myplanet/model/RealmTeamNotification.java
  app/src/main/java/org/ole/planet/myplanet/model/RealmTeamNotification.kt
  app/src/main/java/org/ole/planet/myplanet/model/RealmTeamTask.java
  app/src/main/java/org/ole/planet/myplanet/model/RealmTeamTask.kt
  app/src/main/java/org/ole/planet/myplanet/service/TaskNotificationWorker.java
  app/src/main/java/org/ole/planet/myplanet/service/UploadManager.java
  app/src/main/java/org/ole/planet/myplanet/ui/team/MyTeamsDetailFragment.java
  app/src/main/java/org/ole/planet/myplanet/ui/team/TeamDetailFragment.java
  app/src/main/java/org/ole/planet/myplanet/ui/team/teamDiscussion/DiscussionListFragment.java
  app/src/main/java/org/ole/planet/myplanet/ui/team/teamTask/AdapterTask.java
  app/src/main/java/org/ole/planet/myplanet/ui/team/teamTask/TeamTaskFragment.java
Labels: peer review, solve conflict

#2780 actions: refactor `RealmExamQuestion` model to kotlin (fixes #2775)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/model/RealmExamQuestion.java
  app/src/main/java/org/ole/planet/myplanet/model/RealmExamQuestion.kt
  app/src/main/java/org/ole/planet/myplanet/ui/exam/TakeExamFragment.java
Labels: peer review

#2835 actions: refactor `RealmStepExam` to kotlin (fixes #2830)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/base/BaseRecyclerFragment.java
  app/src/main/java/org/ole/planet/myplanet/base/BaseResourceFragment.java
  app/src/main/java/org/ole/planet/myplanet/model/RealmStepExam.java
  app/src/main/java/org/ole/planet/myplanet/model/RealmStepExam.kt
  app/src/main/java/org/ole/planet/myplanet/model/RealmSubmission.java
  app/src/main/java/org/ole/planet/myplanet/ui/course/AdapterSteps.java
  app/src/main/java/org/ole/planet/myplanet/ui/course/CourseStepFragment.java
  app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardActivity.java
  app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardActivity.java.lite
  app/src/main/java/org/ole/planet/myplanet/ui/exam/BaseExamFragment.java
  app/src/main/java/org/ole/planet/myplanet/ui/exam/TakeExamFragment.java
  app/src/main/java/org/ole/planet/myplanet/ui/submission/AdapterMySubmission.java
  app/src/main/java/org/ole/planet/myplanet/ui/survey/AdapterSurvey.java
  app/src/main/java/org/ole/planet/myplanet/ui/survey/SendSurveyFragment.java
Labels: peer review

#2838 actions: refactor `RealmTag` to kotlin (fixes #2833)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/base/BaseRecyclerFragment.java
  app/src/main/java/org/ole/planet/myplanet/base/BaseResourceFragment.java
  app/src/main/java/org/ole/planet/myplanet/model/RealmTag.java
  app/src/main/java/org/ole/planet/myplanet/model/RealmTag.kt
  app/src/main/java/org/ole/planet/myplanet/ui/course/AdapterCourses.java
  app/src/main/java/org/ole/planet/myplanet/ui/course/CourseFragment.java
  app/src/main/java/org/ole/planet/myplanet/ui/library/AdapterLibrary.java
  app/src/main/java/org/ole/planet/myplanet/ui/library/CollectionsFragment.java
  app/src/main/java/org/ole/planet/myplanet/ui/library/LibraryFragment.java
  app/src/main/java/org/ole/planet/myplanet/ui/library/TagExpandableAdapter.java
Labels: peer review

#2836 actions: refactor `RealmSubmission` to kotlin (fixes #2831)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/base/BaseResourceFragment.java
  app/src/main/java/org/ole/planet/myplanet/model/RealmSubmission.java
  app/src/main/java/org/ole/planet/myplanet/model/RealmSubmission.kt
  app/src/main/java/org/ole/planet/myplanet/service/UploadManager.java
  app/src/main/java/org/ole/planet/myplanet/ui/course/CourseProgressActivity.kt
  app/src/main/java/org/ole/planet/myplanet/ui/dashboard/BellDashboardFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/exam/BaseExamFragment.java
  app/src/main/java/org/ole/planet/myplanet/ui/exam/TakeExamFragment.java
  app/src/main/java/org/ole/planet/myplanet/ui/exam/UserInformationFragment.java
  app/src/main/java/org/ole/planet/myplanet/ui/submission/AdapterMySubmission.java
  app/src/main/java/org/ole/planet/myplanet/ui/survey/SendSurveyFragment.java
Labels: peer review

#2837 actions: refactor `RealmSubmitPhotos` to kotlin (fixes #2832)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/datamanager/FileUploadService.java
  app/src/main/java/org/ole/planet/myplanet/model/RealmSubmitPhotos.java
  app/src/main/java/org/ole/planet/myplanet/model/RealmSubmitPhotos.kt
  app/src/main/java/org/ole/planet/myplanet/service/UploadManager.java
  app/src/main/java/org/ole/planet/myplanet/ui/exam/BaseExamFragment.java
Labels: peer review

#2703 chat: save and continue conversations (fixes #2702)
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/AndroidManifest.xml.lite
  app/src/main/java/org/ole/planet/myplanet/model/Conversation.java
  app/src/main/java/org/ole/planet/myplanet/model/RealmChatHistory.java
  app/src/main/java/org/ole/planet/myplanet/service/SyncManager.java
  app/src/main/java/org/ole/planet/myplanet/service/TransactionSyncManager.java
  app/src/main/java/org/ole/planet/myplanet/ui/chat/ChatActivity.kt
  app/src/main/java/org/ole/planet/myplanet/ui/chat/ChatAdapter.kt
  app/src/main/java/org/ole/planet/myplanet/ui/chat/ChatDetailFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/chat/ChatHistoryListAdapter.kt
  app/src/main/java/org/ole/planet/myplanet/ui/chat/ChatHistoryListFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/chat/ChatRequestModel.kt
  app/src/main/java/org/ole/planet/myplanet/ui/chat/ChatResponseModel.kt
  app/src/main/java/org/ole/planet/myplanet/ui/chat/ChatViewModel.kt
  app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardActivity.java
  app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardActivity.java.lite
  app/src/main/res/layout/fragment_chat_detail.xml
  app/src/main/res/layout/fragment_chat_history_list.xml
  app/src/main/res/layout/item_ai_response_message.xml
  app/src/main/res/layout/row_chat_history.xml
Labels: peer review

#2880 actions: refactor file permission handling (fixes #2879)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/base/PermissionActivity.java
  app/src/main/java/org/ole/planet/myplanet/base/PermissionActivity.java.lite
Labels: peer review

#2874 login: deny deleted learners access (fixes #2866)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/model/RealmUserModel.kt
  app/src/main/java/org/ole/planet/myplanet/ui/sync/SyncActivity.java
Labels: peer review

#2849 actions: refactor `SourceFile` model to kotlin (fixes #2845)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/model/SourceFile.java
  app/src/main/java/org/ole/planet/myplanet/model/SourceFile.kt
Labels: peer review

#2850 actions: refactor `Reference` model to kotlin (fixes #2846)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/model/Reference.java
  app/src/main/java/org/ole/planet/myplanet/model/Reference.kt
  app/src/main/java/org/ole/planet/myplanet/ui/references/ReferenceFragment.java
Labels: peer review

#2855 actions: refactor `RealmMyTeam` model to kotlin (fixes #2854)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/model/RealmMyLibrary.kt
  app/src/main/java/org/ole/planet/myplanet/model/RealmMyTeam.java
  app/src/main/java/org/ole/planet/myplanet/model/RealmMyTeam.kt
  app/src/main/java/org/ole/planet/myplanet/service/UploadManager.java
  app/src/main/java/org/ole/planet/myplanet/ui/community/AddLinkFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/community/LeadersFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/community/ServicesFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/enterprises/AdapterFinance.java
  app/src/main/java/org/ole/planet/myplanet/ui/enterprises/FinanceFragment.java
  app/src/main/java/org/ole/planet/myplanet/ui/sync/SyncActivity.java
  app/src/main/java/org/ole/planet/myplanet/ui/team/AdapterTeam.java
  app/src/main/java/org/ole/planet/myplanet/ui/team/AdapterTeamList.kt
  app/src/main/java/org/ole/planet/myplanet/ui/team/MyTeamsDetailFragment.java
  app/src/main/java/org/ole/planet/myplanet/ui/team/PlanFragment.java
  app/src/main/java/org/ole/planet/myplanet/ui/team/TeamDetailFragment.java
  app/src/main/java/org/ole/planet/myplanet/ui/team/TeamFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/team/TeamPagerAdapter.java
  app/src/main/java/org/ole/planet/myplanet/ui/team/teamCourse/TeamCourseFragment.java
  app/src/main/java/org/ole/planet/myplanet/ui/team/teamDiscussion/DiscussionListFragment.java
  app/src/main/java/org/ole/planet/myplanet/ui/team/teamMember/AdapterJoinedMember.java
  app/src/main/java/org/ole/planet/myplanet/ui/team/teamMember/AdapterMemberRequest.java
  app/src/main/java/org/ole/planet/myplanet/ui/team/teamMember/JoinedMemberFragment.java
  app/src/main/java/org/ole/planet/myplanet/ui/team/teamMember/MembersFragment.java
  app/src/main/java/org/ole/planet/myplanet/ui/team/teamResource/TeamResourceFragment.java
  app/src/main/java/org/ole/planet/myplanet/ui/team/teamTask/TeamTaskFragment.java
Labels: peer review

#2878 actions: more sync stability (fixes #2875)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/utilities/FileUtils.java
Labels: review, priority

#2877 dashboard: more stability (fixes #2876)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardActivity.java
Labels: review

#2848 actions: refactor `Row` model to kotlin (fixes #2844)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/model/Rows.java
  app/src/main/java/org/ole/planet/myplanet/model/Rows.kt
  app/src/main/java/org/ole/planet/myplanet/service/SyncManager.java
  app/src/main/java/org/ole/planet/myplanet/service/TransactionSyncManager.java
Labels: peer review

#2908 login: better name check (fixes #2900)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/sync/SyncActivity.java
Labels: review

#2862 resources: update list on submit (fixes #2860)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/library/AddResourceFragment.java
  app/src/main/java/org/ole/planet/myplanet/ui/myPersonals/MyPersonalsFragment.java
Labels: peer review

#2857 actions: refactor `RealmRemovedLog` model to kotlin (fixes #2856)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/model/RealmRemovedLog.java
  app/src/main/java/org/ole/planet/myplanet/model/RealmRemovedLog.kt
Labels: peer review

#2890 actions: refactor `CheckboxListView` utilities to kotlin (fixes #2885)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/base/BaseResourceFragment.java
  app/src/main/java/org/ole/planet/myplanet/ui/library/AddResourceActivity.java
  app/src/main/java/org/ole/planet/myplanet/ui/survey/SendSurveyFragment.java
  app/src/main/java/org/ole/planet/myplanet/ui/team/teamResource/TeamResourceFragment.java
  app/src/main/java/org/ole/planet/myplanet/ui/userprofile/EditAchievementFragment.java
  app/src/main/java/org/ole/planet/myplanet/utilities/CheckboxListView.java
  app/src/main/java/org/ole/planet/myplanet/utilities/CheckboxListView.kt
Labels: peer review

#2907 service: improve `TaskNotificationWorker` (fixes #2899)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/service/TaskNotificationWorker.java
Labels: review

#2888 actions: refactor `BottomNavigationViewHelper` utilities to kotlin (fixes #2883)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/utilities/BottomNavigationViewHelper.java
  app/src/main/java/org/ole/planet/myplanet/utilities/BottomNavigationViewHelper.kt
Labels: peer review

#2916 actions: refactor `RealmChatHistory` model to kotlin (fixes #2915)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/model/Conversation.java
  app/src/main/java/org/ole/planet/myplanet/model/Conversation.kt
  app/src/main/java/org/ole/planet/myplanet/model/RealmChatHistory.java
  app/src/main/java/org/ole/planet/myplanet/model/RealmChatHistory.kt
  app/src/main/java/org/ole/planet/myplanet/ui/chat/ChatDetailFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/chat/ChatHistoryListAdapter.kt
Labels: peer review

#2887 actions: refactor `AuthSessionUpdater` utilities to kotlin (fixes #2882)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/viewer/VideoPlayerActivity.java
  app/src/main/java/org/ole/planet/myplanet/utilities/AuthSessionUpdater.java
  app/src/main/java/org/ole/planet/myplanet/utilities/AuthSessionUpdater.kt
Labels: peer review

#2865 actions: refactor `AudioRecorderService` service to kotlin (fixes #2864)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/service/AudioRecorderService.java
  app/src/main/java/org/ole/planet/myplanet/service/AudioRecorderService.kt
Labels: peer review

#2889 actions: refactor `CameraUtils` utilities to kotlin (fixes #2884)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/utilities/CameraUtils.java
  app/src/main/java/org/ole/planet/myplanet/utilities/CameraUtils.kt
Labels: peer review

#2901 actions: refactor `Constants` utilities to kotlin (fixes #2893)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/utilities/Constants.java
  app/src/main/java/org/ole/planet/myplanet/utilities/Constants.kt
Labels: peer review

#2902 actions: refactor `CustomClickableSpan` utilities to kotlin (fixes #2894)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/utilities/CustomClickableSpan.java
  app/src/main/java/org/ole/planet/myplanet/utilities/CustomClickableSpan.kt
Labels: peer review

#2903 actions: refactor `CustomViewPager` utilities to kotlin (fixes #2895)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/utilities/CustomViewPager.java
  app/src/main/java/org/ole/planet/myplanet/utilities/CustomViewPager.kt
Labels: peer review
