Repository open-learning-exchange/myplanet, pull requests merged in 2024-08, with the labels that each got.

#3982 sync: easier configuration (fixes #3742)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/datamanager/Service.kt
  app/src/main/java/org/ole/planet/myplanet/ui/sync/SyncActivity.kt
  app/src/main/res/layout/dialog_server_url_.xml
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-ne/strings.xml
  app/src/main/res/values-so/strings.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
  gradle.properties
Labels: sync conf

#3979 settings: smoother languages in dark mode (fixes #3977)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/MainApplication.kt
  app/src/main/java/org/ole/planet/myplanet/ui/SettingActivity.kt
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-ne/strings.xml
  app/src/main/res/values-so/strings.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/pref.xml
Labels: ready to merge

#3981 teams: smoother creation and search (fixes #3980)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/team/TeamFragment.kt
Labels: ready to merge

#3984 all: less service warnings is more (fixes #3983)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/base/BaseNewsFragment.kt
  app/src/main/java/org/ole/planet/myplanet/service/AudioRecorderService.kt
  app/src/main/java/org/ole/planet/myplanet/service/AutoSyncWorker.kt
  app/src/main/java/org/ole/planet/myplanet/service/StayOnlineWorker.kt
  app/src/main/java/org/ole/planet/myplanet/service/SyncManager.kt
  app/src/main/java/org/ole/planet/myplanet/service/UploadManager.kt
  app/src/main/java/org/ole/planet/myplanet/service/UploadToShelfService.kt
  app/src/main/java/org/ole/planet/myplanet/service/UserProfileDbHandler.kt
  app/src/main/java/org/ole/planet/myplanet/ui/SettingActivity.kt
  app/src/main/java/org/ole/planet/myplanet/ui/dashboard/BaseDashboardFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardActivity.kt
  app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardActivity.kt.lite
  app/src/main/java/org/ole/planet/myplanet/ui/sync/ProcessUserDataActivity.kt
  app/src/main/java/org/ole/planet/myplanet/ui/sync/SyncActivity.kt
Labels: ready to merge

#3989 community: smoother news with shared chats (fixes #3987)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/chat/ChatAdapter.kt
  app/src/main/java/org/ole/planet/myplanet/ui/news/AdapterNews.kt
Labels: ready to merge

#4002 resources: smoother filter layout (fixes #3985)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/resources/ResourcesFilterFragment.kt
  app/src/main/res/layout/fragment_library_filter.xml
Labels: ready to merge

#4005 all: consistent left menu (fixes 3991)
  app/build.gradle
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-so/strings.xml
  app/src/main/res/values/strings.xml
Labels: ready to merge

#4007 teams: smoother dark mode (fixes #3993)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/enterprises/EnterpriseCalendarFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/team/teamResource/TeamResourceFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/team/teamTask/TeamTaskFragment.kt
  app/src/main/res/layout/add_meetup.xml
  app/src/main/res/layout/alert_task.xml
  app/src/main/res/layout/fragment_team_task.xml
  app/src/main/res/layout/my_library_alertdialog.xml
  app/src/main/res/layout/row_member_request.xml
  app/src/main/res/layout/row_task.xml
  app/src/main/res/layout/row_team_resource.xml
  app/src/main/res/values-night/styles.xml
  app/src/main/res/values/styles.xml
Labels: ready to merge

#4021 chat: smoother dark mode (fixes #4019)
  app/build.gradle
  app/src/main/res/layout/row_news.xml
Labels: ready to merge

#4011 courses: smoother dark mode (fixes #3999)
  app/build.gradle
  app/src/main/res/layout/fragment_course_step.xml
  app/src/main/res/layout/fragment_rating.xml
  app/src/main/res/layout/row_steps.xml
Labels: review, ready to merge, peer review

#4033 all: default dark mode to follow system (fixes #4026)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/MainApplication.kt
  app/src/main/res/xml/pref.xml
Labels: review, peer review

#4039 all: smoother arabic strings (fixes #4023)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/dashboard/BaseDashboardFragment.kt
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-ne/strings.xml
  app/src/main/res/values-so/strings.xml
  app/src/main/res/values/strings.xml
Labels: ready to merge

#4052 actions: remove jcenter from gradle (fixes #4051)
  app/build.gradle
  library/CalendarView-1.0.4.aar
  library/barteksc-android-pdf-viewer-3.2.0-beta.1.aar
  library/build.gradle
  library/flexbox-1.0.0.aar
  library/materialarcmenu-2.0.0.aar
Labels: review, priority, peer review

#4034 all: align string files (fixes #4022)
  app/build.gradle
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values/strings.xml
Labels: ready to merge

#4029 teams: smoother tasks icons (fixes #4027)
  app/build.gradle
  app/src/main/res/layout/row_task.xml
Labels: ready to merge

#4032 sync: more server configurations (fixes #4031)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/model/ServerAddressesModel.kt
  app/src/main/java/org/ole/planet/myplanet/ui/sync/ServerAddressAdapter.kt
  app/src/main/java/org/ole/planet/myplanet/ui/sync/SyncActivity.kt
  app/src/main/res/layout/dialog_server_url_.xml
  app/src/main/res/layout/item_server_address.xml
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-ne/strings.xml
  app/src/main/res/values-so/strings.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  gradle.properties
Labels: ready to merge

#4044 all: smoother chat icon in navbar (fixes #4042)
  app/build.gradle
  app/src/main/res/drawable/chat.xml
Labels: ready to merge

#4053 community: dark mode message replies (fixes #4035)
  app/build.gradle
  app/src/main/res/layout/activity_reply.xml
Labels: ready to merge

#4056 login: smoother guest (fixes #4013)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/sync/LoginActivity.kt
Labels: ready to merge

#4064 sync: smoother fail message (fixes #4055)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/datamanager/Service.kt
  app/src/main/java/org/ole/planet/myplanet/ui/sync/SyncActivity.kt
  app/src/main/java/org/ole/planet/myplanet/utilities/NetworkUtils.kt
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-ne/strings.xml
  app/src/main/res/values-so/strings.xml
  app/src/main/res/values/strings.xml
Labels: ready to merge

#4065 all: smoother sidebar logo (fixes #4043)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardActivity.kt
  app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardActivity.kt.lite
Labels: ready to merge

#4066 resources: smoother audios (fixes #4012)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/viewer/AudioPlayerActivity.kt
Labels: ready to merge

#4050 teams: smoother dark mode (fixes #4036)
  app/build.gradle
  app/src/main/res/layout-w600dp/fragment_team_detail.xml
  app/src/main/res/layout/fragment_enterprise_calendar.xml
  app/src/main/res/layout/fragment_members.xml
  app/src/main/res/layout/fragment_plan.xml
  app/src/main/res/layout/fragment_team_course.xml
  app/src/main/res/layout/fragment_team_detail.xml
  app/src/main/res/layout/fragment_team_resource.xml
  app/src/main/res/layout/fragment_team_task.xml
Labels: review, peer review

#4071 login: smoother teams (fixes #4068)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/sync/LoginActivity.kt
Labels: ready to merge

#4076 feedback: smoother columns (fixes #4028)
  app/build.gradle
  app/src/main/res/layout/fragment_feedback_list.xml
  app/src/main/res/layout/row_feedback.xml
Labels: ready to merge

#4096 all: positional strings formatting (fixes #4093)
  app/build.gradle
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-ne/strings.xml
  app/src/main/res/values-so/strings.xml
  app/src/main/res/values/strings.xml
Labels: ready to merge

#4099 login: smoother server dialog (fixes #4098)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/sync/ServerAddressAdapter.kt
  app/src/main/java/org/ole/planet/myplanet/ui/sync/SyncActivity.kt
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-ne/strings.xml
  app/src/main/res/values-so/strings.xml
  app/src/main/res/values/strings.xml
Labels: priority, ready to merge

#4038 community: smoother guest access (fixes #3994)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/community/ServicesFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/enterprises/ReportsFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/sync/DashboardElementActivity.kt
  app/src/main/java/org/ole/planet/myplanet/ui/team/BaseTeamFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/team/PlanFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/team/TeamDetailFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/team/teamCourse/TeamCourseFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/team/teamDiscussion/DiscussionListFragment.kt
Labels: priority, ready to merge

#4101 login: only one team list (fixes #4097)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/sync/SyncActivity.kt
  app/src/main/res/layout/dialog_server_url_.xml
Labels: ready to merge

#4115 all: use caching `planet.gt` (fixes #4114)
  app/build.gradle
  gradle.properties
Labels: priority, ready to merge

#4109 login: smoother layout setup (fixes #4108)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/team/teamMember/MemberDetailFragment.kt
Labels: review, priority, peer review

#4136 teams: smoother list with icons (fixes #4124)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/team/AdapterTeamList.kt
  app/src/main/res/drawable/ic_join_request.xml
  app/src/main/res/layout/item_team_list.xml
Labels: ready to merge

#4143 login: smoother team dark mode (fixes #4126)
  app/build.gradle
  app/src/main/res/layout-large-land/activity_login.xml
  app/src/main/res/layout-night/activity_login.xml
  app/src/main/res/layout-normal-land/activity_login.xml
  app/src/main/res/layout-xlarge-land/activity_login.xml
  app/src/main/res/layout/activity_login.xml
Labels: ready to merge

#4146 resources: smoother pdf (fixes #4145)
  app/build.gradle
Labels: ready to merge

#4147 all: activate `libs` directory (fixes #4154)
  app/build.gradle
  app/libs/CalendarView-1.0.4.aar
  app/libs/ChipCloud-3.0.5.aar
  app/libs/barteksc-android-pdf-viewer-3.2.0-beta.1.aar
  app/libs/flexbox-1.0.0.aar
  app/libs/materialarcmenu-2.0.0.aar
  library/build.gradle
Labels: ready to merge
