Repository open-learning-exchange/myplanet, pull requests merged in 2024-06, with the labels that each got.

#3541 dashboard: smoother realm writing (fixes #3540)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/dashboard/BaseDashboardFragment.kt
Labels: review

#3538 resources: cleaner video management (fixes #3537)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/viewer/VideoPlayerActivity.kt
Labels: review

#3544 resources: smoother details view (fixes #3543)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/resources/AdapterResource.kt
  app/src/main/java/org/ole/planet/myplanet/ui/resources/ResourceDetailFragment.kt
  app/src/main/res/layout/fragment_library_detail.xml
Labels: review

#3556 courses: more responsive details (fixes #3553)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/courses/AdapterCourses.kt
  app/src/main/res/layout/row_course.xml
Labels: review

#3565 sync: divide for smoother login (fixes #3562)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/base/BaseResourceFragment.kt
  app/src/main/java/org/ole/planet/myplanet/datamanager/MyDownloadService.kt
  app/src/main/java/org/ole/planet/myplanet/model/RealmMyCourse.kt
  app/src/main/java/org/ole/planet/myplanet/service/SyncManager.kt
  app/src/main/java/org/ole/planet/myplanet/service/TransactionSyncManager.kt
  app/src/main/java/org/ole/planet/myplanet/ui/dashboard/BaseDashboardFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/dictionary/DictionaryActivity.kt
  app/src/main/java/org/ole/planet/myplanet/ui/sync/ProcessUserDataActivity.kt
  app/src/main/java/org/ole/planet/myplanet/ui/sync/SyncActivity.kt
  app/src/main/java/org/ole/planet/myplanet/utilities/DialogUtils.kt
  app/src/main/java/org/ole/planet/myplanet/utilities/Utilities.kt
Labels: review

#3566 mycourses: show downloadable courses resources (fixes #3563)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/base/BaseRecyclerFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/courses/CoursesFragment.kt
Labels: review

#3578 community: default text if empty (fixes #2256)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/community/ServicesFragment.kt
  app/src/main/java/org/ole/planet/myplanet/utilities/Markdown.kt
  app/src/main/res/layout/fragment_services.xml
Labels: review

#3593 news: show shared chats (fixes #3582)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/model/RealmNews.kt
  app/src/main/java/org/ole/planet/myplanet/ui/chat/ChatAdapter.kt
  app/src/main/java/org/ole/planet/myplanet/ui/news/AdapterNews.kt
  app/src/main/java/org/ole/planet/myplanet/ui/news/NewsFragment.kt
  app/src/main/res/layout/row_news.xml
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-ne/strings.xml
  app/src/main/res/values-so/strings.xml
  app/src/main/res/values/strings.xml
Labels: peer review

#3586 mylibrary: show only my resources (fixes #3567)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/base/BaseResourceFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/courses/CourseDetailFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/resources/ResourceDetailFragment.kt
  app/src/main/java/org/ole/planet/myplanet/utilities/DownloadUtils.kt
Labels: peer review

#3614 teams: show member details (fixes #3546)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/service/UserProfileDbHandler.kt
  app/src/main/java/org/ole/planet/myplanet/ui/team/teamMember/AdapterJoinedMember.kt
  app/src/main/java/org/ole/planet/myplanet/ui/team/teamMember/MemberDetailFragment.kt
  app/src/main/res/layout/fragment_member_detail.xml
  app/src/main/res/layout/row_joined_user.xml
Labels: ready to merge

#3625 all: use `android.hardware.camera2.*` (fixes #3619)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/courses/CourseStepFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/exam/TakeExamFragment.kt
  app/src/main/java/org/ole/planet/myplanet/utilities/CameraUtils.kt
Labels: ready to merge

#3631 actions: less warnings is more (fixes #3627)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/datamanager/FileUploadService.kt
  app/src/main/java/org/ole/planet/myplanet/service/UploadManager.kt
Labels: ready to merge

#3642 dashboard: smoother lifecycle management (fixes #3629)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/sync/DashboardElementActivity.kt
Labels: review

#3636 actions: better discord success message (fixes #3633)
  .github/workflows/android-release.yml
  app/build.gradle
Labels: review

#3606 sync: allow only stable versions (fixes #3605)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/datamanager/Service.kt
  app/src/main/java/org/ole/planet/myplanet/ui/sync/SyncActivity.kt
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-ne/strings.xml
  app/src/main/res/values-so/strings.xml
  app/src/main/res/values/strings.xml
Labels: review

#3657 sync: trim lite version (fixes #3656)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/datamanager/Service.kt
Labels: review

#3637 actions: less warnings is more (fixes #3626)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardActivity.kt
Labels: ready to merge

#3641 actions: less warnings is more (fixes #3640)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/dashboard/MyActivityFragment.kt
Labels: ready to merge

#3666 actions: less warnings is more (fixes #3665)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/community/CommunityPagerAdapter.kt
Labels: ready to merge

#3655 actions: less warnings is more (fixes #3654)
  .github/workflows/android-build.yml
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/AndroidManifest.xml.lite
  app/src/main/java/org/ole/planet/myplanet/base/BaseContainerFragment.kt
  app/src/main/java/org/ole/planet/myplanet/base/BaseContainerFragment.kt.lite
  app/src/main/java/org/ole/planet/myplanet/ui/dashboard/BaseDashboardFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardActivity.kt
  app/src/main/java/org/ole/planet/myplanet/ui/news/NewsFragment.kt
Labels: ready to merge

#3681 actions: only one language bundle (fixes #3678)
  app/build.gradle
Labels: review

#3680 chat: share with community, teams and enterprises (fixes #3679)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/model/RealmChatHistory.kt
  app/src/main/java/org/ole/planet/myplanet/model/RealmNews.kt
  app/src/main/java/org/ole/planet/myplanet/ui/chat/ChatHistoryListAdapter.kt
  app/src/main/java/org/ole/planet/myplanet/ui/news/ExpandableListAdapter.kt
  app/src/main/java/org/ole/planet/myplanet/ui/news/GrandChildAdapter.kt
  app/src/main/res/drawable/baseline_share_24.xml
  app/src/main/res/drawable/custom_expandable.xml
  app/src/main/res/drawable/down_arrow.xml
  app/src/main/res/drawable/up_arrow.xml
  app/src/main/res/layout/add_note_dialog.xml
  app/src/main/res/layout/chat_share_dialog.xml
  app/src/main/res/layout/child_item.xml
  app/src/main/res/layout/expandable_list_grand_child_item.xml
  app/src/main/res/layout/expandable_list_group.xml
  app/src/main/res/layout/expandable_list_item.xml
  app/src/main/res/layout/grand_child_recyclerview_dialog.xml
  app/src/main/res/layout/group_item.xml
  app/src/main/res/layout/row_chat_history.xml
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-ne/strings.xml
  app/src/main/res/values-so/strings.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
Labels: ready to merge

#3672 actions: less warnings is more (fixes #3671)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/sync/LoginActivity.kt
Labels: ready to merge

#3677 sync: team selection (fixes #3668)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/sync/SyncActivity.kt
Labels: ready to merge

#3692 teams: smoother plan (fixes #3690)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/team/PlanFragment.kt
Labels: ready to merge

#3697 dashboard: safer fragment transactions (fixes #3693)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/dashboard/BaseDashboardFragment.kt
Labels: ready to merge

#3715 actions: bump `dogi/sign-android-release` to 5.1 (fixes #3711)
  .github/workflows/android-release.yml
  app/build.gradle
Labels: dependencies, github_actions

#3723 actions: less warnings is more (fixes #3722)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/datamanager/ApiClient.kt
Labels: ready to merge

#3732 actions: smoother manual release (fixes #3712)
  .github/workflows/android-release.yml
  app/build.gradle
Labels: ready to merge

#3736 surveys: smoother empty list (fixes #3724)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/base/BaseRecyclerFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/submission/MySubmissionFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/survey/SurveyFragment.kt
  app/src/main/res/layout/fragment_my_submission.xml
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-ne/strings.xml
  app/src/main/res/values-so/strings.xml
  app/src/main/res/values/strings.xml
Labels: ready to merge

#3737 sync: smoother downloads (fixes #3728)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/datamanager/MyDownloadService.kt
  app/src/main/java/org/ole/planet/myplanet/utilities/DialogUtils.kt
  app/src/main/java/org/ole/planet/myplanet/utilities/Utilities.kt
Labels: ready to merge
