Repository open-learning-exchange/myplanet, pull requests merged in 2024-07, with the labels that each got.

#3735 chat: mark shared (fixes #3734)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/chat/ChatHistoryListAdapter.kt
  app/src/main/java/org/ole/planet/myplanet/ui/chat/ChatHistoryListFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/news/NewsFragment.kt
  app/src/main/res/drawable/baseline_check_24.xml
  app/src/main/res/layout/row_chat_history.xml
Labels: ready to merge

#3730 all: smoother dialogs (fixes #3729)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/base/BaseDialogFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/feedback/FeedbackFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/rating/RatingFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/resources/CollectionsFragment.kt
  app/src/main/res/layout/fragment_feedback.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/styles.xml
Labels: review, peer review

#3746 chats: smoother empty history (fixes #3725)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/base/BaseRecyclerFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/chat/ChatHistoryListFragment.kt
  app/src/main/res/layout/fragment_chat_history_list.xml
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-ne/strings.xml
  app/src/main/res/values-so/strings.xml
  app/src/main/res/values/strings.xml
Labels: review, peer review

#3684 dashboard: better strings (fixes #3683)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardActivity.kt
  app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardActivity.kt.lite
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-ne/strings.xml
  app/src/main/res/values-so/strings.xml
  app/src/main/res/values/strings.xml
Labels: ready to merge

#3752 all: add LICENSE (fixes #3751)
  LICENSE
  app/build.gradle
Labels: ready to merge

#3750 all: less warnings is more (fixes #3749)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/helpwanted/HelpWantedFragment.kt
  app/src/main/java/org/ole/planet/myplanet/utilities/JsonParserUtils.kt
Labels: ready to merge

#3703 actions: less warnings is more (fixes #3699)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/team/MyTeamsDetailFragment.kt
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-ne/strings.xml
  app/src/main/res/values-so/strings.xml
  app/src/main/res/values/strings.xml
Labels: ready to merge

#3748 chats: smoother history (fixes #3747)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/chat/ChatAdapter.kt
  app/src/main/java/org/ole/planet/myplanet/ui/chat/ChatHistoryListAdapter.kt
Labels: ready to merge

#3763 actions: smoother release versions (fixes #3762)
  .github/workflows/android-build.yml
  .github/workflows/android-release.yml
  app/build.gradle
Labels: review, peer review

#3768 actions: better release outputs (fixes #3761)
  .github/workflows/android-build.yml
  .github/workflows/android-release.yml
  app/build.gradle
Labels: review, peer review

#3769 actions: better `lite` build test (fixes #3695)
  .github/workflows/android-build.yml
  app/build.gradle
Labels: review, peer review

#3765 actions: less warnings is more (fixes #3764)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/helpwanted/HelpWantedFragment.kt
Labels: ready to merge

#3767 chats: smoother text (fixes #3766)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/chat/ChatAdapter.kt
  app/src/main/java/org/ole/planet/myplanet/ui/chat/ChatDetailFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/chat/ChatHistoryListAdapter.kt
  app/src/main/java/org/ole/planet/myplanet/ui/chat/ChatHistoryListFragment.kt
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-ne/strings.xml
  app/src/main/res/values-so/strings.xml
  app/src/main/res/values/strings.xml
Labels: ready to merge

#3773 actions: less warnings is more (fixes #3772)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/utilities/FileUtils.kt
Labels: ready to merge

#3781 actions: less warnings is more (fixes #3777)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/courses/CourseStepFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/exam/TakeExamFragment.kt
  app/src/main/java/org/ole/planet/myplanet/utilities/CameraUtils.kt
Labels: ready to merge

#3783 feedback: smoother empty list (fixes #3726)
  app/src/main/java/org/ole/planet/myplanet/base/BaseRecyclerFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/feedback/FeedbackListFragment.kt
  app/src/main/res/layout/fragment_feedback_list.xml
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-ne/strings.xml
  app/src/main/res/values-so/strings.xml
  app/src/main/res/values/strings.xml
Labels: ready to merge

#3785 resources: safer transactions (fixes #3645)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/resources/ResourcesFragment.kt
Labels: ready to merge

#3786 chat: smoother refresh (fixes #3784)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/model/RealmChatHistory.kt
  app/src/main/java/org/ole/planet/myplanet/ui/chat/ChatDetailFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/chat/ChatHistoryListAdapter.kt
  app/src/main/java/org/ole/planet/myplanet/ui/chat/ChatHistoryListFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardActivity.kt
  app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardActivity.kt.lite
Labels: ready to merge

#3790 courses: smoother steps (fixes #3789)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/courses/CourseStepFragment.kt
Labels: ready to merge

#3798 community: smoother tabs (fixes #3797)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/community/AdapterLeader.kt
  app/src/main/java/org/ole/planet/myplanet/ui/community/CommunityTabFragment.kt
Labels: ready to merge

#3796 actions: less warnings is more (fixes #3795)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/team/BaseTeamFragment.kt
Labels: ready to merge

#3782 actions: less warnings is more (fixes #3775)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/utilities/VersionUtils.kt
Labels: ready to merge

#3792 actions: smoother build (fixes #3780) (fixes #3778)
  app/build.gradle
Labels: ready to merge

#3807 all: ensure compatibility (fixes #3774)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/base/BaseRecyclerFragment.kt
Labels: ready to merge

#3808 dashboard: stabler fragments (fixes #3770)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/sync/DashboardElementActivity.kt
Labels: ready to merge

#3809 login: smoother team list (fixes #3771)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/sync/LoginActivity.kt
Labels: ready to merge

#3805 actions: smoother translation files (fixes #3793)
  app/build.gradle
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-ne/strings.xml
  app/src/main/res/values-so/strings.xml
  app/src/main/res/values/strings.xml
Labels: ready to merge

#3817 dashboard: smoother texts (fixes #3816)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/dashboard/BaseDashboardFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/dashboard/BaseDashboardFragmentPlugin.kt
  app/src/main/java/org/ole/planet/myplanet/ui/dashboard/BellDashboardFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardActivity.kt
  app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardActivity.kt.lite
  app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/dashboard/notification/AdapterNotification.kt
  app/src/main/java/org/ole/planet/myplanet/ui/dashboard/notification/NotificationFragment.kt
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-ne/strings.xml
  app/src/main/res/values-so/strings.xml
  app/src/main/res/values/strings.xml
Labels: ready to merge

#3823 all: log syncs (fixes #3819)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/MainApplication.kt
  app/src/main/java/org/ole/planet/myplanet/ui/sync/SyncActivity.kt
Labels: ready to merge

#3824 settings: smoother reset (fixes #3822)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/sync/SyncActivity.kt
Labels: ready to merge

#3825 mylife: stabler list (fixes #3821)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/dashboard/BaseDashboardFragment.kt
Labels: ready to merge

#3851 mymeetup: smoother texts (fixes #3849)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/mylife/AdapterMyLife.kt
  app/src/main/java/org/ole/planet/myplanet/ui/mymeetup/AdapterMeetup.kt
  app/src/main/java/org/ole/planet/myplanet/ui/mymeetup/MyMeetupDetailFragment.kt
Labels: ready to merge

#3856 sync: smoother large data (fixes #3855)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/datamanager/MyDownloadService.kt
  app/src/main/java/org/ole/planet/myplanet/model/RealmMyCourse.kt
  app/src/main/java/org/ole/planet/myplanet/utilities/Utilities.kt
Labels: ready to merge

#3857 chat: smoother most recently used list (fixes #3832)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/model/RealmChatHistory.kt
  app/src/main/java/org/ole/planet/myplanet/ui/chat/ChatHistoryListAdapter.kt
Labels: ready to merge

#3812 teams: smoother messages (fixes #3592)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/team/TeamPagerAdapter.kt
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-ne/strings.xml
  app/src/main/res/values-so/strings.xml
  app/src/main/res/values/strings.xml
Labels: ready to merge

#3837 mylife: smoother dictionary texts (fixes #3835)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/dictionary/DictionaryActivity.kt
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-ne/strings.xml
  app/src/main/res/values-so/strings.xml
  app/src/main/res/values/strings.xml
Labels: ready to merge

#3839 enterprises: smoother texts (fixes #3838)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/enterprises/AdapterCalendar.kt
  app/src/main/java/org/ole/planet/myplanet/ui/enterprises/AdapterFinance.kt
  app/src/main/java/org/ole/planet/myplanet/ui/enterprises/AdapterReports.kt
  app/src/main/java/org/ole/planet/myplanet/ui/enterprises/EnterpriseCalendarFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/enterprises/FinanceFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/enterprises/ReportsFragment.kt
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-ne/strings.xml
  app/src/main/res/values-so/strings.xml
  app/src/main/res/values/strings.xml
Labels: ready to merge

#3843 exam: smoother texts (fixes #3842)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/exam/BaseExamFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/exam/TakeExamFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/exam/UserInformationFragment.kt
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-ne/strings.xml
  app/src/main/res/values-so/strings.xml
  app/src/main/res/values/strings.xml
Labels: ready to merge

#3848 myhealth: smoother texts (fixes #3847)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/myhealth/AdapterHealthExamination.kt
  app/src/main/java/org/ole/planet/myplanet/ui/myhealth/AddExaminationActivity.kt
  app/src/main/java/org/ole/planet/myplanet/ui/myhealth/MyHealthFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/myhealth/UserListArrayAdapter.kt
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-ne/strings.xml
  app/src/main/res/values-so/strings.xml
  app/src/main/res/values/strings.xml
Labels: ready to merge

#3860 community: smoother news texts (fixes #3859)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/news/AdapterNews.kt
  app/src/main/java/org/ole/planet/myplanet/ui/news/ExpandableListAdapter.kt
  app/src/main/java/org/ole/planet/myplanet/ui/news/NewsFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/news/ReplyActivity.kt
Labels: ready to merge

#3862 resources: smoother texts (fixes #3861)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/onBoarding/OnBoardingActivity.kt
  app/src/main/java/org/ole/planet/myplanet/ui/resources/AdapterResource.kt
  app/src/main/java/org/ole/planet/myplanet/ui/resources/AddResourceActivity.kt
  app/src/main/java/org/ole/planet/myplanet/ui/resources/AddResourceFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/resources/CollectionsFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/resources/ResourceDetailFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/resources/ResourcesFragment.kt
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-ne/strings.xml
  app/src/main/res/values-so/strings.xml
  app/src/main/res/values/strings.xml
Labels: ready to merge

#3801 courses: last visited step (fixes #3800)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/courses/TakeCourseFragment.kt
Labels: ready to merge

#3865 surveys: overview on completion (fixes #3833)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/exam/BaseExamFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/exam/UserInformationFragment.kt
Labels: ready to merge

#3866 sync: smoother texts (fixes #3864)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/dashboard/AboutFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/submission/AdapterMySubmission.kt
  app/src/main/java/org/ole/planet/myplanet/ui/survey/SurveyFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/sync/DashboardElementActivity.kt
  app/src/main/java/org/ole/planet/myplanet/ui/sync/LoginActivity.kt
  app/src/main/java/org/ole/planet/myplanet/ui/sync/ProcessUserDataActivity.kt
  app/src/main/java/org/ole/planet/myplanet/ui/sync/SyncActivity.kt
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-ne/strings.xml
  app/src/main/res/values-so/strings.xml
  app/src/main/res/values/strings.xml
Labels: ready to merge

#3870 teams: smoother texts (fixes #3869)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/team/AdapterTeamList.kt
  app/src/main/java/org/ole/planet/myplanet/ui/team/BaseTeamFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/team/PlanFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/team/TeamDetailFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/team/TeamPagerAdapter.kt
  app/src/main/java/org/ole/planet/myplanet/ui/team/teamCourse/TeamCourseFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/team/teamDiscussion/DiscussionListFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/team/teamMember/AdapterJoinedMember.kt
  app/src/main/java/org/ole/planet/myplanet/ui/team/teamMember/JoinedMemberFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/team/teamMember/MemberDetailFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/team/teamResource/AdapterTeamResource.kt
  app/src/main/java/org/ole/planet/myplanet/ui/team/teamResource/TeamResourceFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/team/teamTask/AdapterTask.kt
  app/src/main/java/org/ole/planet/myplanet/ui/team/teamTask/TeamTaskFragment.kt
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-ne/strings.xml
  app/src/main/res/values-so/strings.xml
  app/src/main/res/values/strings.xml
Labels: ready to merge

#3872 teams: smoother messages (fixes #3871)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/team/teamDiscussion/DiscussionListFragment.kt
Labels: ready to merge

#3874 courses: stabler filter (fixes #3858)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/courses/CoursesFragment.kt
Labels: ready to merge

#3885 login: save by learners username (fixes #3882)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/sync/LoginActivity.kt
Labels: ready to merge

#3878 courses: ratings only by learners (fixes #3876)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/base/BaseContainerFragment.kt
  app/src/main/java/org/ole/planet/myplanet/base/BaseContainerFragment.kt.lite
  app/src/main/java/org/ole/planet/myplanet/ui/courses/AdapterCourses.kt
Labels: ready to merge

#3880 learner: smoother profile texts (fixes #3879)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/userprofile/AchievementFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/userprofile/BecomeMemberActivity.kt
  app/src/main/java/org/ole/planet/myplanet/ui/userprofile/EditAchievementFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/userprofile/TeamListAdapter.kt
  app/src/main/java/org/ole/planet/myplanet/ui/userprofile/UserDetailFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/userprofile/UserProfileFragment.kt
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-ne/strings.xml
  app/src/main/res/values-so/strings.xml
  app/src/main/res/values/strings.xml
Labels: ready to merge

#3899 sync: smoother serialization (fixes #3886)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/sync/SyncActivity.kt
  build.gradle
Labels: review, WIP, priority, peer review

#3905 mycourses: cleaner archive button (fixes #3888)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/courses/CoursesFragment.kt
  app/src/main/res/layout/fragment_my_course.xml
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-ne/strings.xml
  app/src/main/res/values-so/strings.xml
  app/src/main/res/values/strings.xml
Labels: ready to merge

#3917 all: better non-activity context handling (fixes #3915)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/MainApplication.kt
Labels: ready to merge

#3919 teams: show name and type (fixes #3918)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/team/TeamDetailFragment.kt
Labels: ready to merge

#3947 all: less utilities warnings is more (fixes #3944)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/MainApplication.kt
  app/src/main/java/org/ole/planet/myplanet/datamanager/ManagerSync.kt
  app/src/main/java/org/ole/planet/myplanet/ui/dashboard/BaseDashboardFragmentPlugin.kt
  app/src/main/java/org/ole/planet/myplanet/ui/enterprises/AdapterReports.kt
  app/src/main/java/org/ole/planet/myplanet/ui/enterprises/ReportsFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/news/AdapterNews.kt
  app/src/main/java/org/ole/planet/myplanet/ui/onBoarding/OnBoardingActivity.kt
  app/src/main/java/org/ole/planet/myplanet/ui/sync/LoginActivity.kt
  app/src/main/java/org/ole/planet/myplanet/ui/sync/SyncActivity.kt
  app/src/main/java/org/ole/planet/myplanet/ui/team/AdapterTeamList.kt
  app/src/main/java/org/ole/planet/myplanet/ui/viewer/PDFReaderActivity.kt
  app/src/main/java/org/ole/planet/myplanet/utilities/AndroidDecrypter.kt
  app/src/main/java/org/ole/planet/myplanet/utilities/AuthSessionUpdater.kt
  app/src/main/java/org/ole/planet/myplanet/utilities/CheckboxListView.kt
  app/src/main/java/org/ole/planet/myplanet/utilities/Constants.kt
  app/src/main/java/org/ole/planet/myplanet/utilities/DialogUtils.kt
  app/src/main/java/org/ole/planet/myplanet/utilities/DownloadUtils.kt
  app/src/main/java/org/ole/planet/myplanet/utilities/FileUtils.kt
  app/src/main/java/org/ole/planet/myplanet/utilities/JsonUtils.kt
  app/src/main/java/org/ole/planet/myplanet/utilities/NetworkUtils.kt
  app/src/main/java/org/ole/planet/myplanet/utilities/NotificationUtil.kt
  app/src/main/java/org/ole/planet/myplanet/utilities/SharedPrefManager.kt
  app/src/main/java/org/ole/planet/myplanet/utilities/TimeUtils.kt
  app/src/main/java/org/ole/planet/myplanet/utilities/Utilities.kt
  app/src/main/java/org/ole/planet/myplanet/views/RoundedListPreference.kt
Labels: ready to merge

#3850 sync: generate data `csv`es (fixes #3853)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/model/RealmAchievement.kt
  app/src/main/java/org/ole/planet/myplanet/model/RealmCertification.kt
  app/src/main/java/org/ole/planet/myplanet/model/RealmChatHistory.kt
  app/src/main/java/org/ole/planet/myplanet/model/RealmCourseProgress.kt
  app/src/main/java/org/ole/planet/myplanet/model/RealmFeedback.kt
  app/src/main/java/org/ole/planet/myplanet/model/RealmMeetup.kt
  app/src/main/java/org/ole/planet/myplanet/model/RealmMyCourse.kt
  app/src/main/java/org/ole/planet/myplanet/model/RealmMyHealthPojo.kt
  app/src/main/java/org/ole/planet/myplanet/model/RealmMyLibrary.kt
  app/src/main/java/org/ole/planet/myplanet/model/RealmMyTeam.kt
  app/src/main/java/org/ole/planet/myplanet/model/RealmNews.kt
  app/src/main/java/org/ole/planet/myplanet/model/RealmOfflineActivity.kt
  app/src/main/java/org/ole/planet/myplanet/model/RealmRating.kt
  app/src/main/java/org/ole/planet/myplanet/model/RealmStepExam.kt
  app/src/main/java/org/ole/planet/myplanet/model/RealmSubmission.kt
  app/src/main/java/org/ole/planet/myplanet/model/RealmTag.kt
  app/src/main/java/org/ole/planet/myplanet/model/RealmTeamLog.kt
  app/src/main/java/org/ole/planet/myplanet/model/RealmTeamTask.kt
  app/src/main/java/org/ole/planet/myplanet/model/RealmUserModel.kt
  app/src/main/java/org/ole/planet/myplanet/service/TransactionSyncManager.kt
  app/src/main/java/org/ole/planet/myplanet/ui/SettingActivity.kt
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-ne/strings.xml
  app/src/main/res/values-so/strings.xml
  app/src/main/res/values/strings.xml
Labels: review, priority, ready to merge, peer review

#3954 resources: smoother video play management (fixes #3951)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/viewer/VideoPlayerActivity.kt
Labels: bug, priority

#3927 teams: smoother strings (fixes #3926)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/team/TeamPagerAdapter.kt
Labels: ready to merge

#3960 all: less base warnings is more (fixes #3958)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/base/BaseActivity.kt
  app/src/main/java/org/ole/planet/myplanet/base/BaseContainerFragment.kt
  app/src/main/java/org/ole/planet/myplanet/base/BaseContainerFragment.kt.lite
  app/src/main/java/org/ole/planet/myplanet/base/BaseMemberFragment.kt
  app/src/main/java/org/ole/planet/myplanet/base/BaseNewsFragment.kt
  app/src/main/java/org/ole/planet/myplanet/base/BaseRecyclerFragment.kt
  app/src/main/java/org/ole/planet/myplanet/base/BaseResourceFragment.kt
Labels: ready to merge

#3962 all: less callback warnings is more (fixes #3961)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/callback/OnHomeItemClickListener.kt
  app/src/main/java/org/ole/planet/myplanet/callback/OnMyLifeItemSelected.kt
  app/src/main/java/org/ole/planet/myplanet/callback/ProgressBroadcastReceiver.kt
  app/src/main/java/org/ole/planet/myplanet/callback/UploadAttachmentListener.kt
Labels: ready to merge

#3964 chat: continue shared conversations (fixes #3963)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/chat/ChatAdapter.kt
  app/src/main/java/org/ole/planet/myplanet/ui/chat/ChatDetailFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/community/CommunityFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/community/ServicesFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/enterprises/EnterpriseCalendarFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/enterprises/FinanceFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/enterprises/ReportsFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/news/AdapterNews.kt
  app/src/main/java/org/ole/planet/myplanet/ui/news/NewsFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/news/ReplyActivity.kt
  app/src/main/java/org/ole/planet/myplanet/ui/team/MyTeamsDetailFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/team/PlanFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/team/TeamDetailFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/team/teamCourse/TeamCourseFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/team/teamDiscussion/DiscussionListFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/team/teamMember/JoinedMemberFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/team/teamMember/MembersFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/team/teamResource/TeamResourceFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/team/teamTask/TeamTaskFragment.kt
Labels: ready to merge

#3971 actions: smoother test build (fixes 3972)
  .github/workflows/android-build.yml
  app/build.gradle
  build.gradle
Labels: ready to merge

#3943 teams: smoother permissions (fixes #3889)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/base/BaseNewsFragment.kt
  app/src/main/java/org/ole/planet/myplanet/model/RealmMyTeam.kt
  app/src/main/java/org/ole/planet/myplanet/ui/community/CommunityFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/enterprises/AdapterReports.kt
  app/src/main/java/org/ole/planet/myplanet/ui/enterprises/EnterpriseCalendarFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/enterprises/ReportsFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/news/AdapterNews.kt
  app/src/main/java/org/ole/planet/myplanet/ui/news/ReplyActivity.kt
  app/src/main/java/org/ole/planet/myplanet/ui/team/AdapterTeamList.kt
  app/src/main/java/org/ole/planet/myplanet/ui/team/BaseTeamFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/team/teamDiscussion/DiscussionListFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/team/teamResource/TeamResourceFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/team/teamTask/AdapterTask.kt
  app/src/main/java/org/ole/planet/myplanet/ui/team/teamTask/TeamTaskFragment.kt
Labels: ready to merge

#3952 settings: smoother languages in toolbar (fixes #3935)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/SettingActivity.kt
  app/src/main/res/values/styles.xml
Labels: ready to merge

#3973 all: less datamanager warnings is more (fixes #3970)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/datamanager/ApiClient.kt
  app/src/main/java/org/ole/planet/myplanet/datamanager/FileUploadService.kt
  app/src/main/java/org/ole/planet/myplanet/datamanager/ManagerSync.kt
  app/src/main/java/org/ole/planet/myplanet/datamanager/MyDownloadService.kt
  app/src/main/java/org/ole/planet/myplanet/datamanager/Service.kt
Labels: ready to merge

#3975 all: less model warnings is more (fixes #3974)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/model/ChatRequestModel.kt
  app/src/main/java/org/ole/planet/myplanet/model/ChatViewModel.kt
  app/src/main/java/org/ole/planet/myplanet/model/DocumentResponse.kt
  app/src/main/java/org/ole/planet/myplanet/model/MyPlanet.kt
  app/src/main/java/org/ole/planet/myplanet/model/RealmAchievement.kt
  app/src/main/java/org/ole/planet/myplanet/model/RealmAnswer.kt
  app/src/main/java/org/ole/planet/myplanet/model/RealmApkLog.kt
  app/src/main/java/org/ole/planet/myplanet/model/RealmCertification.kt
  app/src/main/java/org/ole/planet/myplanet/model/RealmCourseActivity.kt
  app/src/main/java/org/ole/planet/myplanet/model/RealmCourseProgress.kt
  app/src/main/java/org/ole/planet/myplanet/model/RealmDictionary.kt
  app/src/main/java/org/ole/planet/myplanet/model/RealmExamQuestion.kt
  app/src/main/java/org/ole/planet/myplanet/model/RealmFeedback.kt
  app/src/main/java/org/ole/planet/myplanet/model/RealmMeetup.kt
  app/src/main/java/org/ole/planet/myplanet/model/RealmMyCourse.kt
  app/src/main/java/org/ole/planet/myplanet/model/RealmMyHealthPojo.kt
  app/src/main/java/org/ole/planet/myplanet/model/RealmMyLibrary.kt
  app/src/main/java/org/ole/planet/myplanet/model/RealmMyLife.kt
  app/src/main/java/org/ole/planet/myplanet/model/RealmMyTeam.kt
  app/src/main/java/org/ole/planet/myplanet/model/RealmNews.kt
  app/src/main/java/org/ole/planet/myplanet/model/RealmOfflineActivity.kt
  app/src/main/java/org/ole/planet/myplanet/model/RealmRating.kt
  app/src/main/java/org/ole/planet/myplanet/model/RealmRemovedLog.kt
  app/src/main/java/org/ole/planet/myplanet/model/RealmResourceActivity.kt
  app/src/main/java/org/ole/planet/myplanet/model/RealmSearchActivity.kt
  app/src/main/java/org/ole/planet/myplanet/model/RealmStepExam.kt
  app/src/main/java/org/ole/planet/myplanet/model/RealmSubmission.kt
  app/src/main/java/org/ole/planet/myplanet/model/RealmTag.kt
  app/src/main/java/org/ole/planet/myplanet/model/RealmTeamLog.kt
  app/src/main/java/org/ole/planet/myplanet/model/RealmTeamTask.kt
  app/src/main/java/org/ole/planet/myplanet/model/RealmUserModel.kt
  app/src/main/java/org/ole/planet/myplanet/model/SourceFile.kt
  app/src/main/java/org/ole/planet/myplanet/ui/chat/ChatDetailFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/chat/ChatHistoryListFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/courses/AdapterCourses.kt
  app/src/main/java/org/ole/planet/myplanet/ui/dictionary/DictionaryActivity.kt
  app/src/main/java/org/ole/planet/myplanet/ui/sync/SyncActivity.kt
  app/src/main/java/org/ole/planet/myplanet/ui/userprofile/AchievementFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/userprofile/EditAchievementFragment.kt
Labels: ready to merge
