Repository open-learning-exchange/myplanet, pull requests merged in 2024-02, with the labels that each got.

#3043 actions: refactor `submission` ui dir to kotlin (fixes #3038)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/submission/AdapterMySubmission.java
  app/src/main/java/org/ole/planet/myplanet/ui/submission/AdapterMySubmission.kt
  app/src/main/java/org/ole/planet/myplanet/ui/submission/MySubmissionFragment.java
  app/src/main/java/org/ole/planet/myplanet/ui/submission/MySubmissionFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/submission/SubmissionDetailFragment.java
  app/src/main/java/org/ole/planet/myplanet/ui/submission/SubmissionDetailFragment.kt
Labels: peer review

#3088 team: refresh join request on change (fixes #3087)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/team/teamMember/AdapterMemberRequest.kt
  app/src/main/java/org/ole/planet/myplanet/ui/team/teamMember/MembersFragment.kt
Labels: peer review

#3008 actions: refactor `WebViewActivity` viewer to kotlin (fixes #3001)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/viewer/WebViewActivity.java
  app/src/main/java/org/ole/planet/myplanet/ui/viewer/WebViewActivity.kt
Labels: peer review

#3085 actions: less warnings is more (fixes #3084)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/model/RealmUserModel.kt
  app/src/main/java/org/ole/planet/myplanet/ui/chat/ChatAdapter.kt
  app/src/main/java/org/ole/planet/myplanet/ui/chat/ChatHistoryListFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/community/CommunityFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/community/CommunityPagerAdapter.kt
  app/src/main/java/org/ole/planet/myplanet/ui/community/CommunityTabFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/community/HomeCommunityDialogFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/community/LeadersFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/community/ServicesFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/course/AdapterCourses.kt
  app/src/main/java/org/ole/planet/myplanet/ui/course/AdapterMyProgress.kt
  app/src/main/java/org/ole/planet/myplanet/ui/course/AdapterProgressGrid.kt
  app/src/main/java/org/ole/planet/myplanet/ui/course/CourseFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/course/CourseProgressActivity.kt
  app/src/main/java/org/ole/planet/myplanet/ui/course/CourseStepFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/course/MyProgressFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/course/TakeCourseFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/dashboard/AboutFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/dashboard/BaseDashboardFragmentPlugin.kt
  app/src/main/java/org/ole/planet/myplanet/ui/dashboard/BellDashboardFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/dictionary/DictionaryActivity.kt
  app/src/main/java/org/ole/planet/myplanet/ui/enterprises/AdapterFinance.kt
  app/src/main/java/org/ole/planet/myplanet/ui/library/LibraryDetailFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/library/LibraryFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/news/NewsDetailActivity.kt
  app/src/main/java/org/ole/planet/myplanet/ui/team/MyTeamsDetailFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/team/teamDiscussion/DiscussionListFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/userprofile/AchievementFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/userprofile/UserProfileFragment.kt
  app/src/main/java/org/ole/planet/myplanet/utilities/AndroidDecrypter.kt
  app/src/main/java/org/ole/planet/myplanet/utilities/Constants.kt
  app/src/main/java/org/ole/planet/myplanet/utilities/DownloadUtils.kt
  app/src/main/java/org/ole/planet/myplanet/utilities/NetworkUtils.kt
Labels: review

#3090 actions: better `RealmOfflineActivity` (fixes #3089)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/model/RealmOfflineActivity.kt
Labels: peer review

#3047 actions: refactor `VideoPlayerActivity` viewer to kotlin (fixes #3044)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/viewer/VideoPlayerActivity.java
  app/src/main/java/org/ole/planet/myplanet/ui/viewer/VideoPlayerActivity.kt
Labels: peer review

#3048 actions: refactor bulk dir to kotlin (fixes #3045)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/callback/SuccessListener.kt
  app/src/main/java/org/ole/planet/myplanet/ui/calendar/CalendarFragment.java
  app/src/main/java/org/ole/planet/myplanet/ui/calendar/CalendarFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/helpwanted/HelpWantedFragment.java
  app/src/main/java/org/ole/planet/myplanet/ui/helpwanted/HelpWantedFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/map/OfflineMapActivity.java
  app/src/main/java/org/ole/planet/myplanet/ui/map/OfflineMapActivity.kt
  app/src/main/java/org/ole/planet/myplanet/ui/myPersonals/AdapterMyPersonal.java
  app/src/main/java/org/ole/planet/myplanet/ui/myPersonals/AdapterMyPersonal.kt
  app/src/main/java/org/ole/planet/myplanet/ui/myPersonals/MyPersonalsFragment.java
  app/src/main/java/org/ole/planet/myplanet/ui/myPersonals/MyPersonalsFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/mymeetup/MyMeetUpsFragment.java
  app/src/main/java/org/ole/planet/myplanet/ui/mymeetup/MyMeetUpsFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/mymeetup/MyMeetupDetailFragment.java
  app/src/main/java/org/ole/planet/myplanet/ui/mymeetup/MyMeetupDetailFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/rating/RatingFragment.java
  app/src/main/java/org/ole/planet/myplanet/ui/rating/RatingFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/references/ReferenceFragment.java
  app/src/main/java/org/ole/planet/myplanet/ui/references/ReferenceFragment.kt
Labels: peer review

#3092 login: show only device using members (fixes #3091)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/sync/LoginActivity.kt
  app/src/main/java/org/ole/planet/myplanet/ui/sync/SyncActivity.java
Labels: peer review

#3003 actions: better json for realm models (fixes #2997)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/model/RealmFeedback.kt
  app/src/main/java/org/ole/planet/myplanet/model/RealmMyLibrary.kt
  app/src/main/java/org/ole/planet/myplanet/model/RealmSubmission.kt
  app/src/main/java/org/ole/planet/myplanet/model/RealmUserModel.kt
Labels: peer review

#3042 actions: refactor `survey` ui dir to kotlin (fixes #3037)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/survey/AdapterSurvey.java
  app/src/main/java/org/ole/planet/myplanet/ui/survey/AdapterSurvey.kt
  app/src/main/java/org/ole/planet/myplanet/ui/survey/SendSurveyFragment.java
  app/src/main/java/org/ole/planet/myplanet/ui/survey/SendSurveyFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/survey/SurveyFragment.java
  app/src/main/java/org/ole/planet/myplanet/ui/survey/SurveyFragment.kt
Labels: peer review

#3096 actions: refactor `myLife` ui dir to kotlin (fixes #3095)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/mylife/AdapterMyLife.java
  app/src/main/java/org/ole/planet/myplanet/ui/mylife/AdapterMyLife.kt
  app/src/main/java/org/ole/planet/myplanet/ui/mylife/LifeFragment.java
  app/src/main/java/org/ole/planet/myplanet/ui/mylife/LifeFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/mylife/helper/ItemTouchHelperAdapter.java
  app/src/main/java/org/ole/planet/myplanet/ui/mylife/helper/ItemTouchHelperAdapter.kt
  app/src/main/java/org/ole/planet/myplanet/ui/mylife/helper/ItemTouchHelperViewHolder.java
  app/src/main/java/org/ole/planet/myplanet/ui/mylife/helper/ItemTouchHelperViewHolder.kt
  app/src/main/java/org/ole/planet/myplanet/ui/mylife/helper/OnStartDragListener.java
  app/src/main/java/org/ole/planet/myplanet/ui/mylife/helper/OnStartDragListener.kt
  app/src/main/java/org/ole/planet/myplanet/ui/mylife/helper/SimpleItemTouchHelperCallback.java
  app/src/main/java/org/ole/planet/myplanet/ui/mylife/helper/SimpleItemTouchHelperCallback.kt
Labels: review

#3100 login: init check during sync (fixes #3099)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/sync/SyncActivity.kt
Labels: peer review

#3107 teams: more join stability (fixes #3106)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/team/AdapterTeamList.kt
Labels: ready to merge, peer review

#3105 teams: show valid ones only (fixes #3104)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/team/AdapterTeamList.kt
  app/src/main/java/org/ole/planet/myplanet/ui/team/TeamFragment.kt
Labels: peer review

#3118 teams: more responsive (fixes #3117)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/team/teamMember/JoinedMemberFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/team/teamMember/MembersFragment.kt
  app/src/main/res/layout/row_member_request.xml
Labels: peer review

#3126 actions: refactor `Utilities` dir to kotlin (fixes #3125)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/base/BaseContainerFragment.kt
  app/src/main/java/org/ole/planet/myplanet/base/BaseContainerFragment.kt.lite
  app/src/main/java/org/ole/planet/myplanet/base/BaseResourceFragment.kt
  app/src/main/java/org/ole/planet/myplanet/base/PermissionActivity.kt.lite
  app/src/main/java/org/ole/planet/myplanet/datamanager/FileUploadService.kt
  app/src/main/java/org/ole/planet/myplanet/datamanager/ManagerSync.kt
  app/src/main/java/org/ole/planet/myplanet/datamanager/MyDownloadService.kt
  app/src/main/java/org/ole/planet/myplanet/datamanager/Service.kt
  app/src/main/java/org/ole/planet/myplanet/model/RealmNews.kt
  app/src/main/java/org/ole/planet/myplanet/model/RealmSubmission.kt
  app/src/main/java/org/ole/planet/myplanet/model/RealmUserModel.kt
  app/src/main/java/org/ole/planet/myplanet/service/AutoSyncWorker.kt
  app/src/main/java/org/ole/planet/myplanet/service/SyncManager.kt
  app/src/main/java/org/ole/planet/myplanet/service/TransactionSyncManager.kt
  app/src/main/java/org/ole/planet/myplanet/service/UploadManager.kt
  app/src/main/java/org/ole/planet/myplanet/service/UploadToShelfService.kt
  app/src/main/java/org/ole/planet/myplanet/ui/chat/ChatDetailFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/course/AdapterCourses.kt
  app/src/main/java/org/ole/planet/myplanet/ui/dashboard/BaseDashboardFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/library/AdapterLibrary.kt
  app/src/main/java/org/ole/planet/myplanet/ui/myPersonals/MyPersonalsFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/myhealth/MyHealthFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/news/AdapterNews.kt
  app/src/main/java/org/ole/planet/myplanet/ui/news/NewsFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/sync/DashboardElementActivity.kt
  app/src/main/java/org/ole/planet/myplanet/ui/sync/SyncActivity.kt
  app/src/main/java/org/ole/planet/myplanet/ui/team/PlanFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/team/teamMember/AdapterJoinedMember.kt
  app/src/main/java/org/ole/planet/myplanet/ui/userprofile/UserProfileFragment.kt
  app/src/main/java/org/ole/planet/myplanet/utilities/DialogUtils.kt
  app/src/main/java/org/ole/planet/myplanet/utilities/FileUtils.kt
  app/src/main/java/org/ole/planet/myplanet/utilities/LocaleHelper.java
  app/src/main/java/org/ole/planet/myplanet/utilities/LocaleHelper.kt
  app/src/main/java/org/ole/planet/myplanet/utilities/Utilities.java
  app/src/main/java/org/ole/planet/myplanet/utilities/Utilities.kt
Labels: peer review

#3119 team: responsive voices (fixes #3109)
  app/build.gradle
  app/src/main/res/layout/row_news.xml
Labels: peer review

#3130 team: check fragment state (fixes #3121)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/team/teamTask/TeamTaskFragment.kt
Labels: peer review

#3135 actions: refactor `exams` dir to kotlin (fixes #3116)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/model/RealmAnswer.kt
  app/src/main/java/org/ole/planet/myplanet/ui/exam/BaseExamFragment.java
  app/src/main/java/org/ole/planet/myplanet/ui/exam/BaseExamFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/exam/TakeExamFragment.java
  app/src/main/java/org/ole/planet/myplanet/ui/exam/TakeExamFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/exam/UserInformationFragment.java
  app/src/main/java/org/ole/planet/myplanet/ui/exam/UserInformationFragment.kt
Labels: ready to merge, peer review

#3149 resources: more stability when viewing (fixes #3147)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/utilities/Utilities.kt
Labels: review

#3131 sync: better null checks (fixes #3124)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/service/TransactionSyncManager.kt
Labels: review

#3139 courses: more stability in progress (fixes #3138)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/course/AdapterMyProgress.kt
Labels: review

#3140 resources: check exoplayer init before stop (fixes #3133)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/viewer/VideoPlayerActivity.kt
Labels: review

#3144 team: refresh task on submit (fixes #3143)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/team/teamTask/TeamTaskFragment.kt
Labels: peer review

#3153 team: more news stability (fixes #3148)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/news/AdapterNews.kt
Labels: review

#3152 courses: less warnings is more (fixes #3150)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/base/BaseContainerFragment.kt
  app/src/main/java/org/ole/planet/myplanet/base/BaseContainerFragment.kt.lite
  app/src/main/java/org/ole/planet/myplanet/base/BaseResourceFragment.kt
  app/src/main/java/org/ole/planet/myplanet/callback/OnCourseItemSelected.kt
  app/src/main/java/org/ole/planet/myplanet/callback/OnLibraryItemSelected.kt
  app/src/main/java/org/ole/planet/myplanet/callback/TagClickListener.kt
  app/src/main/java/org/ole/planet/myplanet/ui/course/AdapterCourses.kt
  app/src/main/java/org/ole/planet/myplanet/ui/course/CourseDetailFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/course/CourseFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/course/CourseStepFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/dashboard/BaseDashboardFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/library/AdapterLibrary.kt
  app/src/main/java/org/ole/planet/myplanet/ui/library/CollectionsFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/library/LibraryFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/library/TagExpandableAdapter.kt
  app/src/main/java/org/ole/planet/myplanet/utilities/Utilities.kt
Labels: peer review

#3146 team: better list of members (fixes #3145)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/team/teamTask/TeamTaskFragment.kt
Labels: peer review

#3137 survey: allow partial completion (fixes #3136)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/dashboard/BellDashboardFragment.kt
Labels: review

#3132 survey: more stability (fixes #3120)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/survey/SurveyFragment.kt
Labels: review

#3156 resources: download once (fixes #3155)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/base/BaseContainerFragment.kt
  app/src/main/java/org/ole/planet/myplanet/datamanager/MyDownloadService.kt
Labels: review

#3159 news: more stability (fixes #3154)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/news/AdapterNews.kt
Labels: review

#3161 sync: more stable download (fixes #3160)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/datamanager/MyDownloadService.kt
  app/src/main/java/org/ole/planet/myplanet/utilities/NotificationUtil.kt
Labels: review

#3166 enterprise: adding reports (fixes #3165)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/model/RealmMyTeam.kt
  app/src/main/java/org/ole/planet/myplanet/service/UploadManager.kt
  app/src/main/java/org/ole/planet/myplanet/ui/enterprises/AdapterReports.kt
  app/src/main/java/org/ole/planet/myplanet/ui/enterprises/ReportsFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/team/TeamPagerAdapter.kt
  app/src/main/res/layout/dialog_add_report.xml
  app/src/main/res/layout/fragment_reports.xml
  app/src/main/res/layout/report_list_item.xml
Labels: peer review

#3176 team: smoother sync (fixes #3175)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/model/RealmMyTeam.kt
  app/src/main/java/org/ole/planet/myplanet/ui/team/TeamFragment.kt
Labels: peer review
