Repository open-learning-exchange/myplanet, pull requests merged in 2025-01, with the labels that each got.

#4938 dashboard: smoother dark mode (fixes #4937)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/dashboard/BaseDashboardFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/dashboard/BaseDashboardFragmentPlugin.kt
  app/src/main/res/drawable/ic_more.xml
  app/src/main/res/drawable/light_rect.xml
  app/src/main/res/layout/item_home_my_team.xml
  app/src/main/res/layout/item_library_home.xml
  app/src/main/res/layout/item_my_life.xml
  app/src/main/res/values-night/colors.xml
Labels: ready to merge

#4921 teams: smoother message dialog (fixes #4920)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/news/AdapterNews.kt
  app/src/main/java/org/ole/planet/myplanet/ui/team/MyTeamsDetailFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/team/teamDiscussion/DiscussionListFragment.kt
  app/src/main/res/layout/alert_input.xml
Labels: ready to merge

#4922 sync: smoother download error handling (fixes #4919)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/base/BaseResourceFragment.kt
  app/src/main/java/org/ole/planet/myplanet/datamanager/MyDownloadService.kt
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-ne/strings.xml
  app/src/main/res/values-so/strings.xml
  app/src/main/res/values/strings.xml
Labels: ready to merge

#4936 teams: smoother finances button color (fixes #4934)
  app/build.gradle
  app/src/main/res/layout/fragment_finance.xml
Labels: ready to merge

#4940 dashboard: smoother profile edit (fixes #4939)
  app/build.gradle
  app/src/main/res/layout/edit_profile_dialog.xml
Labels: ready to merge

#4956 all: smoother notification dark mode (fixes #4954)
  app/build.gradle
  app/src/main/res/layout/app_bar_bell.xml
  app/src/main/res/layout/fragment_notifications.xml
  app/src/main/res/layout/row_notifications.xml
Labels: ready to merge

#4967 all: smoother navigation icons (fixes #4966)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardActivity.kt
  app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardActivity.kt.lite
Labels: ready to merge

#4969 all: smoother navigation community icon (fixes #4968)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardActivity.kt
  app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardActivity.kt.lite
Labels: ready to merge

#4976 enterprises: smoother reports button (fixes #4972)
  app/build.gradle
  app/src/main/res/layout/fragment_reports.xml
Labels: ready to merge

#4984 courses: smoother resources button (fixes #4971)
  app/build.gradle
  app/src/main/res/layout/fragment_course_detail.xml
  app/src/main/res/values/styles.xml
Labels: ready to merge

#4965 sync: cloud community (fixes #4964)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/datamanager/Service.kt
  app/src/main/java/org/ole/planet/myplanet/service/TransactionSyncManager.kt
  app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardActivity.kt
  app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardActivity.kt.lite
  app/src/main/java/org/ole/planet/myplanet/ui/sync/DashboardElementActivity.kt
  app/src/main/java/org/ole/planet/myplanet/ui/sync/ProcessUserDataActivity.kt
  app/src/main/java/org/ole/planet/myplanet/ui/sync/SyncActivity.kt
  app/src/main/java/org/ole/planet/myplanet/utilities/ServerUrlMapper.kt
  app/src/main/java/org/ole/planet/myplanet/utilities/Utilities.kt
  gradle.properties
Labels: priority, ready to merge

#4985 all: smoother navigation libraries icons (fixes #4975)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardActivity.kt
  app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardActivity.kt.lite
Labels: ready to merge

#4987 teams: smoother member views (fixes #4973)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/team/teamMember/AdapterJoinedMember.kt
  app/src/main/java/org/ole/planet/myplanet/ui/team/teamMember/MemberDetailFragment.kt
Labels: ready to merge

#4988 teams: smoother message button (fixes #4974)
  app/build.gradle
  app/src/main/res/layout/fragment_discussion_list.xml
Labels: ready to merge

#4962 all: smoother notifications view (fixes #4955)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/dashboard/notification/AdapterNotification.kt
  app/src/main/java/org/ole/planet/myplanet/ui/dashboard/notification/NotificationsFragment.kt
Labels: ready to merge

#5002 mylife: smoother myhealth calender icon (fixes #4998)
  app/build.gradle
  app/src/main/res/layout/activity_add_my_health.xml
Labels: ready to merge

#5014 resources: smoother downloads (fixes #5012)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/datamanager/MyDownloadService.kt
Labels: ready to merge

#5015 courses: smoother joining (fixes #5013)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/model/RealmCourseActivity.kt
  app/src/main/java/org/ole/planet/myplanet/ui/courses/TakeCourseFragment.kt
Labels: ready to merge

#5003 all: smoother notifications tasks (fixes 4963)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/dashboard/notification/AdapterNotification.kt
Labels: ready to merge

#4926 courses: smoother mycourses toolbar (fixes #4925)
  app/build.gradle
  app/src/main/res/layout/fragment_my_course.xml
Labels: ready to merge

#4982 surveys: smoother list buttons (fixes #4970)
  app/build.gradle
  app/src/main/res/values-night/styles.xml
  app/src/main/res/values/styles.xml
Labels: peer review

#5011 community: smoother reports (fixes #5008)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/datamanager/Service.kt
  app/src/main/java/org/ole/planet/myplanet/model/RealmUserModel.kt
  app/src/main/java/org/ole/planet/myplanet/ui/community/CommunityPagerAdapter.kt
  app/src/main/java/org/ole/planet/myplanet/ui/team/BaseTeamFragment.kt
Labels: peer review

#5025 mylife: display myhealth records (fixes #5024)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/MainApplication.kt
  app/src/main/java/org/ole/planet/myplanet/service/TransactionSyncManager.kt
  app/src/main/java/org/ole/planet/myplanet/ui/dashboard/BellDashboardFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/myhealth/AdapterHealthExamination.kt
  app/src/main/java/org/ole/planet/myplanet/ui/myhealth/MyHealthFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/userprofile/UserProfileFragment.kt
  app/src/main/java/org/ole/planet/myplanet/utilities/Utilities.kt
Labels: ready to merge

#5018 all: smoother disclaimer link (fixes #5017)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DisclaimerFragment.kt
  app/src/main/res/layout/fragment_disclaimer.xml
Labels: ready to merge

#5027 mylife: smoother mypersonals editing (fixes #5026)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/myPersonals/AdapterMyPersonal.kt
Labels: ready to merge

#5035 teams: smoother finances default (fixes #5007)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/enterprises/FinanceFragment.kt
  app/src/main/res/layout/fragment_finance.xml
Labels: ready to merge

#5021 courses: smoother mycourses select all (fixes #4986)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/courses/AdapterCourses.kt
  app/src/main/java/org/ole/planet/myplanet/ui/courses/CoursesFragment.kt
  app/src/main/res/layout/fragment_my_course.xml
Labels: ready to merge

#5022 mylife: smoother mysubmissions dark mode (fixes #4989)
  app/build.gradle
  app/src/main/res/color/toggle_text_color.xml
  app/src/main/res/drawable/bg_submission_toggle_button.xml
  app/src/main/res/drawable/submission_toggle.xml
  app/src/main/res/layout/fragment_my_submission.xml
Labels: ready to merge

#5040 login: smoother team dark mode (fixes #5039)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/sync/LoginActivity.kt
Labels: ready to merge, peer review

#4884 teams: new surveys added (fixes #5029)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/base/BaseDialogFragment.kt
  app/src/main/java/org/ole/planet/myplanet/base/BaseResourceFragment.kt
  app/src/main/java/org/ole/planet/myplanet/model/RealmStepExam.kt
  app/src/main/java/org/ole/planet/myplanet/ui/courses/CourseStepFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/dashboard/BaseDashboardFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/dashboard/BellDashboardFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/dashboard/notification/NotificationsFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/exam/BaseExamFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/exam/UserInformationFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/submission/AdapterMySubmission.kt
  app/src/main/java/org/ole/planet/myplanet/ui/survey/AdapterSurvey.kt
  app/src/main/java/org/ole/planet/myplanet/ui/survey/SurveyFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/team/TeamPagerAdapter.kt
Labels: priority, ready to merge, peer review

#5016 community: smoother services info (fixes #5006)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/community/ServicesFragment.kt
  app/src/main/res/layout/button_single.xml
  app/src/main/res/layout/fragment_services.xml
Labels: peer review

#5043 courses: smoother filter dark mode (fixes #5041)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/courses/CoursesFragment.kt
Labels: peer review

#5044 courses: smoother submissions headings (fixes #5033)
  app/build.gradle
  app/src/main/res/layout/fragment_my_submission.xml
Labels: peer review

#5052 sync: smoother myhealth dialog dark mode (fixes #5048)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/dashboard/BellDashboardFragment.kt
Labels: peer review

#4997 mylife: smoother myhealth switch dark mode (fixes #4994)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/myhealth/MyHealthFragment.kt
  app/src/main/res/layout/alert_health_list.xml
Labels: peer review

#4983 sync: smoother json (fixes #4981)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/utilities/JsonUtils.kt
Labels: ready to merge, peer review

#5038 sync: smoother compression and retries (fixes #5037)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/datamanager/ApiClient.kt
  app/src/main/java/org/ole/planet/myplanet/service/SyncManager.kt
Labels: ready to merge

#5064 teams: smoother create dialog (fixes #5063)
  app/build.gradle
  app/src/main/res/layout/alert_create_team.xml
Labels: ready to merge, peer review

#5066 mylife: smoother myhealth background sync (fixes #5065)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/MainApplication.kt
  app/src/main/java/org/ole/planet/myplanet/ui/dashboard/BaseDashboardFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/dashboard/BellDashboardFragment.kt
Labels: ready to merge, peer review

#5053 all: smoother navigation links (fixes #5046)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardActivity.kt
  app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardActivity.kt.lite
  app/src/main/java/org/ole/planet/myplanet/ui/sync/DashboardElementActivity.kt
Labels: ready to merge

#5072 resources: smoother tag text (fixes #5055)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/resources/ResourcesFragment.kt
  app/src/main/res/layout/fragment_my_library.xml
Labels: ready to merge

#5074 teams: smoother search (fixes #5073)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/team/TeamFragment.kt
Labels: ready to merge

#5077 resources: smoother filter dark mode (fixes #5056)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/resources/TagExpandableAdapter.kt
  app/src/main/res/layout/row_adapter_navigation_child.xml
Labels: ready to merge

#5084 mylife: smoother mysubmissions list (fixes #5081)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/base/BaseRecyclerFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/submission/MySubmissionFragment.kt
  app/src/main/res/layout/fragment_my_submission.xml
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-ne/strings.xml
  app/src/main/res/values-so/strings.xml
  app/src/main/res/values/strings.xml
Labels: ready to merge, peer review

#5087 resources: smoother mylibrary search (fixes #5086)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/base/BaseRecyclerFragment.kt
Labels: ready to merge, peer review

#5099 chat: smoother sharing dark mode (fixes #5078)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/chat/ChatHistoryListAdapter.kt
  app/src/main/java/org/ole/planet/myplanet/ui/news/ExpandableListAdapter.kt
  app/src/main/res/layout/chat_share_dialog.xml
Labels: ready to merge

#5102 settings: less is more (fixes #5092)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/sync/LoginActivity.kt
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-ne/strings.xml
  app/src/main/res/values-so/strings.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/pref.xml
Labels: ready to merge

#5112 mylife: smoother myhealth records (fixes #5111)
  app/build.gradle
  app/src/main/res/values/styles.xml
Labels: ready to merge

#5094 sync: smoother planet uriur (fixes #5093)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/sync/SyncActivity.kt
  app/src/main/java/org/ole/planet/myplanet/utilities/ServerUrlMapper.kt
Labels: ready to merge

#5105 courses: smoother exams submissions (fixes #5104)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/exam/TakeExamFragment.kt
Labels: ready to merge, peer review

#5098 sync: less config is more (fixes #5085)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/sync/SyncActivity.kt
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-ne/strings.xml
  app/src/main/res/values-so/strings.xml
  app/src/main/res/values/strings.xml
  gradle.properties
Labels: ready to merge, peer review

#5101 mylife: smoother myhealth update refresh (fixes #5030)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/myhealth/MyHealthFragment.kt
  app/src/main/res/layout/fragment_vital_sign.xml
Labels: ready to merge

#5110 courses: smoother joining (fixes #5109)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/courses/TakeCourseFragment.kt
Labels: ready to merge, peer review

#5116 all: smoother navigation highlight (fixes #5070)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/callback/OnHomeItemClickListener.kt
  app/src/main/java/org/ole/planet/myplanet/ui/dashboard/BellDashboardFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardActivity.kt
  app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardActivity.kt.lite
Labels: ready to merge, peer review

#5128 sync: smoother not found dark mode (fixes #5100)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/base/BaseResourceFragment.kt
Labels: ready to merge

#5129 chat: smoother share note dark mode (fixes #5119)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/chat/ChatHistoryListAdapter.kt
  app/src/main/res/layout/add_note_dialog.xml
Labels: ready to merge

#5130 all: smoother navigation hide (fixes #5122)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardActivity.kt
  app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardActivity.kt.lite
Labels: ready to merge

#5134 dashboard: smoother profile info (fixes #5106)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/exam/UserInformationFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/team/TeamDetailFragment.kt
Labels: peer review

#5036 enterprises: smoother finances filter (fixes #5007)(fixes #5079)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/enterprises/FinanceFragment.kt
  app/src/main/res/layout/fragment_finance.xml
Labels: peer review

#5135 dashboard: smoother survey reminder guest (fixes #5133)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/dashboard/BellDashboardFragment.kt
Labels: peer review

#5137 sync: smoother check server dark mode (fixes #5131)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/sync/ProcessUserDataActivity.kt
Labels: peer review

#5126 mylife: smoother mysubmission (fixes #5091)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/submission/MySubmissionFragment.kt
  app/src/main/res/layout/fragment_my_submission.xml
Labels: ready to merge, peer review

#5136 dashboard: smoother survey reminder cancel (fixes #5132)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/dashboard/BellDashboardFragment.kt
Labels: ready to merge, peer review

#5146 login: smoother registration (fixes #5144)
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/AndroidManifest.xml.lite
Labels: ready to merge, peer review

#5147 teams: smoother voices tags (fixes #5121)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/news/AdapterNews.kt
Labels: ready to merge, peer review

#5149 enterprises: smoother csv export (fixes #5142)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/enterprises/ReportsFragment.kt
Labels: ready to merge, peer review

#5156 login: smoother input (fixes #5155)
  app/build.gradle
  app/src/main/res/layout-large-land/activity_login.xml
  app/src/main/res/layout-night/activity_login.xml
  app/src/main/res/layout-normal-land/activity_login.xml
  app/src/main/res/layout-xlarge-land/activity_login.xml
  app/src/main/res/layout/activity_login.xml
Labels: ready to merge, peer review

#5183 sync: smoother server selection (fixes #5182)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/datamanager/Service.kt
  app/src/main/java/org/ole/planet/myplanet/ui/sync/SyncActivity.kt
Labels: ready to merge

#5148 mylife: smoother references dictionary (fixes #5118)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/dictionary/DictionaryActivity.kt
Labels: ready to merge

#5178 teams: smoother voices toast message (fixes #5168)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/news/AdapterNews.kt
Labels: ready to merge

#5175 resources: smoother search (fixes #5164)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/base/BaseRecyclerFragment.kt
Labels: ready to merge, peer review
