Repository open-learning-exchange/myplanet, pull requests merged in 2025-06, with the labels that each got.

#5960 teams: smoother voices member details (fixes #5945)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/news/AdapterNews.kt
Labels: ready to merge

#5927 teams: smoother list searching (fixes #5925)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/team/TeamFragment.kt
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-ne/strings.xml
  app/src/main/res/values-so/strings.xml
  app/src/main/res/values/strings.xml
Labels: ready to merge

#5948 resources: smoother mylibrary (fixes #5915)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/base/BaseContainerFragment.kt
  app/src/main/java/org/ole/planet/myplanet/base/BaseContainerFragment.kt.lite
  app/src/main/java/org/ole/planet/myplanet/base/BaseResourceFragment.kt
Labels: ready to merge

#5944 teams: smoother voices sorting (fixes #5885)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/news/AdapterNews.kt
  app/src/main/java/org/ole/planet/myplanet/ui/news/NewsFragment.kt
Labels: ready to merge

#5967 dashboard: smoother myteams list (fixes #5914)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/dashboard/BellDashboardFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardActivity.kt
  app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardActivity.kt.lite
  app/src/main/java/org/ole/planet/myplanet/ui/team/TeamFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/team/teamMember/MemberDetailFragment.kt
Labels: ready to merge

#5965 teams: smoother realm access (fixes #5964)
  .github/workflows/android-build.yml
  .github/workflows/android-release.yml
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/community/ServicesFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/dashboard/BaseDashboardFragmentPlugin.kt
  app/src/main/java/org/ole/planet/myplanet/ui/dashboard/notification/NotificationsFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/exam/UserInformationFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/team/AdapterTeamList.kt
  app/src/main/java/org/ole/planet/myplanet/ui/team/BaseTeamFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/team/TeamDetailFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/team/TeamPagerAdapter.kt
  app/src/main/java/org/ole/planet/myplanet/ui/team/teamDiscussion/DiscussionListFragment.kt
Labels: ready to merge, peer review

#5976 dashboard: smoother viewmodel refactor (fixes #5986)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardActivity.kt
  app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardActivity.kt.lite
  app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardViewModel.kt
Labels: ready to merge, peer review, codex

#5996 login: smoother username entry (fixes #5984)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/sync/LoginActivity.kt
Labels: ready to merge

#5992 all: smoother `BaseRecyclerFragment` (fixes #5990)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/base/BaseRecyclerFragment.kt
Labels: ready to merge, peer review, codex

#5995 teams: smoother voices complexity (fixes #5993)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/news/AdapterNews.kt
Labels: ready to merge, peer review, codex

#5989 teams: smoother voices buttons (fixes #5988)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/news/AdapterNews.kt
  app/src/main/res/drawable/share_with_community.png
  app/src/main/res/drawable/show_replies.png
  app/src/main/res/layout/row_news.xml
Labels: ready to merge

#6011 all: smoother `BaseDashboardFragmentPlugin.kt` (fixes #6023)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/dashboard/BaseDashboardFragmentPlugin.kt
Labels: peer review, codex

#6012 all: smoother `DashboardActivity.kt` (fixes #6023)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardActivity.kt
  app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardActivity.kt.lite
Labels: peer review, codex

#6015 chat: smoother provider availability (fixes #6014)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/chat/ChatDetailFragment.kt
Labels: ready to merge, peer review

#6036 teams: smoother survery choice other input (fixes #6018)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/model/RealmExamQuestion.kt
  app/src/main/java/org/ole/planet/myplanet/ui/exam/TakeExamFragment.kt
Labels: ready to merge, peer review

#6030 all: smoother `BaseContainerFragment.kt` (fixes #6043)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/base/BaseContainerFragment.kt
Labels: peer review, codex

#6033 dashboard: smoother `DashboardActivity.kt` (fixes #6042)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/dashboard/ChallengeHelper.kt
  app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardActivity.kt
  app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardActivity.kt.lite
Labels: peer review, codex

#6035 dashboard: smoother `UserProfileFragment.kt` (fixes #6039)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/userprofile/UserProfileFragment.kt
Labels: peer review, codex

#6058 chat: smoother `ChatDetailFragment.kt` (fixes #6049)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/chat/ChatApiHelper.kt
  app/src/main/java/org/ole/planet/myplanet/ui/chat/ChatDetailFragment.kt
Labels: peer review, codex

#6059 teams: smoother `AdapterNews.kt` (fixes #6050)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/news/AdapterNews.kt
Labels: peer review, codex

#6060 courses: smoother `TakeExamFragment.kt` (fixes #6051)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/exam/TakeExamFragment.kt
Labels: peer review, codex

#6064 actions: smoother build including codex dependabot (fixes #6063)
  .github/workflows/android-build.yml
  app/build.gradle
Labels: peer review, codex

#6006 login: smoother register fast sync (fixes #5646)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/callback/SecurityDataCallback.kt
  app/src/main/java/org/ole/planet/myplanet/datamanager/Service.kt
  app/src/main/java/org/ole/planet/myplanet/model/RealmUserModel.kt
  app/src/main/java/org/ole/planet/myplanet/service/UploadToShelfService.kt
  app/src/main/java/org/ole/planet/myplanet/ui/sync/LoginActivity.kt
  app/src/main/java/org/ole/planet/myplanet/ui/sync/ProcessUserDataActivity.kt
  app/src/main/java/org/ole/planet/myplanet/ui/sync/SyncActivity.kt
  app/src/main/java/org/ole/planet/myplanet/ui/userprofile/BecomeMemberActivity.kt
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-ne/strings.xml
  app/src/main/res/values-so/strings.xml
  app/src/main/res/values/strings.xml
Labels: peer review

#6079 teams: smoother `AdapterNews.kt` (fixes #6073)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/news/AdapterNews.kt
  app/src/main/java/org/ole/planet/myplanet/utilities/TextViewExtensions.kt
Labels: ready to merge, codex

#6086 login: smoother `BecomeMemberActivity.kt` (fixes #6083)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/userprofile/BecomeMemberActivity.kt
Labels: ready to merge, codex

#6066 teams: smoother survey button next (fixes #6037)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/exam/TakeExamFragment.kt
Labels: ready to merge, peer review

#6080 dashboard: smoother `UserProfileFragment.kt` (fixes #6075)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/userprofile/UserProfileFragment.kt
Labels: codex

#6087 sync: smoother `SyncActivity.kt` (fixes #6084)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/sync/SyncActivity.kt
  app/src/main/java/org/ole/planet/myplanet/utilities/ServerConfigUtils.kt
Labels: ready to merge, codex

#6108 teams: smoother voices label adding options (fixes #5955)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/news/AdapterNews.kt
  app/src/main/res/menu/menu_add_label.xml
Labels: peer review

#6120 login: smoother register server check (fixes #6119)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/MainApplication.kt
Labels: ready to merge

#6089 teams: smoother survey answer validation (fixes #6065)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/exam/BaseExamFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/exam/TakeExamFragment.kt
  app/src/main/java/org/ole/planet/myplanet/utilities/Utilities.kt
Labels: ready to merge, peer review

#6097 mylife: smoother `AchievementFragment.kt` (fixes #6093)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/model/RealmMyLibrary.kt
  app/src/main/java/org/ole/planet/myplanet/ui/userprofile/AchievementFragment.kt
Labels: peer review, codex

#6099 sync: smoother `SyncActivity.kt` (fixes #6078)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/sync/SyncActivity.kt
Labels: peer review, codex

#6101 courses: smoother `TakeExamFragment.kt` (fixes #6076)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/exam/ExamAnswerUtils.kt
  app/src/main/java/org/ole/planet/myplanet/ui/exam/ExamSubmissionUtils.kt
  app/src/main/java/org/ole/planet/myplanet/ui/exam/TakeExamFragment.kt
Labels: peer review

#6124 dashboard: smoother profile language (fixes #6122)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/myhealth/MyHealthFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/userprofile/UserProfileFragment.kt
  app/src/main/java/org/ole/planet/myplanet/utilities/Utilities.kt
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-ne/strings.xml
  app/src/main/res/values-so/strings.xml
  app/src/main/res/values/strings.xml
Labels: ready to merge
