Repository open-learning-exchange/myplanet, pull requests merged in 2025-08, with the labels that each got.

#6554 community: smoother voices searching filter (fixes #6553)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/news/NewsFragment.kt
  app/src/main/res/layout/fragment_news.xml
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-ne/strings.xml
  app/src/main/res/values-so/strings.xml
  app/src/main/res/values/strings.xml
Labels: ready to merge, peer review

#6538 teams: smoother chats (fixes #6537)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/team/TeamDetailFragment.kt
Labels: ready to merge, peer review

#6549 dashboard: smoother survey submissions (fixes #6561)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardActivity.kt
  app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardViewModel.kt
Labels: peer review, codex, ⭐⭐⭐'

#6547 all: smoother realm initialization (fixes #6562)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/MainApplication.kt
  app/src/main/java/org/ole/planet/myplanet/datamanager/Service.kt
  app/src/main/java/org/ole/planet/myplanet/di/DatabaseModule.kt
  app/src/main/java/org/ole/planet/myplanet/model/RealmMyLife.kt
  app/src/main/java/org/ole/planet/myplanet/service/SyncManager.kt
  app/src/main/java/org/ole/planet/myplanet/service/UserProfileDbHandler.kt
  app/src/main/java/org/ole/planet/myplanet/ui/courses/TakeCourseFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/enterprises/AdapterReports.kt
  app/src/main/java/org/ole/planet/myplanet/ui/resources/ResourceDetailFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/sync/GuestLoginExtensions.kt
  app/src/main/java/org/ole/planet/myplanet/ui/sync/SyncActivity.kt
  app/src/main/java/org/ole/planet/myplanet/ui/team/TeamCalendarFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/userprofile/UserProfileFragment.kt
  app/src/main/java/org/ole/planet/myplanet/utilities/DownloadUtils.kt
Labels: peer review, codex, ⭐⭐'

#6519 sync: smoother register and logins (fixes #6518)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/sync/LoginActivity.kt
Labels: priority, peer review

#6567 all: smoother imports (fixes #6568)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/base/BaseResourceFragment.kt
  app/src/main/java/org/ole/planet/myplanet/di/RepositoryModule.kt
  app/src/main/java/org/ole/planet/myplanet/repository/LibraryRepositoryImpl.kt
  app/src/main/java/org/ole/planet/myplanet/service/TransactionSyncManager.kt
  app/src/main/java/org/ole/planet/myplanet/service/UploadToShelfService.kt
  app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardViewModel.kt
  app/src/main/java/org/ole/planet/myplanet/ui/enterprises/AdapterReports.kt
  app/src/main/java/org/ole/planet/myplanet/ui/onBoarding/OnBoardingActivity.kt
  app/src/main/java/org/ole/planet/myplanet/ui/resources/ResourceDetailFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/sync/DashboardElementActivity.kt
  app/src/main/java/org/ole/planet/myplanet/ui/sync/LoginActivity.kt
  app/src/main/java/org/ole/planet/myplanet/ui/team/TeamCalendarFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/userprofile/UserProfileFragment.kt
  app/src/main/java/org/ole/planet/myplanet/utilities/AuthHelper.kt
  app/src/main/java/org/ole/planet/myplanet/utilities/DownloadUtils.kt
Labels: codex

#6574 all: smoother navigation helper (fixes #6588)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/SettingActivity.kt
  app/src/main/java/org/ole/planet/myplanet/ui/chat/ChatHistoryListFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/community/AdapterLeader.kt
  app/src/main/java/org/ole/planet/myplanet/ui/courses/CoursesFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/exam/BaseExamFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/mylife/AdapterMyLife.kt
  app/src/main/java/org/ole/planet/myplanet/ui/navigation/NavigationHelper.kt
  app/src/main/java/org/ole/planet/myplanet/ui/news/NewsFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/resources/AddResourceActivity.kt
  app/src/main/java/org/ole/planet/myplanet/ui/resources/ResourcesFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/sync/DashboardElementActivity.kt
  app/src/main/java/org/ole/planet/myplanet/ui/team/teamDiscussion/DiscussionListFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/team/teamMember/AdapterJoinedMember.kt
Labels: peer review, codex, ⭐⭐., ⭐⭐⭐', ⭐⭐⭐`

#6578 resources: smoother shared preferences (fixes #6590)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/resources/ResourcesFragment.kt
  app/src/main/java/org/ole/planet/myplanet/utilities/SharedPrefManager.kt
Labels: peer review, codex, ⭐⭐., ⭐⭐⭐'

#6556 all: smoother planet connectivity notice (fixes #6555)
  app/build.gradle
  app/src/lite/AndroidManifest.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/ole/planet/myplanet/MainApplication.kt
  app/src/main/java/org/ole/planet/myplanet/service/NetworkConnectivityService.kt
  app/src/main/java/org/ole/planet/myplanet/service/ServerReachabilityWorker.kt
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-ne/strings.xml
  app/src/main/res/values-so/strings.xml
  app/src/main/res/values/strings.xml
Labels: peer review

#6597 all: smoother `NetworkUtils.kt` (fixes #6623)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/utilities/NetworkUtils.kt
Labels: small change, peer review, codex

#6598 all: smoother `JsonUtils.kt` (fixes #6624)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/utilities/JsonUtils.kt
Labels: small change, peer review, codex

#6599 all: smoother `NetworkModule.kt` (fixes #6625)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/di/NetworkModule.kt
Labels: small change, peer review, codex

#6609 teams: smoother plan changing (fixes #6604)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/team/PlanFragment.kt
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-ne/strings.xml
  app/src/main/res/values-so/strings.xml
  app/src/main/res/values/strings.xml
Labels: priority, ready to merge, peer review

#6610 all: smoother notification acknowledgements (fixes #6602)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/dashboard/notification/NotificationsFragment.kt
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-ne/strings.xml
  app/src/main/res/values-so/strings.xml
  app/src/main/res/values/strings.xml
Labels: priority, ready to merge, peer review

#6611 teams: smoother resource removals (fixes #6607)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/team/teamResource/AdapterTeamResource.kt
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-ne/strings.xml
  app/src/main/res/values-so/strings.xml
  app/src/main/res/values/strings.xml
Labels: priority, ready to merge, peer review

#6593 chat: smoother `ChatViewModel.kt` (fixes #6626)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/chat/ChatDetailFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/chat/ChatHistoryListFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/chat/ChatViewModel.kt
Labels: small change, ready to merge, peer review, codex

#6594 courses: smoother repositories (fixes #6627)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/di/RepositoryModule.kt
  app/src/main/java/org/ole/planet/myplanet/repository/CourseProgressRepository.kt
  app/src/main/java/org/ole/planet/myplanet/repository/CourseProgressRepositoryImpl.kt
  app/src/main/java/org/ole/planet/myplanet/repository/LibraryRepository.kt
  app/src/main/java/org/ole/planet/myplanet/repository/LibraryRepositoryImpl.kt
  app/src/main/java/org/ole/planet/myplanet/repository/RatingRepository.kt
  app/src/main/java/org/ole/planet/myplanet/repository/RatingRepositoryImpl.kt
  app/src/main/java/org/ole/planet/myplanet/repository/SearchRepository.kt
  app/src/main/java/org/ole/planet/myplanet/repository/SearchRepositoryImpl.kt
  app/src/main/java/org/ole/planet/myplanet/ui/courses/CoursesViewModel.kt
Labels: ready to merge, peer review, codex

#6608 resources: smoother views (fixes #6605)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/resources/ResourceDetailFragment.kt
Labels: priority, peer review

#6612 teams: smoother survey adoptions (fixes #6606)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/survey/AdapterSurvey.kt
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-ne/strings.xml
  app/src/main/res/values-so/strings.xml
  app/src/main/res/values/strings.xml
Labels: priority, peer review

#6619 teams: smoother reports deletion (fixes #6618)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/enterprises/AdapterReports.kt
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-ne/strings.xml
  app/src/main/res/values-so/strings.xml
  app/src/main/res/values/strings.xml
Labels: priority, peer review

#6634 courses: smoother realm closing (fixes #6641)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/courses/CourseDetailFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/courses/MyProgressFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/courses/TakeCourseFragment.kt
Labels: peer review, codex, ⭐⭐⭐., ⭐⭐⭐'

#6635 all: smoother repository binds (fixes #6642)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/di/RepositoryModule.kt
  app/src/main/java/org/ole/planet/myplanet/repository/UserRepositoryImpl.kt
Labels: peer review, experiment, codex, ⭐⭐⭐., ⭐⭐'

#6628 all: less synchronous `CourseRepository.kt` is more (fixes #6628)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/repository/CourseRepository.kt
  app/src/main/java/org/ole/planet/myplanet/repository/CourseRepositoryImpl.kt
Labels: peer review, codex, ⭐⭐⭐.

#6629 all: less synchronous `UserRepository.kt` is more (fixes #6646)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/repository/UserRepository.kt
  app/src/main/java/org/ole/planet/myplanet/repository/UserRepositoryImpl.kt
Labels: peer review, codex, ⭐⭐⭐.

#6633 all: smoother `NetworkModule.kt` retrofit (fixes #6647)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/MainApplication.kt
  app/src/main/java/org/ole/planet/myplanet/datamanager/ApiClient.kt
  app/src/main/java/org/ole/planet/myplanet/di/NetworkModule.kt
Labels: codex, ⭐⭐⭐.

#6600 teams: smoother voices updates (fixes #6670)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/news/AdapterNews.kt
  app/src/main/java/org/ole/planet/myplanet/ui/news/RealmNewsDiffCallback.kt
Labels: ready to merge, codex

#6652 all: smoother `DownloadUtils.kt` (fixes #6676)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/base/BaseResourceFragment.kt
  app/src/main/java/org/ole/planet/myplanet/model/RealmMyTeam.kt
  app/src/main/java/org/ole/planet/myplanet/ui/dashboard/BaseDashboardFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/dictionary/DictionaryActivity.kt
  app/src/main/java/org/ole/planet/myplanet/ui/sync/SyncActivity.kt
  app/src/main/java/org/ole/planet/myplanet/utilities/DownloadUtils.kt
  app/src/main/java/org/ole/planet/myplanet/utilities/Utilities.kt
Labels: codex, ⭐⭐⭐., ⭐⭐⭐', ⭐⭐⭐`

#6653 all: smoother `ReplyActivity.kt` realm closing (fixes #6677)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/news/ReplyActivity.kt
Labels: codex, ⭐⭐⭐., ⭐⭐⭐', ⭐⭐⭐`

#6655 chat: smoother conversation continuing (fixes #6679)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/chat/ChatDetailFragment.kt
Labels: codex, ⭐⭐⭐., ⭐⭐⭐', ⭐⭐⭐`

#6656 resources: smoother `PDFReaderActivity.kt` realm closing (fixes #6680)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/viewer/PDFReaderActivity.kt
Labels: codex, ⭐⭐⭐., ⭐⭐⭐', ⭐⭐⭐`

#6657 mylife: smoother `AchievementFragment.kt` realm closing (fixes #6681)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/userprofile/AchievementFragment.kt
Labels: codex, ⭐⭐⭐., ⭐⭐⭐', ⭐⭐⭐`

#6669 all: smoother executors (fixes #6683)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/datamanager/Service.kt
  app/src/main/java/org/ole/planet/myplanet/model/RealmMyLife.kt
  app/src/main/java/org/ole/planet/myplanet/utilities/CameraUtils.kt
Labels: codex, ⭐⭐⭐., ⭐⭐⭐', ⭐⭐⭐`

#6668 sync: smoother `SyncActivity.kt` (fixes #6682)
  app/src/main/java/org/ole/planet/myplanet/ui/sync/SyncActivity.kt
Labels: codex, ⭐⭐⭐., ⭐⭐⭐', ⭐⭐⭐`

#6640 all: smoother sync and realm closing (fixes #6684)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/service/UploadToShelfService.kt
  app/src/main/java/org/ole/planet/myplanet/ui/resources/ResourceDetailFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/team/TeamCalendarFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/userprofile/AchievementFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/userprofile/EditAchievementFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/userprofile/UserDetailFragment.kt
Labels: codex, ⭐⭐⭐., ⭐⭐⭐`

#6585 teams: smoother tabbing (fixes #6685)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardActivity.kt
  app/src/main/java/org/ole/planet/myplanet/ui/dashboard/notification/NotificationsFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/team/TeamDetailFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/team/TeamPage.kt
  app/src/main/java/org/ole/planet/myplanet/ui/team/TeamPageConfig.kt
  app/src/main/java/org/ole/planet/myplanet/ui/team/TeamPagerAdapter.kt
Labels: codex

#6673 chat: smoother `ChatAdapter.kt` coroutines (fixes #6703)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/chat/ChatAdapter.kt
Labels: ready to merge, peer review, codex

#6643 dashboard: smoother `DashboardViewModel.kt` (fixes #6704)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardActivity.kt
  app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardViewModel.kt
Labels: ready to merge, peer review, codex

#6674 teams: smoother survey sorting (fixes #6658)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/survey/AdapterSurvey.kt
  app/src/main/java/org/ole/planet/myplanet/ui/survey/SurveyFragment.kt
Labels: ready to merge, peer review

#6692 teams: smoother survey repository queries (fixes #6708)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/repository/SubmissionRepositoryImpl.kt
Labels: ready to merge, peer review, codex

#6697 resources: smoother collections realm closing (fixes #6710)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/resources/CollectionsFragment.kt
Labels: ready to merge, peer review, codex, ⭐⭐⭐'

#6700 all: less `TimeUtils.kt` is more (fixes #6711)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/utilities/TimeUtils.kt
Labels: ready to merge, peer review, codex

#6713 all: smoother `MyActivityFragment.kt` realm closing (fixes #6733)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/dashboard/MyActivityFragment.kt
Labels: ready to merge, peer review, codex, ⭐⭐⭐., ⭐⭐⭐`

#6721 all: smoother user repository realm handling (fixes #6736)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/repository/UserRepositoryImpl.kt
Labels: ready to merge, codex, ⭐⭐⭐.

#6724 all: smoother resources repository realm handling (fixes #6738)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/repository/LibraryRepositoryImpl.kt
Labels: ready to merge, peer review, codex, ⭐⭐⭐.

#6731 login: smoother register realm handling (fixes #6729)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/model/RealmUserModel.kt
  app/src/main/java/org/ole/planet/myplanet/ui/userprofile/BecomeMemberActivity.kt
Labels: codex, ⭐⭐⭐., ⭐⭐⭐', ⭐⭐`

#6739 teams: smoother navigation with helper (fixes #6754)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/team/AdapterTeamList.kt
Labels: ready to merge, codex, ⭐⭐⭐., ⭐⭐⭐', ⭐⭐⭐`

#6743 community: smoother service links realm closing (fixes #6756)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/community/AddLinkFragment.kt
Labels: ready to merge, codex, ⭐⭐⭐., ⭐⭐⭐'

#6745 all: smoother profiles realm closing (fixes #6758)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/exam/UserInformationFragment.kt
Labels: ready to merge, codex, ⭐⭐⭐.

#6746 courses: smoother exams realm closing (fixes #6759)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/exam/BaseExamFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/exam/TakeExamFragment.kt
Labels: ready to merge, codex, ⭐⭐⭐., ⭐⭐⭐'

#6749 courses: smoother progress realm closing (fixes #6762)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/courses/CourseProgressActivity.kt
Labels: ready to merge, codex, ⭐⭐⭐., ⭐⭐⭐'

#6748 all: smoother courses repository user injection (fixes #6761)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/repository/CourseRepositoryImpl.kt
Labels: ready to merge, codex, ⭐⭐⭐., ⭐⭐'

#6777 sync: smoother uploading (fixes #6530)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/sync/SyncActivity.kt
Labels: priority

#6753 teams: smoother voices deletion (fixes #6690)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/news/RealmNewsDiffCallback.kt
Labels: peer review, ⭐⭐⭐.

#6752 teams: smoother detail scope (fixes #6799)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/team/TeamDetailFragment.kt
Labels: ready to merge, codex, ⭐⭐⭐., ⭐⭐'

#6765 all: smoother destroy super calls last (fixes #6800)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/base/BaseContainerFragment.kt
  app/src/main/java/org/ole/planet/myplanet/base/BaseMemberFragment.kt
  app/src/main/java/org/ole/planet/myplanet/base/BaseResourceFragment.kt
  app/src/main/java/org/ole/planet/myplanet/service/NetworkConnectivityService.kt
  app/src/main/java/org/ole/planet/myplanet/ui/SettingActivity.kt
  app/src/main/java/org/ole/planet/myplanet/ui/chat/ChatDetailFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/chat/ChatHistoryListFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/courses/CourseDetailFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/courses/CourseProgressActivity.kt
  app/src/main/java/org/ole/planet/myplanet/ui/courses/CourseStepFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/courses/CoursesFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/courses/TakeCourseFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardActivity.kt
  app/src/main/java/org/ole/planet/myplanet/ui/dashboard/MyActivityFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/dashboard/notification/NotificationsFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/feedback/FeedbackFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/feedback/FeedbackListFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/myPersonals/MyPersonalsFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/myhealth/AddExaminationActivity.kt
  app/src/main/java/org/ole/planet/myplanet/ui/myhealth/AddMyHealthActivity.kt
  app/src/main/java/org/ole/planet/myplanet/ui/myhealth/MyHealthFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/mylife/LifeFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/news/NewsDetailActivity.kt
  app/src/main/java/org/ole/planet/myplanet/ui/news/ReplyActivity.kt
  app/src/main/java/org/ole/planet/myplanet/ui/resources/AddResourceActivity.kt
  app/src/main/java/org/ole/planet/myplanet/ui/resources/CollectionsFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/resources/ResourceDetailFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/resources/ResourcesFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/sync/LoginActivity.kt
  app/src/main/java/org/ole/planet/myplanet/ui/sync/SyncActivity.kt
  app/src/main/java/org/ole/planet/myplanet/ui/team/TeamCalendarFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/team/TeamDetailFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/team/TeamFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/userprofile/AchievementFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/userprofile/EditAchievementFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/userprofile/UserProfileFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/viewer/AudioPlayerActivity.kt
  app/src/main/java/org/ole/planet/myplanet/ui/viewer/PDFReaderActivity.kt
  app/src/main/java/org/ole/planet/myplanet/ui/viewer/VideoPlayerActivity.kt
Labels: ready to merge, codex, ⭐⭐⭐., ⭐⭐⭐'

#6766 login: smoother register realm inheriting (fixes #6801)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/userprofile/BecomeMemberActivity.kt
Labels: ready to merge, codex, ⭐⭐⭐., ⭐⭐⭐'

#6767 all: smoother `NetworkUtils.kt` scope (fixes #6802)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/MainApplication.kt
  app/src/main/java/org/ole/planet/myplanet/utilities/NetworkUtils.kt
Labels: ready to merge, codex, ⭐⭐⭐., ⭐⭐⭐'

#6773 all: less resources repository is more (fixes #6804)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/base/BaseRecyclerFragment.kt
  app/src/main/java/org/ole/planet/myplanet/base/BaseResourceFragment.kt
  app/src/main/java/org/ole/planet/myplanet/repository/LibraryRepository.kt
  app/src/main/java/org/ole/planet/myplanet/repository/LibraryRepositoryImpl.kt
  app/src/main/java/org/ole/planet/myplanet/ui/dashboard/BaseDashboardFragment.kt
Labels: ready to merge, codex, ⭐⭐⭐., ⭐⭐⭐'

#6774 all: less submission repository is more (fixes #6805)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/base/BaseResourceFragment.kt
  app/src/main/java/org/ole/planet/myplanet/repository/SubmissionRepository.kt
  app/src/main/java/org/ole/planet/myplanet/repository/SubmissionRepositoryImpl.kt
  app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardViewModel.kt
Labels: ready to merge, codex, ⭐⭐⭐., ⭐⭐⭐'

#6775 all: smoother course progress repository (fixes #6806)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/repository/CourseProgressRepositoryImpl.kt
Labels: ready to merge, codex, ⭐⭐⭐., ⭐⭐⭐'

#6776 all: smoother rating repository (fixes #6807)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/repository/RatingRepositoryImpl.kt
Labels: ready to merge, codex, ⭐⭐⭐.

#6772 dashboard: less scope is more (fixes #6803)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/dashboard/BellDashboardViewModel.kt
Labels: ready to merge, codex, ⭐⭐⭐., ⭐⭐⭐'

#6797 all: smoother markdown dialogs (fixes #6821)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/utilities/MarkdownDialog.kt
Labels: codex, ⭐⭐⭐., ⭐⭐⭐'

#6728 sync: smoother server availability check (fixes #6727)
  app/build.gradle
  app/src/lite/AndroidManifest.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/ole/planet/myplanet/MainApplication.kt
  app/src/main/java/org/ole/planet/myplanet/service/NetworkConnectivityService.kt
  app/src/main/java/org/ole/planet/myplanet/service/NetworkMonitorWorker.kt
  app/src/main/java/org/ole/planet/myplanet/service/ServerReachabilityWorker.kt
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-ne/strings.xml
  app/src/main/res/values-so/strings.xml
  app/src/main/res/values/strings.xml
Labels: priority, peer review

#6811 all: smoother `JsonUtils.kt` (fixes #6826)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/model/RealmExamQuestion.kt
  app/src/main/java/org/ole/planet/myplanet/ui/exam/ExamAnswerUtils.kt
  app/src/main/java/org/ole/planet/myplanet/ui/exam/TakeExamFragment.kt
  app/src/main/java/org/ole/planet/myplanet/utilities/JsonParserUtils.kt
  app/src/main/java/org/ole/planet/myplanet/utilities/JsonUtils.kt
Labels: peer review, codex

#6814 all: smoother repository realm query list helper (fixes #6827)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/datamanager/DatabaseService.kt
  app/src/main/java/org/ole/planet/myplanet/repository/CourseProgressRepositoryImpl.kt
  app/src/main/java/org/ole/planet/myplanet/repository/CourseRepositoryImpl.kt
  app/src/main/java/org/ole/planet/myplanet/repository/LibraryRepositoryImpl.kt
  app/src/main/java/org/ole/planet/myplanet/repository/RatingRepositoryImpl.kt
  app/src/main/java/org/ole/planet/myplanet/repository/SubmissionRepositoryImpl.kt
  app/src/main/java/org/ole/planet/myplanet/repository/UserRepositoryImpl.kt
Labels: peer review, codex, ⭐⭐⭐., ⭐⭐⭐'

#6815 all: smoother navigation back stack helper (fixes #6828)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/base/BaseContainerFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/courses/TakeCourseFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardActivity.kt
  app/src/main/java/org/ole/planet/myplanet/ui/exam/BaseExamFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/exam/UserInformationFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/navigation/NavigationHelper.kt
  app/src/main/java/org/ole/planet/myplanet/ui/resources/ResourceDetailFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/sync/DashboardElementActivity.kt
  app/src/main/java/org/ole/planet/myplanet/ui/team/teamMember/MemberDetailFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/userprofile/EditAchievementFragment.kt
Labels: peer review, codex, ⭐⭐⭐., ⭐⭐⭐'

#6817 teams: smoother survey sorting (fixes #6829)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/survey/AdapterSurvey.kt
Labels: peer review, codex, ⭐⭐⭐., ⭐⭐⭐'

#6818 all: smoother resources repository (fixes #6831)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/repository/LibraryRepositoryImpl.kt
Labels: peer review, codex, ⭐⭐⭐., ⭐⭐⭐'

#6840 teams: smoother survey diff callback (fixes #6861)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/survey/AdapterSurvey.kt
  app/src/main/java/org/ole/planet/myplanet/ui/survey/SurveyDiffCallback.kt
Labels: codex, ⭐⭐⭐., ⭐⭐⭐', ⭐⭐⭐`

#6839 teams: smoother voices diff callback (fixes #6862)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/news/AdapterNews.kt
  app/src/main/java/org/ole/planet/myplanet/ui/news/NewsDiffCallback.kt
Labels: codex, ⭐⭐⭐., ⭐⭐⭐', ⭐⭐⭐`

#6879 all: smoother `DiffUtil.kt` (fixes #6884)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/news/AdapterNews.kt
  app/src/main/java/org/ole/planet/myplanet/ui/news/NewsDiffCallback.kt
  app/src/main/java/org/ole/planet/myplanet/ui/survey/AdapterSurvey.kt
  app/src/main/java/org/ole/planet/myplanet/ui/survey/SurveyDiffCallback.kt
  app/src/main/java/org/ole/planet/myplanet/utilities/DiffUtil.kt
Labels: priority, experiment, codex, ⭐⭐⭐., ⭐⭐⭐'

#6850 all: smoother `ServicesFragment.kt` scoping (fixes #6888)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/community/ServicesFragment.kt
Labels: codex, ⭐⭐⭐., ⭐⭐⭐', ⭐⭐⭐`

#6860 teams: smoother calendar (fixes #6781)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/team/TeamCalendarFragment.kt
Labels: peer review, ⭐⭐⭐.

#6863 sync: smoother shared constants (fixes #6889)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/sync/SyncActivity.kt
  app/src/main/java/org/ole/planet/myplanet/utilities/SharedPrefManager.kt
Labels: codex, ⭐⭐⭐., ⭐⭐⭐', ⭐⭐⭐`

#6867 all: smoother realm instances (fixes #6893)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/datamanager/DatabaseService.kt
Labels: codex, ⭐⭐⭐., ⭐⭐⭐', ⭐⭐⭐`

#6868 sync: smoother time logging (fixes #6890)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/service/SyncManager.kt
  app/src/main/java/org/ole/planet/myplanet/utilities/SyncTimeLogger.kt
Labels: codex, ⭐⭐⭐., ⭐⭐⭐', ⭐⭐⭐`

#6869 all: smoother `UrlUtils.kt` (fixes #6896)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/base/BaseContainerFragment.kt
  app/src/main/java/org/ole/planet/myplanet/datamanager/FileUploadService.kt
  app/src/main/java/org/ole/planet/myplanet/datamanager/ManagerSync.kt
  app/src/main/java/org/ole/planet/myplanet/datamanager/Service.kt
  app/src/main/java/org/ole/planet/myplanet/model/RealmMyCourse.kt
  app/src/main/java/org/ole/planet/myplanet/model/RealmMyTeam.kt
  app/src/main/java/org/ole/planet/myplanet/model/RealmNews.kt
  app/src/main/java/org/ole/planet/myplanet/model/RealmSubmission.kt
  app/src/main/java/org/ole/planet/myplanet/model/RealmUserModel.kt
  app/src/main/java/org/ole/planet/myplanet/service/AutoSyncWorker.kt
  app/src/main/java/org/ole/planet/myplanet/service/SyncManager.kt
  app/src/main/java/org/ole/planet/myplanet/service/TransactionSyncManager.kt
  app/src/main/java/org/ole/planet/myplanet/service/UploadManager.kt
  app/src/main/java/org/ole/planet/myplanet/service/UploadToShelfService.kt
  app/src/main/java/org/ole/planet/myplanet/ui/sync/LoginActivity.kt
  app/src/main/java/org/ole/planet/myplanet/ui/sync/ProcessUserDataActivity.kt
  app/src/main/java/org/ole/planet/myplanet/ui/sync/SyncActivity.kt
  app/src/main/java/org/ole/planet/myplanet/ui/userprofile/AchievementFragment.kt
  app/src/main/java/org/ole/planet/myplanet/utilities/AuthSessionUpdater.kt
  app/src/main/java/org/ole/planet/myplanet/utilities/DialogUtils.kt
  app/src/main/java/org/ole/planet/myplanet/utilities/DownloadUtils.kt
  app/src/main/java/org/ole/planet/myplanet/utilities/ResourceOpener.kt
  app/src/main/java/org/ole/planet/myplanet/utilities/UrlUtils.kt
  app/src/main/java/org/ole/planet/myplanet/utilities/Utilities.kt
Labels: peer review, codex, ⭐⭐⭐., ⭐⭐⭐', ⭐⭐⭐`

#6870 all: smoother realm find helper (fixes #6897)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/datamanager/DatabaseService.kt
  app/src/main/java/org/ole/planet/myplanet/repository/CourseRepositoryImpl.kt
  app/src/main/java/org/ole/planet/myplanet/repository/LibraryRepositoryImpl.kt
  app/src/main/java/org/ole/planet/myplanet/repository/SubmissionRepositoryImpl.kt
  app/src/main/java/org/ole/planet/myplanet/repository/UserRepositoryImpl.kt
Labels: codex, ⭐⭐⭐., ⭐⭐⭐'

#6871 courses: smoother repository owning flag (fixes #6899)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/repository/CourseRepository.kt
  app/src/main/java/org/ole/planet/myplanet/repository/CourseRepositoryImpl.kt
  app/src/main/java/org/ole/planet/myplanet/ui/courses/CoursesViewModel.kt
Labels: codex, ⭐⭐., ⭐⭐'

#6702 teams: smoother leader switching (fixes #6663)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/team/teamMember/AdapterJoinedMember.kt
Labels: priority, ready to merge, peer review

#6910 all: less repository suffix is more (fixes #6919)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/base/BaseResourceFragment.kt
  app/src/main/java/org/ole/planet/myplanet/repository/LibraryRepository.kt
  app/src/main/java/org/ole/planet/myplanet/repository/LibraryRepositoryImpl.kt
  app/src/main/java/org/ole/planet/myplanet/repository/SubmissionRepository.kt
  app/src/main/java/org/ole/planet/myplanet/repository/SubmissionRepositoryImpl.kt
  app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardViewModel.kt
Labels: codex, ⭐⭐⭐.

#6864 all: smoother `Utilities.kt` hexing (fixes #6925)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/utilities/Utilities.kt
Labels: codex, ⭐⭐⭐.

#6906 sync: smoother server listing (fixes #6928)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/sync/ServerAddressAdapter.kt
Labels: peer review, codex

#6907 mylife: smoother myhealth realm closing (fixes #6929)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/myhealth/MyHealthFragment.kt
  app/src/main/java/org/ole/planet/myplanet/utilities/CameraUtils.kt
  app/src/main/java/org/ole/planet/myplanet/utilities/MapTileUtils.kt
Labels: peer review, codex

#6911 dashboard: smoother base fragment realm closing (fixes #6930)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/dashboard/BaseDashboardFragment.kt
Labels: codex, ⭐⭐⭐., ⭐⭐⭐', ⭐⭐⭐`

#6913 all: smoother base recycler fragment realm closing (fixes #6932)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/base/BaseRecyclerFragment.kt
Labels: codex, ⭐⭐⭐., ⭐⭐⭐', ⭐⭐⭐`

#6914 mylife: smoother achievements realm listeners closing (fixes #6933)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/userprofile/AchievementFragment.kt
Labels: codex, ⭐⭐⭐., ⭐⭐⭐', ⭐⭐⭐`

#6915 teams: smoother realm listeners closing (fixes #6934)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/team/TeamFragment.kt
Labels: codex, ⭐⭐⭐., ⭐⭐⭐`

#6916 community: smoother realm listeners closing (fixes #6935)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/community/CommunityFragment.kt
Labels: codex, ⭐⭐⭐., ⭐⭐⭐`

#6917 teams: smoother calendar realm (fixes #6936)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/team/TeamCalendarFragment.kt
Labels: codex, ⭐⭐⭐.

#6923 dashboard: smoother view model (fixes #6873)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardViewModel.kt
Labels: codex, ⭐⭐⭐.

#6920 teams: smoother realm transactions (fixes #6795)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/team/TeamDetailFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/team/teamDiscussion/DiscussionListFragment.kt
Labels: peer review

#6908 all: smoother view bindings (fixes #6905)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/calendar/CalendarFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/chat/ChatDetailFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/chat/ChatHistoryListFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/courses/CourseDetailFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/courses/CourseProgressActivity.kt
  app/src/main/java/org/ole/planet/myplanet/ui/courses/MyProgressFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/dashboard/AboutFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardActivity.kt
  app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DisclaimerFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/dashboard/InactiveDashboardFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/dashboard/MyActivityFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/feedback/FeedbackFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/feedback/FeedbackListFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/helpwanted/HelpWantedFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/myhealth/AddExaminationActivity.kt
  app/src/main/java/org/ole/planet/myplanet/ui/myhealth/AddMyHealthActivity.kt
  app/src/main/java/org/ole/planet/myplanet/ui/myhealth/MyHealthFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/news/NewsDetailActivity.kt
  app/src/main/java/org/ole/planet/myplanet/ui/news/NewsFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/rating/RatingFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/references/ReferenceFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/resources/AddResourceActivity.kt
  app/src/main/java/org/ole/planet/myplanet/ui/resources/CollectionsFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/resources/ResourceDetailFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/submission/MySubmissionFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/submission/SubmissionDetailFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/sync/LoginActivity.kt
  app/src/main/java/org/ole/planet/myplanet/ui/userprofile/UserProfileFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/viewer/CSVViewerActivity.kt
  app/src/main/java/org/ole/planet/myplanet/ui/viewer/ImageViewerActivity.kt
  app/src/main/java/org/ole/planet/myplanet/ui/viewer/MarkdownViewerActivity.kt
  app/src/main/java/org/ole/planet/myplanet/ui/viewer/PDFReaderActivity.kt
  app/src/main/java/org/ole/planet/myplanet/ui/viewer/TextFileViewerActivity.kt
Labels: peer review, 🐳💥🌀>

#6940 all: smoother `NotificationUtil.kt` realm handling (fixes #6968)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/datamanager/DatabaseService.kt
  app/src/main/java/org/ole/planet/myplanet/datamanager/ManagerSync.kt
  app/src/main/java/org/ole/planet/myplanet/utilities/NotificationUtil.kt
Labels: codex, ⭐⭐⭐', ⭐⭐⭐`

#6943 all: smoother feedback realm closing (fixes #6969)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/feedback/FeedbackDetailActivity.kt
Labels: codex, ⭐⭐⭐., ⭐⭐⭐', ⭐⭐⭐`

#6947 all: smoother repository realm centralization (fixes #6971)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/repository/CourseProgressRepositoryImpl.kt
  app/src/main/java/org/ole/planet/myplanet/repository/CourseRepositoryImpl.kt
  app/src/main/java/org/ole/planet/myplanet/repository/LibraryRepositoryImpl.kt
  app/src/main/java/org/ole/planet/myplanet/repository/RatingRepositoryImpl.kt
  app/src/main/java/org/ole/planet/myplanet/repository/RealmRepository.kt
  app/src/main/java/org/ole/planet/myplanet/repository/SearchRepositoryImpl.kt
  app/src/main/java/org/ole/planet/myplanet/repository/SubmissionRepositoryImpl.kt
  app/src/main/java/org/ole/planet/myplanet/repository/UserRepositoryImpl.kt
Labels: priority, codex, ⭐⭐⭐., ⭐⭐⭐'

#6946 resources: smoother user handling (fixes #6977)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/resources/ResourcesFragment.kt
Labels: codex, ⭐⭐⭐., ⭐⭐⭐', ⭐⭐⭐`

#6941 resources: smoother list updates (fixes #6978)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/resources/AdapterResource.kt
Labels: codex, ⭐⭐⭐., ⭐⭐⭐`

#6942 courses: smoother list updates (fixes #6979)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/courses/AdapterCourses.kt
Labels: codex, ⭐⭐⭐., ⭐⭐⭐', ⭐⭐⭐`

#7004 teams: smoother member removing (fixes #6961)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/team/teamMember/AdapterJoinedMember.kt
Labels: priority

#6991 all: smoother repository realm comparisons (fixes #7012)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/datamanager/DatabaseService.kt
  app/src/main/java/org/ole/planet/myplanet/repository/RealmRepository.kt
Labels: codex, ⭐⭐⭐.

#6998 courses: smoother repository submission count (fixes #7013)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/repository/SubmissionRepository.kt
  app/src/main/java/org/ole/planet/myplanet/repository/SubmissionRepositoryImpl.kt
  app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardViewModel.kt
Labels: codex, ⭐⭐⭐.

#6999 all: smoother notification repository unread counting (fixes #7014)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/di/RepositoryModule.kt
  app/src/main/java/org/ole/planet/myplanet/repository/NotificationRepository.kt
  app/src/main/java/org/ole/planet/myplanet/repository/NotificationRepositoryImpl.kt
  app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardViewModel.kt
Labels: codex, ⭐⭐⭐.

#7007 all: less repository constructor commas is more (fixes #7018)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/repository/CourseRepositoryImpl.kt
  app/src/main/java/org/ole/planet/myplanet/repository/SubmissionRepositoryImpl.kt
  app/src/main/java/org/ole/planet/myplanet/repository/UserRepositoryImpl.kt
Labels: ready to merge, codex

#6992 resources: smoother local path opening (fixes #7021)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/utilities/ResourceOpener.kt
Labels: ready to merge, codex, ⭐⭐⭐.

#7001 teams: smoother member details binding (fixes #7022)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/team/teamMember/MemberDetailFragment.kt
Labels: small change, ready to merge, codex, ⭐⭐⭐., ⭐⭐⭐`

#6994 courses: smoother list diffing (fixes #7025)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/courses/AdapterCourses.kt
Labels: ready to merge, codex, ⭐⭐⭐.

#7036 Replace LibraryRepository with ResourceRepository
  app/src/main/java/org/ole/planet/myplanet/base/BaseResourceFragment.kt
  app/src/main/java/org/ole/planet/myplanet/repository/ResourceRepository.kt
  app/src/main/java/org/ole/planet/myplanet/repository/ResourceRepositoryImpl.kt
  app/src/main/java/org/ole/planet/myplanet/ui/courses/CoursesViewModel.kt
  app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardViewModel.kt
  app/src/main/java/org/ole/planet/myplanet/ui/resources/ResourcesFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/team/teamResource/TeamResourceFragment.kt
Labels: codex

#7038 all: smoother imports (fixes #7040)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/repository/SubmissionRepositoryImpl.kt
  app/src/main/java/org/ole/planet/myplanet/ui/sync/ServerAddressAdapter.kt
  app/src/main/java/org/ole/planet/myplanet/ui/sync/SyncActivity.kt
  app/src/main/java/org/ole/planet/myplanet/ui/team/teamDiscussion/DiscussionListFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/team/teamResource/TeamResourceFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/userprofile/AchievementFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/userprofile/UserProfileFragment.kt
  app/src/main/java/org/ole/planet/myplanet/utilities/ResourceOpener.kt
Labels: codex

#7042 all: smoother `NotificationUtils.kt` (fixes #7063)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/MainApplication.kt
  app/src/main/java/org/ole/planet/myplanet/service/SyncManager.kt
  app/src/main/java/org/ole/planet/myplanet/service/TaskNotificationWorker.kt
  app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardActivity.kt
  app/src/main/java/org/ole/planet/myplanet/ui/sync/DashboardElementActivity.kt
  app/src/main/java/org/ole/planet/myplanet/ui/sync/SyncActivity.kt
  app/src/main/java/org/ole/planet/myplanet/ui/viewer/PDFReaderActivity.kt
  app/src/main/java/org/ole/planet/myplanet/utilities/NotificationUtils.kt
Labels: ready to merge, codex, ⭐⭐⭐., ⭐⭐⭐'

#7046 all: smoother `UrlUtils.kt` (fixes #7066)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/datamanager/DownloadWorker.kt
  app/src/main/java/org/ole/planet/myplanet/datamanager/FileUploadService.kt
  app/src/main/java/org/ole/planet/myplanet/datamanager/ManagerSync.kt
  app/src/main/java/org/ole/planet/myplanet/datamanager/MyDownloadService.kt
  app/src/main/java/org/ole/planet/myplanet/datamanager/Service.kt
  app/src/main/java/org/ole/planet/myplanet/model/RealmSubmission.kt
  app/src/main/java/org/ole/planet/myplanet/service/SyncManager.kt
  app/src/main/java/org/ole/planet/myplanet/service/TransactionSyncManager.kt
  app/src/main/java/org/ole/planet/myplanet/service/UploadManager.kt
  app/src/main/java/org/ole/planet/myplanet/service/UploadToShelfService.kt
  app/src/main/java/org/ole/planet/myplanet/ui/chat/ChatApiHelper.kt
  app/src/main/java/org/ole/planet/myplanet/ui/sync/ProcessUserDataActivity.kt
  app/src/main/java/org/ole/planet/myplanet/utilities/UrlUtils.kt
  app/src/main/java/org/ole/planet/myplanet/utilities/Utilities.kt
Labels: ready to merge, codex, ⭐⭐⭐., ⭐⭐⭐'

#7048 all: smoother notification diffing (fixes #7068)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/dashboard/notification/AdapterNotification.kt
Labels: ready to merge, codex, ⭐⭐⭐., ⭐⭐⭐'

#7050 all: smoother `SelectionUtils.kt` (fixes #7069)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/courses/AdapterCourses.kt
  app/src/main/java/org/ole/planet/myplanet/ui/resources/AdapterResource.kt
  app/src/main/java/org/ole/planet/myplanet/utilities/SelectionUtils.kt
  app/src/main/java/org/ole/planet/myplanet/utilities/Utilities.kt
Labels: ready to merge, codex, ⭐⭐⭐., ⭐⭐⭐'

#7028 actions: smoother module gradle build script (fixes #7071)
  app/build.gradle
  app/build.gradle.kts
Labels: ready to merge, codex, ⭐⭐⭐., ⭐⭐⭐'

#7074 all: smoother profile realm handling (fixes #7090)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/sync/ProcessUserDataActivity.kt
Labels: ready to merge, peer review, codex, ⭐⭐⭐., ⭐⭐⭐', ⭐⭐⭐`

#7081 all: smoother feedback repository realm handling (fixes #7091)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/repository/FeedbackRepository.kt
Labels: ready to merge, peer review, codex, ⭐⭐⭐., ⭐⭐⭐', ⭐⭐⭐`

#7075 teams: smoother discussion list realm handling (fixes #7092)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/team/teamDiscussion/DiscussionListFragment.kt
Labels: ready to merge, peer review, codex, ⭐⭐⭐., ⭐⭐⭐', ⭐⭐⭐`

#7076 teams: smoother finances realm closing (fixes #7094)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/enterprises/FinanceFragment.kt
Labels: ready to merge, peer review, codex, ⭐⭐⭐., ⭐⭐⭐', ⭐⭐⭐`

#7079 teams: smoother resources binding (fixes #7096)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/team/teamResource/TeamResourceFragment.kt
Labels: ready to merge, peer review, codex, ⭐⭐⭐., ⭐⭐⭐', ⭐⭐⭐`

#7080 mylife: smoother achievements binding (fixes #7097)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/userprofile/AchievementFragment.kt
Labels: ready to merge, peer review, codex, ⭐⭐⭐., ⭐⭐⭐', ⭐⭐⭐`

#7056 all: smoother feedback lists (fixes #6730)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/repository/FeedbackRepository.kt
Labels: codex, ⭐⭐⭐.

#7101 teams: smoother survey realm handling and closing (fixes #7123)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/survey/SendSurveyFragment.kt
Labels: codex, ⭐⭐⭐., ⭐⭐⭐`

#7102 all: smoother notification realm handling and closing (fixes #7124)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/dashboard/notification/NotificationsFragment.kt
Labels: codex, ⭐⭐⭐., ⭐⭐⭐`

#7103 community: smoother voices binding and realm closing (fixes #7125)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/community/CommunityFragment.kt
Labels: codex, ⭐⭐⭐., ⭐⭐⭐`

#7104 teams: smoother details binding and realm closing (fixes #7126)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/team/TeamDetailFragment.kt
Labels: codex, ⭐⭐⭐., ⭐⭐⭐`

#7112 chat: smoother history lists (fixes #7130)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/chat/ChatHistoryListAdapter.kt
Labels: codex, ⭐⭐⭐.

#7106 teams: smoother tasks binding and realm closing (fixes #7128)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/team/teamTask/TeamTaskFragment.kt
Labels: codex, ⭐⭐⭐.

#7108 all: smoother feedback detail view model (fixes #7133)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/repository/FeedbackRepository.kt
  app/src/main/java/org/ole/planet/myplanet/ui/feedback/FeedbackDetailActivity.kt
  app/src/main/java/org/ole/planet/myplanet/ui/feedback/FeedbackDetailViewModel.kt
Labels: codex, ⭐⭐⭐.

#7114 teams: smoother discussion list binding (fixes #7132)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/team/teamDiscussion/DiscussionListFragment.kt
Labels: codex, ⭐⭐⭐.

#7115 all: smoother feedback adapter item callback (fixes #7134)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/feedback/AdapterFeedback.kt
Labels: codex, ⭐⭐⭐.

#6880 sync: smoother beta (fixes #6511)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/base/BaseRealtimeFragment.kt
  app/src/main/java/org/ole/planet/myplanet/callback/RealtimeSyncListener.kt
  app/src/main/java/org/ole/planet/myplanet/service/ImprovedSyncManager.kt
  app/src/main/java/org/ole/planet/myplanet/service/SyncManager.kt
  app/src/main/java/org/ole/planet/myplanet/service/sync/AdaptiveBatchProcessor.kt
  app/src/main/java/org/ole/planet/myplanet/service/sync/CircuitBreaker.kt
  app/src/main/java/org/ole/planet/myplanet/service/sync/OptimizedSyncStrategy.kt
  app/src/main/java/org/ole/planet/myplanet/service/sync/RealmConnectionPool.kt
  app/src/main/java/org/ole/planet/myplanet/service/sync/RealtimeSyncCoordinator.kt
  app/src/main/java/org/ole/planet/myplanet/service/sync/StandardSyncStrategy.kt
  app/src/main/java/org/ole/planet/myplanet/service/sync/SyncPerformanceMonitor.kt
  app/src/main/java/org/ole/planet/myplanet/service/sync/SyncStrategy.kt
  app/src/main/java/org/ole/planet/myplanet/service/sync/ThreadSafeRealmHelper.kt
  app/src/main/java/org/ole/planet/myplanet/ui/chat/ChatHistoryListFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/courses/CoursesFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/feedback/FeedbackListFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/myhealth/MyHealthFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/resources/RealtimeLibraryFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/resources/ResourcesFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/survey/SurveyFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/sync/RealtimeSyncMixin.kt
  app/src/main/java/org/ole/planet/myplanet/ui/team/TeamDetailFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/userprofile/AchievementFragment.kt
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-ne/strings.xml
  app/src/main/res/values-so/strings.xml
  app/src/main/res/values/strings.xml
Labels: priority, peer review

#7160 team: smoother member accepting and rejecting (fixes #6787)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/team/teamMember/AdapterMemberRequest.kt
Labels: ready to merge

#7136 courses: smoother progress realm handling (fixes #7169)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/courses/MyProgressFragment.kt
Labels: ready to merge, codex, ⭐⭐⭐., ⭐⭐⭐', ⭐⭐⭐`

#7138 dashboard: smoother activity realm handling (fixes #7170)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/dashboard/MyActivityFragment.kt
Labels: ready to merge, codex, ⭐⭐⭐., ⭐⭐⭐', ⭐⭐⭐`

#7139 teams: smoother view binding (fixes #7171)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/team/TeamFragment.kt
Labels: ready to merge, codex, ⭐⭐⭐., ⭐⭐⭐'

#7140 dashboard: smoother profile binding (fixes #7172)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/userprofile/UserDetailFragment.kt
Labels: ready to merge, codex, ⭐⭐⭐., ⭐⭐⭐'

#7141 teams: smoother mine detail binding (fixes #7173)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/team/MyTeamsDetailFragment.kt
Labels: ready to merge, codex, ⭐⭐⭐., ⭐⭐⭐', ⭐⭐⭐`

#7148 teams: smoother list diffing (fixes #7176)
  app/src/main/java/org/ole/planet/myplanet/ui/team/AdapterTeam.kt
Labels: ready to merge, codex, ⭐⭐⭐.

#7149 chat: smoother list diffing (fixes #7179)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/chat/ChatAdapter.kt
  app/src/main/java/org/ole/planet/myplanet/ui/chat/ChatDetailFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/news/AdapterNews.kt
Labels: codex, ⭐⭐⭐.

#7183 sync: smoother realm handling (fixes #7202)
  app/src/main/java/org/ole/planet/myplanet/ui/sync/SyncActivity.kt
Labels: codex, ⭐⭐⭐., ⭐⭐⭐', ⭐⭐⭐`
