Repository open-learning-exchange/myplanet, pull requests merged in 2025-10, with the labels that each got.

#8051 teams: less delete report is more (fixes #8076)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/model/RealmMyTeam.kt
Labels: triage, less, ready to merge, codex, ⭐⭐⭐., ⭐⭐⭐'

#8053 teams: less leader is more (fixes #8078)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/model/RealmMyTeam.kt
Labels: triage, less, ready to merge, codex, ⭐⭐⭐., ⭐⭐⭐'

#8054 all: less challenge actions is more (fixes #8079)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/model/RealmUserChallengeActions.kt
Labels: triage, less, ready to merge, codex, ⭐⭐⭐., ⭐⭐⭐'

#8047 teams: smoother survey question birthyear (fixes #8046)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/exam/UserInformationFragment.kt
  app/src/main/res/layout/fragment_user_information.xml
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-ne/strings.xml
  app/src/main/res/values-so/strings.xml
  app/src/main/res/values/strings.xml
Labels: priority, ready to merge, ⭐⭐⭐', ⭐⭐⭐`

#8049 courses: smoother collection tag filtering (fixes #8048)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/base/BaseRecyclerFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/courses/AdapterCourses.kt
Labels: priority, ready to merge, ⭐⭐⭐', ⭐⭐⭐`

#8062 teams: smoother voices refreshing (fixes #8081)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/base/BaseNewsFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/news/AdapterNews.kt
Labels: small change, ready to merge, codex, ⭐⭐⭐., ⭐⭐⭐', ⭐⭐⭐`

#8065 all: smoother feedback timestamp handling (fixes #8082)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/repository/FeedbackRepositoryImpl.kt
Labels: small change, ready to merge, codex, ⭐⭐⭐., ⭐⭐⭐', ⭐⭐⭐`

#8066 teams: smoother task repository status completion updating (fixes #8083)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/repository/TeamRepository.kt
  app/src/main/java/org/ole/planet/myplanet/repository/TeamRepositoryImpl.kt
  app/src/main/java/org/ole/planet/myplanet/ui/team/teamTask/TeamTaskFragment.kt
Labels: ready to merge, codex, ⭐⭐⭐., ⭐⭐⭐', ⭐⭐⭐`

#8067 courses: smoother submission repository steps checking (fixes #8084)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/repository/SubmissionRepository.kt
  app/src/main/java/org/ole/planet/myplanet/repository/SubmissionRepositoryImpl.kt
  app/src/main/java/org/ole/planet/myplanet/ui/courses/CourseStepFragment.kt
Labels: ready to merge, codex, ⭐⭐⭐., ⭐⭐⭐', ⭐⭐⭐`

#8090 dashboard: less loading is more (fixes #8124)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardViewModel.kt
Labels: triage, less, codex, ⭐⭐⭐.

#8100 all: less badge drawable assets is more (fixes #8130)
  app/build.gradle
  app/src/main/res/drawable/b_a.png
  app/src/main/res/drawable/c_a.png
  app/src/main/res/drawable/c_b.png
  app/src/main/res/drawable/o_b.png
Labels: triage, less, codex, ⭐⭐⭐.

#8102 dashboard: less icon assets is more (fixes #8132)
  app/build.gradle
  app/src/main/res/drawable-anydpi/ic_dashboard.xml
  app/src/main/res/drawable-hdpi/ic_dashboard.png
  app/src/main/res/drawable-mdpi/ic_dashboard.png
  app/src/main/res/drawable-xhdpi/ic_dashboard.png
  app/src/main/res/drawable-xxhdpi/ic_dashboard.png
Labels: triage, less, ready to merge, codex, ⭐⭐⭐.

#8026 teams: smoother survey repository loading (fixes #8135)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/di/RepositoryModule.kt
  app/src/main/java/org/ole/planet/myplanet/repository/SurveyRepository.kt
  app/src/main/java/org/ole/planet/myplanet/repository/SurveyRepositoryImpl.kt
  app/src/main/java/org/ole/planet/myplanet/ui/survey/SurveyFragment.kt
Labels: ready to merge, experiment, codex, ⭐⭐⭐., ⭐⭐⭐', ⭐⭐⭐`

#8112 teams: smoother plan user profile inheriting (fixes #8137)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/team/PlanFragment.kt
Labels: small change, ready to merge, codex, ⭐⭐⭐., ⭐⭐⭐', ⭐⭐⭐`

#8087 courses: smoother exam submissions (fixes #8073)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/exam/TakeExamFragment.kt
Labels: priority, ready to merge, peer review, ⭐⭐⭐', ⭐⭐⭐`

#8120 courses: smoother repository steps querying (fixes #8139)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/repository/CourseRepositoryImpl.kt
Labels: small change, ready to merge, codex, ⭐⭐⭐., ⭐⭐⭐', ⭐⭐⭐`

#8109 community: smoother user profile handling (fixes #8147)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/community/CommunityTabFragment.kt
Labels: small change, ready to merge, codex, ⭐⭐⭐., ⭐⭐⭐', ⭐⭐⭐`

#8122 courses: smoother repository exams counting (fixes #8149)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/repository/CourseRepositoryImpl.kt
Labels: small change, ready to merge, codex, ⭐⭐⭐., ⭐⭐⭐', ⭐⭐⭐`

#8091 teams: less status repository is more (fixes #8150)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/repository/TeamRepository.kt
  app/src/main/java/org/ole/planet/myplanet/repository/TeamRepositoryImpl.kt
Labels: triage, less, ready to merge, experiment, codex, ⭐⭐⭐.

#8114 sync: smoother exam result detecting (fixes #8151)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/service/ServerReachabilityWorker.kt
Labels: small change, ready to merge, codex, ⭐⭐⭐., ⭐⭐⭐'

#8155 sync: less optimized is more (fixes #8176)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/service/ImprovedSyncManager.kt
  app/src/main/java/org/ole/planet/myplanet/service/SyncManager.kt
  app/src/main/java/org/ole/planet/myplanet/service/sync/OptimizedSyncStrategy.kt
Labels: triage, less, ready to merge, experiment, codex, ⭐⭐⭐.

#8157 teams: less add member drawable is more (fixes #8178)
  app/build.gradle
  app/src/main/res/drawable-anydpi/ic_add_member.xml
Labels: triage, less, ready to merge, codex, ⭐⭐⭐.

#8158 login: less gif animation is more (fixes #8179)
  app/build.gradle
  app/src/main/res/drawable/file_upload_animation_login_deprecated.gif
Labels: triage, less, ready to merge, codex, ⭐⭐⭐.

#8159 all: less dropdown color is more (fixes #8180)
  app/build.gradle
  app/src/main/res/color/dropdown_background.xml
  app/src/main/res/color/dropdown_text_color.xml
Labels: triage, less, ready to merge, codex, ⭐⭐⭐.

#8160 dashboard: less help wanted is more (fixes #8181)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/dashboard/BaseDashboardFragmentPlugin.kt
  app/src/main/java/org/ole/planet/myplanet/ui/helpwanted/HelpWantedFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/mylife/AdapterMyLife.kt
  app/src/main/java/org/ole/planet/myplanet/utilities/Constants.kt
  app/src/main/res/drawable/ic_help_wanted.png
  app/src/main/res/layout/fragment_help_wanted.xml
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-ne/strings.xml
  app/src/main/res/values-so/strings.xml
  app/src/main/res/values/strings.xml
Labels: triage, less, ready to merge, codex, ⭐⭐⭐.

#8162 all: smoother feedback user profile handling (fixes #8184)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/feedback/FeedbackFragment.kt
Labels: small change, ready to merge, codex, ⭐⭐⭐., ⭐⭐⭐`

#8165 dashboard: smoother profile user handling (fixes #8187)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/userprofile/UserProfileFragment.kt
Labels: small change, ready to merge, codex, ⭐⭐⭐., ⭐⭐⭐`

#8169 courses: smoother details navigating (fixes #8097)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/courses/AdapterCourses.kt
Labels: priority, ready to merge, peer review, ⭐⭐⭐.

#8058 teams: smoother task notification worker dependency injecting (fixes #8153)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/di/WorkerDependenciesEntryPoint.kt
  app/src/main/java/org/ole/planet/myplanet/service/TaskNotificationWorker.kt
  app/src/main/java/org/ole/planet/myplanet/service/UserProfileDbHandler.kt
Labels: priority, ready to merge, codex, ⭐⭐⭐., ⭐⭐⭐'

#8189 sync: less realtime progress tracking is more (fixes #8209)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/service/sync/RealtimeSyncCoordinator.kt
Labels: triage, less, ready to merge, codex, ⭐⭐⭐.

#8190 sync: less retry is more (fixes #8210)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/service/sync/CircuitBreaker.kt
Labels: triage, less, ready to merge, codex, ⭐⭐⭐.

#8191 sync: less performance monitor metrics is more (fixes #8211)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/service/sync/SyncPerformanceMonitor.kt
Labels: triage, less, ready to merge, codex, ⭐⭐⭐.

#8192 teams: less submission count repository is more (fixes #8212)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/repository/SubmissionRepository.kt
  app/src/main/java/org/ole/planet/myplanet/repository/SubmissionRepositoryImpl.kt
Labels: triage, less, ready to merge, codex, ⭐⭐⭐.

#8193 mylife: less my personals is more (fixes #8213)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/myPersonals/MyPersonalsFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/resources/AddResourceFragment.kt
Labels: triage, less, ready to merge, codex, ⭐⭐⭐.

#8194 sync: less circuit breaker is more (fixes #8214)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/service/sync/CircuitBreaker.kt
Labels: triage, less, ready to merge, codex, ⭐⭐⭐.

#8195 all: less progress icon density is more (fixes #8215)
  app/build.gradle
  app/src/main/res/drawable-hdpi/ic_progress.png
  app/src/main/res/drawable-mdpi/ic_progress.png
  app/src/main/res/drawable-xhdpi/ic_progress.png
  app/src/main/res/drawable-xxhdpi/ic_progress.png
Labels: triage, less, ready to merge, codex, ⭐⭐⭐.

#8196 teams: less survey icon is more (fixes #8216)
  app/build.gradle
  app/src/main/res/drawable-hdpi/ic_survey.png
  app/src/main/res/drawable-mdpi/ic_survey.png
  app/src/main/res/drawable-xhdpi/ic_survey.png
  app/src/main/res/drawable-xxhdpi/ic_survey.png
Labels: triage, less, ready to merge, codex, ⭐⭐⭐.

#8198 resources: less storage icons is more (fixes #8218)
  app/build.gradle
  app/src/main/res/drawable-hdpi/baseline_storage_black_18.png
  app/src/main/res/drawable-hdpi/baseline_storage_black_24.png
  app/src/main/res/drawable-hdpi/baseline_storage_black_36.png
  app/src/main/res/drawable-hdpi/baseline_storage_black_48.png
  app/src/main/res/drawable-mdpi/baseline_storage_black_18.png
  app/src/main/res/drawable-mdpi/baseline_storage_black_24.png
  app/src/main/res/drawable-mdpi/baseline_storage_black_36.png
  app/src/main/res/drawable-mdpi/baseline_storage_black_48.png
  app/src/main/res/drawable-xhdpi/baseline_storage_black_18.png
  app/src/main/res/drawable-xhdpi/baseline_storage_black_24.png
  app/src/main/res/drawable-xhdpi/baseline_storage_black_36.png
  app/src/main/res/drawable-xhdpi/baseline_storage_black_48.png
  app/src/main/res/drawable-xxhdpi/baseline_storage_black_18.png
  app/src/main/res/drawable-xxhdpi/baseline_storage_black_24.png
  app/src/main/res/drawable-xxhdpi/baseline_storage_black_36.png
  app/src/main/res/drawable-xxhdpi/baseline_storage_black_48.png
  app/src/main/res/drawable-xxxhdpi/baseline_storage_black_18.png
  app/src/main/res/drawable-xxxhdpi/baseline_storage_black_24.png
  app/src/main/res/drawable-xxxhdpi/baseline_storage_black_36.png
  app/src/main/res/drawable-xxxhdpi/baseline_storage_black_48.png
Labels: triage, less, ready to merge, codex, ⭐⭐⭐.

#8207 teams: smoother details updating (fixes #8115)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/callback/TeamUpdateListener.kt
  app/src/main/java/org/ole/planet/myplanet/ui/team/PlanFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/team/TeamDetailFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/team/TeamPagerAdapter.kt
Labels: priority, ready to merge, ⭐⭐⭐', ⭐⭐⭐`

#8199 teams: smoother voices creating (fixes #8110)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/model/RealmNews.kt
  app/src/main/java/org/ole/planet/myplanet/ui/team/teamDiscussion/DiscussionListFragment.kt
Labels: priority, ready to merge, ⭐⭐⭐', ⭐⭐⭐`

#8200 courses: smoother submission user profile handling (fixes #8223)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/submission/MySubmissionFragment.kt
Labels: small change, ready to merge, codex, ⭐⭐⭐., ⭐⭐⭐', ⭐⭐⭐`

#8201 teams: smoother events user profile handling (fixes #8224)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/mymeetup/MyMeetupDetailFragment.kt
Labels: small change, ready to merge, codex, ⭐⭐⭐., ⭐⭐⭐', ⭐⭐⭐`

#8208 all: smoother feedback view model navigation closing (fixes #8230)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/feedback/FeedbackDetailActivity.kt
  app/src/main/java/org/ole/planet/myplanet/ui/feedback/FeedbackDetailViewModel.kt
Labels: ready to merge, experiment, codex, ⭐⭐⭐., ⭐⭐⭐', ⭐⭐⭐`

#8089 all: smoother notifications reverting (fixes #7769)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/repository/NotificationRepository.kt
  app/src/main/java/org/ole/planet/myplanet/repository/NotificationRepositoryImpl.kt
  app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardActivity.kt
  app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardViewModel.kt
  app/src/main/java/org/ole/planet/myplanet/ui/dashboard/notification/AdapterNotification.kt
  app/src/main/java/org/ole/planet/myplanet/ui/dashboard/notification/NotificationsFragment.kt
  app/src/main/java/org/ole/planet/myplanet/utilities/NotificationUtils.kt
  app/src/main/res/layout/fragment_notifications.xml
Labels: priority, ready to merge, peer review, experiment, ⭐⭐⭐'

#8236 mylife: less dictionaries drawable is more (fixes #8273)
  app/build.gradle
  app/src/main/res/drawable/ic_dictionaries.png
Labels: triage, less, ready to merge, codex, ⭐⭐⭐.

#8237 teams: less task pending drawable is more (fixes #8274)
  app/build.gradle
  app/src/main/res/drawable/task_pending.png
Labels: triage, less, ready to merge, codex, ⭐⭐⭐.

#8240 all: less realm pool manager is more (fixes #8277)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/service/sync/RealmConnectionPool.kt
Labels: triage, less, ready to merge, codex, ⭐⭐⭐.

#8241 teams: less members methods is more (fixes #8278)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/team/teamMember/MembersFragment.kt
Labels: triage, less, ready to merge, codex, ⭐⭐⭐.

#8242 all: less guest user dialog is more (fixes #8279)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/sync/DashboardElementActivity.kt
Labels: triage, less, ready to merge, codex, ⭐⭐⭐.

#8243 mylife: less my personals refresh is more (fixes #8280)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/myPersonals/MyPersonalsFragment.kt
Labels: triage, less, ready to merge, codex, ⭐⭐⭐.

#8032 teams: smoother joining (fixes #8030)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/model/RealmMyTeam.kt
  app/src/main/java/org/ole/planet/myplanet/repository/TeamRepository.kt
  app/src/main/java/org/ole/planet/myplanet/repository/TeamRepositoryImpl.kt
  app/src/main/java/org/ole/planet/myplanet/ui/team/AdapterTeamList.kt
  app/src/main/java/org/ole/planet/myplanet/ui/team/TeamDetailFragment.kt
Labels: priority, ready to merge, peer review, codex, ⭐⭐⭐., ⭐⭐⭐', ⭐⭐⭐`

#8245 teams: smoother voices reply images showing (fixes #8103)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/base/BaseNewsFragment.kt
  app/src/main/java/org/ole/planet/myplanet/model/RealmNews.kt
  app/src/main/java/org/ole/planet/myplanet/ui/news/AdapterNews.kt
  app/src/main/java/org/ole/planet/myplanet/ui/news/NewsActions.kt
  app/src/main/java/org/ole/planet/myplanet/ui/news/ReplyActivity.kt
Labels: priority, ready to merge, ⭐⭐⭐', ⭐⭐⭐`

#8248 courses: smoother navigating (fixes #7839)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/courses/TakeCourseFragment.kt
Labels: priority, ready to merge, ⭐⭐⭐', ⭐⭐⭐`

#8252 resources: smoother creation user profile handling (fixes #8281)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/resources/AddResourceFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/viewer/PDFReaderActivity.kt
Labels: small change, ready to merge, codex, ⭐⭐., ⭐⭐', ⭐⭐⭐`

#8262 all: less realm instances is more (fixes #8286)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/dashboard/BaseDashboardFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/enterprises/ReportsFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/team/TeamDetailFragment.kt
Labels: small change, ready to merge, codex, ⭐⭐⭐., ⭐⭐⭐', ⭐⭐⭐`

#8263 all: smoother submission repository creating (fixes #8287)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/repository/SubmissionRepositoryImpl.kt
Labels: small change, ready to merge, codex, ⭐⭐⭐., ⭐⭐⭐', ⭐⭐⭐`
