Repository open-learning-exchange/myplanet, pull requests merged in 2025-07, with the labels that each got.

#6126 teams: smoother translations (fixes #6123)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/dashboard/notification/NotificationsFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/exam/UserInformationFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/team/TeamDetailFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/team/TeamPage.kt
  app/src/main/java/org/ole/planet/myplanet/ui/team/TeamPagerAdapter.kt
Labels: ready to merge

#6129 teams: smoother survey canceling (fixes #6125)
  app/build.gradle
  app/src/main/res/layout/fragment_user_information.xml
  app/src/main/res/values-es/strings.xml
Labels: peer review

#6147 sync: smoother server check (fixes #6145)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/MainApplication.kt
  app/src/main/java/org/ole/planet/myplanet/datamanager/Service.kt
Labels: peer review

#6152 login: smoother register autologin (fixes #6151)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/sync/LoginActivity.kt
  app/src/main/java/org/ole/planet/myplanet/ui/sync/ProcessUserDataActivity.kt
  app/src/main/java/org/ole/planet/myplanet/ui/sync/SyncActivity.kt
  app/src/main/java/org/ole/planet/myplanet/ui/userprofile/BecomeMemberActivity.kt
Labels: peer review

#6149 teams: smoother survey single choice other (fixes #6068)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/exam/TakeExamFragment.kt
Labels: peer review

#6132 teams: smoother `AdapterNews.kt` complexity (fixes #6139)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/news/AdapterNews.kt
  app/src/main/java/org/ole/planet/myplanet/ui/news/NewsImageLoader.kt
  app/src/main/java/org/ole/planet/myplanet/ui/news/NewsLabelManager.kt
Labels: ready to merge, codex

#6137 all: smoother `CsvUtils.kt` (fixes #6157)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/model/RealmAchievement.kt
  app/src/main/java/org/ole/planet/myplanet/model/RealmCertification.kt
  app/src/main/java/org/ole/planet/myplanet/model/RealmChatHistory.kt
  app/src/main/java/org/ole/planet/myplanet/model/RealmCourseProgress.kt
  app/src/main/java/org/ole/planet/myplanet/model/RealmFeedback.kt
  app/src/main/java/org/ole/planet/myplanet/model/RealmMeetup.kt
  app/src/main/java/org/ole/planet/myplanet/model/RealmMyCourse.kt
  app/src/main/java/org/ole/planet/myplanet/model/RealmMyHealthPojo.kt
  app/src/main/java/org/ole/planet/myplanet/model/RealmMyLibrary.kt
  app/src/main/java/org/ole/planet/myplanet/model/RealmMyTeam.kt
  app/src/main/java/org/ole/planet/myplanet/model/RealmNews.kt
  app/src/main/java/org/ole/planet/myplanet/model/RealmOfflineActivity.kt
  app/src/main/java/org/ole/planet/myplanet/model/RealmRating.kt
  app/src/main/java/org/ole/planet/myplanet/model/RealmStepExam.kt
  app/src/main/java/org/ole/planet/myplanet/model/RealmSubmission.kt
  app/src/main/java/org/ole/planet/myplanet/model/RealmTag.kt
  app/src/main/java/org/ole/planet/myplanet/model/RealmTeamLog.kt
  app/src/main/java/org/ole/planet/myplanet/model/RealmTeamTask.kt
  app/src/main/java/org/ole/planet/myplanet/model/RealmUserModel.kt
  app/src/main/java/org/ole/planet/myplanet/utilities/CsvUtils.kt
Labels: peer review, codex

#6131 all: smoother `FileUtils.kt` complexity (fixes #6052)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/utilities/FileUtils.kt
Labels: priority, ready to merge, codex

#6166 teams: smoother survey single choice other (fixes #6067)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/exam/ExamSubmissionUtils.kt
Labels: peer review

#6104 sync: smoother beta separate fetch (fixes #6179)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/service/SyncManager.kt
  app/src/main/java/org/ole/planet/myplanet/ui/chat/ChatDetailFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/chat/ChatHistoryListFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/courses/AdapterCourses.kt
  app/src/main/java/org/ole/planet/myplanet/ui/courses/CoursesFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/feedback/FeedbackListFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/myhealth/MyHealthFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/resources/AdapterResource.kt
  app/src/main/java/org/ole/planet/myplanet/ui/resources/ResourcesFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/survey/SurveyFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/team/TeamDetailFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/userprofile/AchievementFragment.kt
  app/src/main/java/org/ole/planet/myplanet/utilities/ServerUrlMapper.kt
  app/src/main/java/org/ole/planet/myplanet/utilities/SharedPrefManager.kt
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-ne/strings.xml
  app/src/main/res/values-so/strings.xml
  app/src/main/res/values/strings.xml
Labels: peer review

#6172 sync: smoother resource transaction (fixes #6170)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/service/SyncManager.kt
Labels: priority, ready to merge

#6168 mylife: smoother myhealth examination canceling (fixes #6114)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/myhealth/AddExaminationActivity.kt
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-ne/strings.xml
  app/src/main/res/values-so/strings.xml
  app/src/main/res/values/strings.xml
Labels: peer review

#6180 teams: smoother survey submissions (fixes #6175)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/exam/UserInformationFragment.kt
  app/src/main/res/layout-w600dp/fragment_team_detail.xml
  app/src/main/res/layout/fragment_team_detail.xml
Labels: ready to merge

#6191 all: smoother `SharedPrefManager.kt` complexity (fixes #6198)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/utilities/SharedPrefManager.kt
Labels: ready to merge, peer review, codex

#6164 actions: smoother gradle configuration (fixes #6195)
  .github/workflows/android-build.yml
  .github/workflows/android-release.yml
  app/build.gradle
  gradle.properties
Labels: peer review, codex

#6206 actions: smoother workflows (fixes #6202)
  .github/workflows/android-build.yml
  .github/workflows/android-release.yml
  app/build.gradle
  app/src/lite/AndroidManifest.xml
  app/src/main/java/org/ole/planet/myplanet/base/BaseContainerFragment.kt
  app/src/main/java/org/ole/planet/myplanet/base/BaseContainerFragment.kt.lite
  app/src/main/java/org/ole/planet/myplanet/base/PermissionActivity.kt
  app/src/main/java/org/ole/planet/myplanet/base/PermissionActivity.kt.lite
  app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardActivity.kt
  app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardActivity.kt.lite
Labels: priority, peer review, codex

#6210 teans: smoother `AdapterNews.kt` complexity (fixes #6220)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/news/AdapterNews.kt
  app/src/main/java/org/ole/planet/myplanet/ui/news/NewsActions.kt
Labels: peer review, codex

#6212 chat: smoother `ChatDetailFragment.kt` complexity (fixes #6221)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/chat/ChatDetailFragment.kt
Labels: peer review, codex

#6216 actions: smoother gradle setup (fixes #6222)
  .github/workflows/android-build.yml
  .github/workflows/android-release.yml
  app/build.gradle
Labels: codex

#6165 teams: smoother voices list sharing button (fixes #6154)
  app/build.gradle
  app/src/main/res/layout/row_news.xml
Labels: ready to merge

#6209 all: less warnings is more (fixes #6235)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/base/BaseRecyclerFragment.kt
  app/src/main/java/org/ole/planet/myplanet/datamanager/FileUploadService.kt
  app/src/main/java/org/ole/planet/myplanet/model/RealmSubmission.kt
  app/src/main/java/org/ole/planet/myplanet/service/UploadManager.kt
  app/src/main/java/org/ole/planet/myplanet/ui/chat/ChatDetailFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/chat/ChatHistoryListAdapter.kt
  app/src/main/java/org/ole/planet/myplanet/ui/chat/ChatHistoryListFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/courses/CoursesFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/dashboard/SurveyAdapter.kt
  app/src/main/java/org/ole/planet/myplanet/ui/exam/UserInformationFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/feedback/FeedbackListFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/myhealth/MyHealthFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/resources/ResourcesFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/survey/SurveyFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/sync/ProcessUserDataActivity.kt
  app/src/main/java/org/ole/planet/myplanet/ui/team/TeamDetailFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/team/TeamPagerAdapter.kt
  app/src/main/java/org/ole/planet/myplanet/ui/team/teamMember/AdapterJoinedMember.kt
  app/src/main/java/org/ole/planet/myplanet/ui/userprofile/AchievementFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/userprofile/BecomeMemberActivity.kt
  app/src/main/java/org/ole/planet/myplanet/utilities/Markdown.kt
  app/src/main/java/org/ole/planet/myplanet/utilities/NetworkUtils.kt
Labels: peer review, codex

#6224 all: smoother `Service.kt` version checking (fixes #6251)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/datamanager/Service.kt
Labels: peer review, codex

#6225 login: smoother `AuthHelper.kt` (fixes #6252)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/sync/GuestLoginExtensions.kt
  app/src/main/java/org/ole/planet/myplanet/ui/sync/LoginActivity.kt
  app/src/main/java/org/ole/planet/myplanet/ui/userprofile/BecomeMemberActivity.kt
  app/src/main/java/org/ole/planet/myplanet/utilities/AuthHelper.kt
Labels: priority, peer review, codex

#6211 courses: smoother rating and markdown images (fixes #6253)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/base/BaseContainerFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/community/ServicesFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/courses/AdapterCourses.kt
  app/src/main/java/org/ole/planet/myplanet/ui/courses/CourseDetailFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/courses/CourseStepFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/news/AdapterNews.kt
  app/src/main/java/org/ole/planet/myplanet/ui/resources/AdapterResource.kt
  app/src/main/java/org/ole/planet/myplanet/utilities/CourseRatingUtils.kt
  app/src/main/java/org/ole/planet/myplanet/utilities/Markdown.kt
Labels: peer review, codex

#6248 dashboard: smoother guest registration (fixes #6171)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/model/RealmUserModel.kt
Labels: ready to merge

#6153 teams: smoother voices labels deletion (fixes #6150)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/news/AdapterNews.kt
  app/src/main/java/org/ole/planet/myplanet/ui/news/NewsLabelManager.kt
  app/src/main/java/org/ole/planet/myplanet/ui/team/MyTeamsDetailFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/team/teamDiscussion/DiscussionListFragment.kt
Labels: priority, peer review

#6264 all: smoother `TimeUtils.kt` (fixes #6288)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/utilities/TimeUtils.kt
Labels: priority, peer review, codex

#6128 resources: smoother audio view (fixes #6116)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/viewer/AudioPlayerActivity.kt
  app/src/main/java/org/ole/planet/myplanet/utilities/IntentUtils.kt
  app/src/main/res/drawable/musical_note.png
  app/src/main/res/drawable/roundcorner.xml
  app/src/main/res/drawable/rounded_corner_bg.xml
  app/src/main/res/layout/activity_audio_player.xml
  app/src/main/res/layout/custom_exo_player.xml
Labels: ready to merge, peer review

#6227 teams: smoother voices images (fixes #6302)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/news/AdapterNews.kt
  app/src/main/java/org/ole/planet/myplanet/ui/news/NewsImageLoader.kt
Labels: ready to merge, peer review, codex

#6257 teams: smoother view init (fixes #6256)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/team/TeamDetailFragment.kt
Labels: ready to merge

#6287 login: smoother register guests (fixes #6258)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/model/RealmUserModel.kt
  app/src/main/java/org/ole/planet/myplanet/ui/sync/LoginActivity.kt
  app/src/main/java/org/ole/planet/myplanet/ui/userprofile/BecomeMemberActivity.kt
Labels: ready to merge

#6261 all: bump `SDK` to 35 (fixes #6003)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/SettingActivity.kt
  app/src/main/java/org/ole/planet/myplanet/ui/courses/CourseProgressActivity.kt
  app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardActivity.kt
  app/src/main/java/org/ole/planet/myplanet/ui/dictionary/DictionaryActivity.kt
  app/src/main/java/org/ole/planet/myplanet/ui/feedback/FeedbackDetailActivity.kt
  app/src/main/java/org/ole/planet/myplanet/ui/map/OfflineMapActivity.kt
  app/src/main/java/org/ole/planet/myplanet/ui/myhealth/AddExaminationActivity.kt
  app/src/main/java/org/ole/planet/myplanet/ui/myhealth/AddMyHealthActivity.kt
  app/src/main/java/org/ole/planet/myplanet/ui/news/NewsDetailActivity.kt
  app/src/main/java/org/ole/planet/myplanet/ui/news/ReplyActivity.kt
  app/src/main/java/org/ole/planet/myplanet/ui/onBoarding/OnBoardingActivity.kt
  app/src/main/java/org/ole/planet/myplanet/ui/resources/AddResourceActivity.kt
  app/src/main/java/org/ole/planet/myplanet/ui/sync/LoginActivity.kt
  app/src/main/java/org/ole/planet/myplanet/ui/userprofile/BecomeMemberActivity.kt
  app/src/main/java/org/ole/planet/myplanet/ui/viewer/AudioPlayerActivity.kt
  app/src/main/java/org/ole/planet/myplanet/ui/viewer/CSVViewerActivity.kt
  app/src/main/java/org/ole/planet/myplanet/ui/viewer/ImageViewerActivity.kt
  app/src/main/java/org/ole/planet/myplanet/ui/viewer/MarkdownViewerActivity.kt
  app/src/main/java/org/ole/planet/myplanet/ui/viewer/PDFReaderActivity.kt
  app/src/main/java/org/ole/planet/myplanet/ui/viewer/TextFileViewerActivity.kt
  app/src/main/java/org/ole/planet/myplanet/ui/viewer/VideoPlayerActivity.kt
  app/src/main/java/org/ole/planet/myplanet/ui/viewer/WebViewActivity.kt
  app/src/main/java/org/ole/planet/myplanet/utilities/EdgeToEdgeUtil.kt
Labels: priority, ready to merge, peer review

#6293 all: less csv is more (fixes #6292)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/model/RealmAchievement.kt
  app/src/main/java/org/ole/planet/myplanet/model/RealmCertification.kt
  app/src/main/java/org/ole/planet/myplanet/model/RealmChatHistory.kt
  app/src/main/java/org/ole/planet/myplanet/model/RealmCourseProgress.kt
  app/src/main/java/org/ole/planet/myplanet/model/RealmFeedback.kt
  app/src/main/java/org/ole/planet/myplanet/model/RealmMeetup.kt
  app/src/main/java/org/ole/planet/myplanet/model/RealmMyCourse.kt
  app/src/main/java/org/ole/planet/myplanet/model/RealmMyHealthPojo.kt
  app/src/main/java/org/ole/planet/myplanet/model/RealmMyLibrary.kt
  app/src/main/java/org/ole/planet/myplanet/model/RealmMyTeam.kt
  app/src/main/java/org/ole/planet/myplanet/model/RealmNews.kt
  app/src/main/java/org/ole/planet/myplanet/model/RealmOfflineActivity.kt
  app/src/main/java/org/ole/planet/myplanet/model/RealmRating.kt
  app/src/main/java/org/ole/planet/myplanet/model/RealmStepExam.kt
  app/src/main/java/org/ole/planet/myplanet/model/RealmSubmission.kt
  app/src/main/java/org/ole/planet/myplanet/model/RealmTag.kt
  app/src/main/java/org/ole/planet/myplanet/model/RealmTeamLog.kt
  app/src/main/java/org/ole/planet/myplanet/model/RealmTeamTask.kt
  app/src/main/java/org/ole/planet/myplanet/model/RealmUserModel.kt
  app/src/main/java/org/ole/planet/myplanet/service/TransactionSyncManager.kt
  app/src/main/java/org/ole/planet/myplanet/ui/SettingActivity.kt
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-ne/strings.xml
  app/src/main/res/values-so/strings.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/pref.xml
Labels: priority, peer review

#6295 sync: smoother `DownloadUtils.kt` notifications (fixes #6320)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/datamanager/DownloadWorker.kt
  app/src/main/java/org/ole/planet/myplanet/datamanager/MyDownloadService.kt
  app/src/main/java/org/ole/planet/myplanet/utilities/DownloadUtils.kt
Labels: peer review, codex

#6272 all: smoother `NetworkResult.kt` handling (fixes #6321)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/datamanager/ApiClient.kt
  app/src/main/java/org/ole/planet/myplanet/datamanager/NetworkResult.kt
  app/src/main/java/org/ole/planet/myplanet/datamanager/Service.kt
Labels: peer review, codex

#6318 courses: smoother voices labels (fixes #6276)
  app/build.gradle
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-ne/strings.xml
  app/src/main/res/values-so/strings.xml
  app/src/main/res/values/strings.xml
Labels: ready to merge

#6316 chat: smoother auto-scrolling (fixes #6285)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/chat/ChatAdapter.kt
Labels: ready to merge

#6314 all: smoother `MainApplication.kt` (fixes #6340)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/MainApplication.kt
Labels: priority, ready to merge, peer review, codex, daily review challange

#6311 dashboard: smoother `BellDashboardFragment.kt` surveys (fixes #6338)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/dashboard/BellDashboardFragment.kt
Labels: priority, ready to merge, peer review, codex, daily review challange

#6351 teams: smoother survey sorting default (fixes #6273)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/survey/AdapterSurvey.kt
Labels: peer review

#6354 login: smoother `ThemeManager.kt` (fixes #6372)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/base/BaseNewsFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/SettingActivity.kt
  app/src/main/java/org/ole/planet/myplanet/ui/sync/LoginActivity.kt
  app/src/main/java/org/ole/planet/myplanet/utilities/ThemeManager.kt
Labels: peer review, codex

#6358 all: smoother `ApiClient.kt` caching (fixes #6373)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/datamanager/ApiClient.kt
Labels: codex, lazy init

#6380 all: smoother retry logic (fixes #6391)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/datamanager/ApiClient.kt
  app/src/main/java/org/ole/planet/myplanet/datamanager/ApiInterface.kt
  app/src/main/java/org/ole/planet/myplanet/datamanager/Service.kt
Labels: ready to merge, codex

#6381 all: smoother realm instance loops (fixes #6392)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/service/UserProfileDbHandler.kt
  app/src/main/java/org/ole/planet/myplanet/ui/sync/SyncActivity.kt
Labels: priority, ready to merge, codex

#6366 sync: smoother dialog (fixes #6365)
  app/build.gradle
  app/src/main/res/layout/dialog_server_url_.xml
Labels: priority, ready to merge

#6387 all: smoother `timeUtils.kt` date format (fixes #6386)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/utilities/TimeUtils.kt
Labels: ready to merge

#6389 all: smoother notifications date parsing (fixes #6385)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/utilities/NotificationUtil.kt
  app/src/main/java/org/ole/planet/myplanet/utilities/TimeUtils.kt
Labels: ready to merge

#6378 all: smoother app with dependency injection (fixes #6395)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/MainApplication.kt
  app/src/main/java/org/ole/planet/myplanet/base/BaseContainerFragment.kt
  app/src/main/java/org/ole/planet/myplanet/base/BaseResourceFragment.kt
  app/src/main/java/org/ole/planet/myplanet/di/DatabaseModule.kt
  app/src/main/java/org/ole/planet/myplanet/di/NetworkModule.kt
  app/src/main/java/org/ole/planet/myplanet/di/RepositoryModule.kt
  app/src/main/java/org/ole/planet/myplanet/di/ServiceModule.kt
  app/src/main/java/org/ole/planet/myplanet/di/SharedPreferencesModule.kt
  app/src/main/java/org/ole/planet/myplanet/service/AutoSyncWorker.kt
  app/src/main/java/org/ole/planet/myplanet/service/SyncManager.kt
  app/src/main/java/org/ole/planet/myplanet/service/UploadManager.kt
  app/src/main/java/org/ole/planet/myplanet/service/UserProfileDbHandler.kt
  app/src/main/java/org/ole/planet/myplanet/ui/SettingActivity.kt
  app/src/main/java/org/ole/planet/myplanet/ui/chat/ChatHistoryListFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/community/CommunityFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/courses/AdapterCourses.kt
  app/src/main/java/org/ole/planet/myplanet/ui/courses/CoursesFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardActivity.kt
  app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardViewModel.kt
  app/src/main/java/org/ole/planet/myplanet/ui/feedback/FeedbackListFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/myPersonals/MyPersonalsFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/myhealth/MyHealthFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/news/AdapterNews.kt
  app/src/main/java/org/ole/planet/myplanet/ui/news/NewsFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/news/ReplyActivity.kt
  app/src/main/java/org/ole/planet/myplanet/ui/resources/ResourcesFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/survey/SurveyFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/sync/ProcessUserDataActivity.kt
  app/src/main/java/org/ole/planet/myplanet/ui/sync/SyncActivity.kt
  app/src/main/java/org/ole/planet/myplanet/ui/team/MyTeamsDetailFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/team/TeamDetailFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/team/teamDiscussion/DiscussionListFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/userprofile/AchievementFragment.kt
  app/src/main/java/org/ole/planet/myplanet/utilities/SyncTimeLogger.kt
Labels: priority, peer review

#6407 sync: smoother realm instances (fixes #6406)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/datamanager/DatabaseService.kt
  app/src/main/java/org/ole/planet/myplanet/datamanager/Service.kt
  app/src/main/java/org/ole/planet/myplanet/service/SyncManager.kt
  app/src/main/java/org/ole/planet/myplanet/ui/enterprises/AdapterReports.kt
  app/src/main/java/org/ole/planet/myplanet/ui/sync/GuestLoginExtensions.kt
  app/src/main/java/org/ole/planet/myplanet/ui/sync/LoginActivity.kt
  app/src/main/java/org/ole/planet/myplanet/ui/sync/SyncActivity.kt
Labels: ready to merge, peer review

#6396 all: smoother fragments `DatabaseService` injection (fixes #6416)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/base/BaseRecyclerFragment.kt
  app/src/main/java/org/ole/planet/myplanet/base/BaseResourceFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/chat/ChatDetailFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/chat/ChatHistoryListFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/community/AddLinkFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/community/CommunityFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/community/ServicesFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/courses/CourseDetailFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/courses/CourseStepFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/courses/MyProgressFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/courses/TakeCourseFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/dashboard/BaseDashboardFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/dashboard/MyActivityFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/dashboard/notification/NotificationsFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/enterprises/FinanceFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/enterprises/ReportsFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/exam/BaseExamFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/exam/UserInformationFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/feedback/FeedbackFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/feedback/FeedbackListFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/myPersonals/MyPersonalsFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/myhealth/MyHealthFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/mymeetup/MyMeetupDetailFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/news/NewsFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/rating/RatingFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/resources/CollectionsFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/resources/ResourceDetailFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/submission/MySubmissionFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/survey/SendSurveyFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/team/BaseTeamFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/team/MyTeamsDetailFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/team/TeamDetailFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/team/TeamFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/userprofile/EditAchievementFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/userprofile/UserDetailFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/userprofile/UserProfileFragment.kt
Labels: ready to merge, codex

#6397 sync: smoother `SyncManager.kt` injections (fixes #6417)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/service/AutoSyncWorker.kt
  app/src/main/java/org/ole/planet/myplanet/service/SyncManager.kt
Labels: ready to merge, codex

#6410 courses: smoother progress darkmode (fixes #6279)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/courses/AdapterMyProgress.kt
  app/src/main/res/layout/item_progress.xml
  app/src/main/res/layout/row_my_progress.xml
Labels: ready to merge, peer review

#6411 mylife: smoother myhealth recording (fixes #6297)
  app/build.gradle
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-ne/strings.xml
  app/src/main/res/values-so/strings.xml
  app/src/main/res/values/strings.xml
Labels: ready to merge, peer review

#6413 teams: smoother joining (fixes #6350)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/team/teamMember/AdapterMemberRequest.kt
  app/src/main/java/org/ole/planet/myplanet/ui/team/teamMember/MembersFragment.kt
Labels: ready to merge, peer review

#6422 all: smoother `ApiInterfaceEntryPoint.kt` injection (fixes #6438)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/datamanager/DownloadWorker.kt
  app/src/main/java/org/ole/planet/myplanet/datamanager/Service.kt
  app/src/main/java/org/ole/planet/myplanet/di/ApiInterfaceEntryPoint.kt
  app/src/main/java/org/ole/planet/myplanet/di/ServiceModule.kt
  app/src/main/java/org/ole/planet/myplanet/service/SyncManager.kt
  app/src/main/java/org/ole/planet/myplanet/ui/chat/ChatApiHelper.kt
  app/src/main/java/org/ole/planet/myplanet/ui/chat/ChatDetailFragment.kt
Labels: ready to merge, codex

#6425 all: smoother activities injection (fixes #6441)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/courses/CourseProgressActivity.kt
  app/src/main/java/org/ole/planet/myplanet/ui/dictionary/DictionaryActivity.kt
  app/src/main/java/org/ole/planet/myplanet/ui/feedback/FeedbackDetailActivity.kt
  app/src/main/java/org/ole/planet/myplanet/ui/myhealth/AddExaminationActivity.kt
  app/src/main/java/org/ole/planet/myplanet/ui/myhealth/AddMyHealthActivity.kt
  app/src/main/java/org/ole/planet/myplanet/ui/news/NewsDetailActivity.kt
  app/src/main/java/org/ole/planet/myplanet/ui/resources/AddResourceActivity.kt
  app/src/main/java/org/ole/planet/myplanet/ui/userprofile/BecomeMemberActivity.kt
  app/src/main/java/org/ole/planet/myplanet/ui/viewer/PDFReaderActivity.kt
Labels: peer review, experiment, codex

#6435 dashboard: smoother profile birthday format (fixes #6412)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/userprofile/UserProfileFragment.kt
Labels: ready to merge, peer review

#6448 sync: smoother `UploadToShelfService.kt` injection (fixes #6472))
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/datamanager/Service.kt
  app/src/main/java/org/ole/planet/myplanet/di/ServiceModule.kt
  app/src/main/java/org/ole/planet/myplanet/service/UploadToShelfService.kt
Labels: ready to merge, peer review, codex

#6475 fix merge conflct
  app/src/main/java/org/ole/planet/myplanet/ui/sync/SyncActivity.kt
Labels: codex

#6471 teams: smoother voices member details (fixes #6455)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/news/AdapterNews.kt
Labels: priority, ready to merge, peer review

#6480 community: smoother services (fixes #6479)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/community/ServicesFragment.kt
Labels: ready to merge, peer review

#6469 mylife: smoother myhealth examination addition (fixes #6414)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/myhealth/AddExaminationActivity.kt
Labels: ready to merge, peer review, codex

#6467 sync: smoother `MyDownloadService.kt` closing (fixes #6437)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/datamanager/MyDownloadService.kt
Labels: ready to merge, peer review, codex

#6492 chat: smoother details (fixes #6461)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/chat/ChatDetailFragment.kt
Labels: ready to merge

#6512 all: smoother notifications badge update (fixes #6510)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardActivity.kt
  app/src/main/java/org/ole/planet/myplanet/ui/dashboard/notification/AdapterNotification.kt
  app/src/main/java/org/ole/planet/myplanet/ui/dashboard/notification/NotificationsFragment.kt
  app/src/main/java/org/ole/planet/myplanet/utilities/NotificationUtil.kt
Labels: priority, peer review

#6542 actions: less dependencies is more (fixes #6543)
  app/build.gradle
Labels: codex
