Repository open-learning-exchange/myplanet, pull requests merged in 2025-02, with the labels that each got.

#5151 enterprises: smoother reports (fixes #5143)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/base/BaseRecyclerFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/enterprises/ReportsFragment.kt
  app/src/main/res/layout/fragment_reports.xml
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-ne/strings.xml
  app/src/main/res/values-so/strings.xml
  app/src/main/res/values/strings.xml
Labels: ready to merge, peer review

#5157 community: smoother leaders profile (fixes #5117)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/community/AdapterLeader.kt
Labels: ready to merge, peer review

#5186 login: smoother register dark mode (fixes #5185)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/userprofile/BecomeMemberActivity.kt
Labels: ready to merge

#5196 login: smoother translations (fixes #5193)
  app/build.gradle
  app/src/main/res/values-es/strings.xml
Labels: ready to merge

#5197 courses: smoother mycourses navigation highlight (fixes #5031)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/courses/CoursesFragment.kt
Labels: ready to merge

#5202 resources: smoother creation meta info (fixes #5170)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/resources/AddResourceActivity.kt
Labels: ready to merge

#5204 teams: smoother members detail (fixes #5154)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/model/RealmTeamLog.kt
  app/src/main/java/org/ole/planet/myplanet/ui/team/teamMember/AdapterJoinedMember.kt
  app/src/main/java/org/ole/planet/myplanet/ui/team/teamMember/MembersFragment.kt
  app/src/main/res/layout/row_joined_user.xml
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-ne/strings.xml
  app/src/main/res/values-so/strings.xml
  app/src/main/res/values/strings.xml
Labels: ready to merge, peer review

#5205 mylife: smoother myhealth examination dark mode (fixes #5051)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/myhealth/AdapterHealthExamination.kt
  app/src/main/res/layout/alert_examination.xml
Labels: ready to merge

#5201 all: smoother navigation icons (fixes #5163)
  app/build.gradle
  app/src/main/res/drawable/baseline_feedback_24.xml
  app/src/main/res/drawable/baseline_forum_24.xml
  app/src/main/res/menu/menu_bell_dashboard.xml
Labels: ready to merge

#5206 teams: smoother voices comment dialog (fixes #5173)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/news/AdapterNews.kt
  app/src/main/res/values-night/styles.xml
  app/src/main/res/values/styles.xml
Labels: ready to merge

#5211 sync: smoother submissions (fixes #5210)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/model/RealmSubmission.kt
Labels: ready to merge

#5213 mylife: smoother myhealth record edit (fixes #5212)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/myhealth/AddExaminationActivity.kt
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-ne/strings.xml
  app/src/main/res/values-so/strings.xml
  app/src/main/res/values/strings.xml
Labels: ready to merge

#5192 chat: smoother providers dynamically (fixes #5191)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/datamanager/Service.kt
  app/src/main/java/org/ole/planet/myplanet/ui/chat/AiProviderModel.kt
  app/src/main/java/org/ole/planet/myplanet/ui/chat/ChatDetailFragment.kt
  app/src/main/java/org/ole/planet/myplanet/utilities/Utilities.kt
  app/src/main/res/layout/fragment_chat_detail.xml
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-ne/strings.xml
  app/src/main/res/values-so/strings.xml
  app/src/main/res/values/strings.xml
Labels: ready to merge

#5221 teams: smoother surveys list (fixes #5218)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/survey/SurveyFragment.kt
Labels: ready to merge

#5228 dashboard: smoother badges (fixes #5219)
  app/build.gradle
  app/src/main/res/layout/card_profile_bell.xml
Labels: peer review

#5231 login: smoother register dark mode (fixes #5198)
  app/build.gradle
  app/src/main/res/layout/activity_become_member.xml
Labels: ready to merge

#5232 login: smoother settings pin (fixes #5216)
  app/build.gradle
  app/src/main/res/layout/dialog_server_url_.xml
Labels: ready to merge

#5224 teams: smoother survey adoption (fixes #5220)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/callback/SurveyAdoptListener.kt
  app/src/main/java/org/ole/planet/myplanet/model/RealmStepExam.kt
  app/src/main/java/org/ole/planet/myplanet/model/RealmSubmission.kt
  app/src/main/java/org/ole/planet/myplanet/service/AutoSyncWorker.kt
  app/src/main/java/org/ole/planet/myplanet/service/UploadManager.kt
  app/src/main/java/org/ole/planet/myplanet/ui/survey/AdapterSurvey.kt
  app/src/main/java/org/ole/planet/myplanet/ui/survey/SurveyFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/sync/ProcessUserDataActivity.kt
  app/src/main/res/layout/fragment_survey.xml
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-ne/strings.xml
  app/src/main/res/values-so/strings.xml
  app/src/main/res/values/strings.xml
Labels: peer review

#5230 resources: smoother search (fixes #5226)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/base/BaseRecyclerFragment.kt
  app/src/main/java/org/ole/planet/myplanet/model/RealmMyCourse.kt
  app/src/main/java/org/ole/planet/myplanet/ui/courses/AdapterCourses.kt
Labels: ready to merge

#5245 login: smoother profile visits (fixes #5244)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/service/UserProfileDbHandler.kt
Labels: peer review

#5247 courses: smoother joining and leaving (fixes #5246)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/courses/TakeCourseFragment.kt
Labels: peer review

#5207 login: smoother voices bottom drawer (fixes #5169)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/community/HomeCommunityDialogFragment.kt
  app/src/main/res/layout/fragment_news.xml
Labels: ready to merge

#5233 dashboard: smoother profile levels (fixes #5223)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/userprofile/UserProfileFragment.kt
Labels: ready to merge

#5252 resources: smoother mylibrary language (fixes #5250)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/resources/ResourcesFragment.kt
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-ne/strings.xml
  app/src/main/res/values-so/strings.xml
  app/src/main/res/values/strings.xml
Labels: ready to merge

#5236 sync: smoother config fast beta (fixes #5234)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/datamanager/ManagerSync.kt
  app/src/main/java/org/ole/planet/myplanet/model/RealmSubmission.kt
  app/src/main/java/org/ole/planet/myplanet/model/RealmUserModel.kt
  app/src/main/java/org/ole/planet/myplanet/service/SyncManager.kt
  app/src/main/java/org/ole/planet/myplanet/ui/sync/SyncActivity.kt
  app/src/main/res/layout/dialog_server_url_.xml
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-ne/strings.xml
  app/src/main/res/values-so/strings.xml
  app/src/main/res/values/strings.xml
Labels: ready to merge, peer review

#5159 login: smoother clearing dialog (fixes #5090)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/sync/SyncActivity.kt
Labels: ready to merge, peer review

#5215 resourses: smoother mylibrary adding dialog (fixes #5174)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/resources/ResourcesFragment.kt
Labels: ready to merge, peer review

#5249 teams: smoother survey search (fixes #5217)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/survey/AdapterSurvey.kt
  app/src/main/java/org/ole/planet/myplanet/ui/survey/SurveyFragment.kt
  app/src/main/res/layout/fragment_survey.xml
Labels: ready to merge, peer review

#5260 chat: smoother search (fixes #5258)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/chat/ChatHistoryListAdapter.kt
  app/src/main/java/org/ole/planet/myplanet/ui/chat/ChatHistoryListFragment.kt
Labels: ready to merge

#5255 dashboard: smoother avatar server check (fixes #5254)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/dashboard/BellDashboardFragment.kt
Labels: ready to merge, peer review

#5257 sync: smoother cloudcommunity check (fixes #5256)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/datamanager/Service.kt
Labels: ready to merge, peer review

#5251 chat: smoother share dark mode (fixes #5248)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/news/ExpandableListAdapter.kt
  app/src/main/res/layout/chat_share_dialog.xml
  app/src/main/res/layout/expandable_list_group.xml
Labels: ready to merge

#5284 teams: smoother chat share dark mode (fixes #5281)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/chat/ChatHistoryListAdapter.kt
  app/src/main/res/layout/expandable_list_grand_child_item.xml
  app/src/main/res/layout/grand_child_recyclerview_dialog.xml
Labels: ready to merge

#5214 courses: smoother mycourses dialog (fixes #5172)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/courses/AdapterCourses.kt
  app/src/main/java/org/ole/planet/myplanet/ui/courses/CoursesFragment.kt
Labels: ready to merge

#5286 courses: smoother mycourses progress dark mode (fixes #5285)
  app/build.gradle
  app/src/main/res/layout/row_my_progress_grid.xml
Labels: ready to merge

#5283 mylife: smoother achievements resources dark mode (fixes #5279)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/userprofile/EditAchievementFragment.kt
Labels: ready to merge

#5280 dashboard: smoother checks (fixes #5253)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/dashboard/BellDashboardFragment.kt
Labels: ready to merge

#5282 courses: smoother joining (fixes #5269)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/courses/TakeCourseFragment.kt
Labels: ready to merge

#5290 login: smoother welcome message (fixes #5275)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/sync/LoginActivity.kt
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-ne/strings.xml
  app/src/main/res/values-so/strings.xml
  app/src/main/res/values/strings.xml
Labels: ready to merge

#5289 dashboard: smoother profile image options (fixes #5288)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/model/RealmUserModel.kt
  app/src/main/java/org/ole/planet/myplanet/ui/userprofile/UserProfileFragment.kt
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-ne/strings.xml
  app/src/main/res/values-so/strings.xml
  app/src/main/res/values/strings.xml
Labels: ready to merge

#5294 mylife: smoother myhealth recording (fixes #5262)
  app/build.gradle
  app/src/main/res/layout/activity_add_examination.xml
Labels: ready to merge

#5295 mylife: smoother myachievements title edit (fixes #5267)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/userprofile/EditAchievementFragment.kt
  app/src/main/res/layout/fragment_edit_achievement.xml
Labels: ready to merge

#5299 teams: smoother selections (fixes #5298)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/service/UserProfileDbHandler.kt
Labels: peer review

#5301 mylife: smoother myachievements button translations (fixes #5266)
  app/build.gradle
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-ne/strings.xml
  app/src/main/res/values-so/strings.xml
  app/src/main/res/values/strings.xml
Labels: peer review

#5302 sync: smoother error handling (fixes #5300)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/MainApplication.kt
  app/src/main/java/org/ole/planet/myplanet/datamanager/MyDownloadService.kt
  app/src/main/java/org/ole/planet/myplanet/ui/sync/SyncActivity.kt
Labels: peer review

#5209 resources: smoother mylibrary experience (fixes #5208)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/resources/AddResourceActivity.kt
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-ne/strings.xml
  app/src/main/res/values-so/strings.xml
  app/src/main/res/values/strings.xml
Labels: ready to merge

#5308 sync: smoother realm threads (fixes #5307)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/datamanager/Service.kt
  app/src/main/java/org/ole/planet/myplanet/ui/sync/LoginActivity.kt
Labels: peer review

#5293 sync: smoother parallelization with coroutines (fixes #5313)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/service/SyncManager.kt
  app/src/main/java/org/ole/planet/myplanet/ui/sync/SyncActivity.kt
Labels: peer review

#5292 courses: smoother archive button (fixes #5276)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/courses/CoursesFragment.kt
Labels: ready to merge

#5305 mylife: smoother myhealth examination input validation (fixes #5264)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/myhealth/AddExaminationActivity.kt
  app/src/main/res/layout/activity_add_examination.xml
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-ne/strings.xml
  app/src/main/res/values-so/strings.xml
  app/src/main/res/values/strings.xml
Labels: ready to merge

#5306 all: smoother mypersonal toast notification (fixes #5270)
  app/build.gradle
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-ne/strings.xml
  app/src/main/res/values-so/strings.xml
  app/src/main/res/values/strings.xml
Labels: ready to merge, peer review

#5314 login: smoother settings dialog (fixes #5311)
  app/build.gradle
  app/src/main/res/layout/dialog_server_url_.xml
Labels: ready to merge

#5319 sync: smoother downloads execution (fixes #5318)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/datamanager/MyDownloadService.kt
Labels: ready to merge

#5330 login: smoother sync foreground stop (fixes #5328)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/sync/SyncActivity.kt
Labels: priority, peer review

#5331 resources: smoother navigation (fixes #5315)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/resources/ResourcesFragment.kt
Labels: peer review

#5309 all: smoother navigation language (fixes #5222)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/SettingActivity.kt
  app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardActivity.kt
  app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardActivity.kt.lite
  app/src/main/res/drawable/translate.png
  app/src/main/res/menu/menu_bell_dashboard.xml
  app/src/main/res/xml/pref.xml
Labels: peer review

#5339 courses: smoother mycourses shortcut (fixes #5337)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/courses/CoursesFragment.kt
Labels: peer review

#5341 courses: smoother mycourses buttons (fixes #5316)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/courses/CoursesFragment.kt
Labels: ready to merge

#5347 teams: smoother survey translations (fixes #5321)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/exam/BaseExamFragment.kt
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-ne/strings.xml
  app/src/main/res/values-so/strings.xml
  app/src/main/res/values/strings.xml
Labels: ready to merge

#5334 teams: smoother list (fixes #5333)
  app/build.gradle
  app/src/main/res/color/dropdown_background.xml
  app/src/main/res/color/dropdown_text_color.xml
  app/src/main/res/drawable/dropdown_item_divider.xml
  app/src/main/res/layout/custom_simple_list_item_1.xml
  app/src/main/res/values-night/colors.xml
  app/src/main/res/values/colors.xml
Labels: peer review

#5345 chat: smoother searching (fixes #5296)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/chat/ChatHistoryListAdapter.kt
  app/src/main/java/org/ole/planet/myplanet/ui/chat/ChatHistoryListFragment.kt
  app/src/main/res/layout/fragment_chat_history_list.xml
Labels: ready to merge

#5349 teams: smoother survey submissions (fixes #5348)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/model/RealmUserModel.kt
  app/src/main/java/org/ole/planet/myplanet/ui/dashboard/BaseDashboardFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/exam/BaseExamFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/exam/UserInformationFragment.kt
  app/src/main/res/layout/fragment_user_information.xml
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-ne/strings.xml
  app/src/main/res/values-so/strings.xml
  app/src/main/res/values/strings.xml
Labels: priority, ready to merge

#5364 chat: smoother history (fixes #5363)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/chat/ChatHistoryListFragment.kt
Labels: ready to merge

#5379 sync: smoother settings planet xela (fixes #5378)
  app/build.gradle
  gradle.properties
Labels: ready to merge

#5356 sync: smoother download foreground service (fixes #5355)
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/AndroidManifest.xml.lite
  app/src/main/java/org/ole/planet/myplanet/base/PermissionActivity.kt
  app/src/main/java/org/ole/planet/myplanet/base/PermissionActivity.kt.lite
  app/src/main/java/org/ole/planet/myplanet/datamanager/MyDownloadService.kt
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-ne/strings.xml
  app/src/main/res/values-so/strings.xml
  app/src/main/res/values/strings.xml
Labels: ready to merge, peer review

#5385 resources: less toast is more (fixes #5320)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/base/BaseResourceFragment.kt
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-ne/strings.xml
  app/src/main/res/values-so/strings.xml
  app/src/main/res/values/strings.xml
Labels: ready to merge
