Repository open-learning-exchange/myplanet, pull requests merged in 2025-09, with the labels that each got.

#7186 teams: smoother finance binding (fixes #7213)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/enterprises/FinanceFragment.kt
Labels: ready to merge, codex, ⭐⭐⭐., ⭐⭐⭐'

#7189 resources: smoother realtime diffing (fixes #7214)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/resources/RealtimeLibraryFragment.kt
Labels: ready to merge, codex, ⭐⭐⭐., ⭐⭐⭐'

#7216 all: smoother imports (fixes #7218)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/MainApplication.kt
  app/src/main/java/org/ole/planet/myplanet/base/BaseRealtimeFragment.kt
  app/src/main/java/org/ole/planet/myplanet/callback/RealtimeSyncListener.kt
  app/src/main/java/org/ole/planet/myplanet/datamanager/ConfigurationManager.kt
  app/src/main/java/org/ole/planet/myplanet/service/ImprovedSyncManager.kt
  app/src/main/java/org/ole/planet/myplanet/service/SyncManager.kt
  app/src/main/java/org/ole/planet/myplanet/service/sync/AdaptiveBatchProcessor.kt
  app/src/main/java/org/ole/planet/myplanet/service/sync/CircuitBreaker.kt
  app/src/main/java/org/ole/planet/myplanet/service/sync/OptimizedSyncStrategy.kt
  app/src/main/java/org/ole/planet/myplanet/service/sync/RealmConnectionPool.kt
  app/src/main/java/org/ole/planet/myplanet/service/sync/RealtimeSyncCoordinator.kt
  app/src/main/java/org/ole/planet/myplanet/ui/SettingActivity.kt
  app/src/main/java/org/ole/planet/myplanet/ui/chat/ChatHistoryListFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/courses/CoursesFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/feedback/FeedbackListFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/myhealth/MyHealthFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/news/AdapterNews.kt
  app/src/main/java/org/ole/planet/myplanet/ui/news/NewsDetailActivity.kt
  app/src/main/java/org/ole/planet/myplanet/ui/resources/RealtimeLibraryFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/resources/ResourcesFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/survey/SurveyFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/sync/SyncActivity.kt
  app/src/main/java/org/ole/planet/myplanet/ui/team/TeamDetailFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/userprofile/AchievementFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/viewer/VideoPlayerActivity.kt
  app/src/main/java/org/ole/planet/myplanet/utilities/Utilities.kt
Labels: codex

#7221 all: smoother edge to edge (fixes #7220)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/SettingActivity.kt
  app/src/main/java/org/ole/planet/myplanet/ui/courses/CourseProgressActivity.kt
  app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardActivity.kt
  app/src/main/java/org/ole/planet/myplanet/ui/dictionary/DictionaryActivity.kt
  app/src/main/java/org/ole/planet/myplanet/ui/feedback/FeedbackDetailActivity.kt
  app/src/main/java/org/ole/planet/myplanet/ui/map/OfflineMapActivity.kt
  app/src/main/java/org/ole/planet/myplanet/ui/myhealth/AddExaminationActivity.kt
  app/src/main/java/org/ole/planet/myplanet/ui/myhealth/AddMyHealthActivity.kt
  app/src/main/java/org/ole/planet/myplanet/ui/news/NewsDetailActivity.kt
  app/src/main/java/org/ole/planet/myplanet/ui/news/ReplyActivity.kt
  app/src/main/java/org/ole/planet/myplanet/ui/onBoarding/OnBoardingActivity.kt
  app/src/main/java/org/ole/planet/myplanet/ui/resources/AddResourceActivity.kt
  app/src/main/java/org/ole/planet/myplanet/ui/sync/LoginActivity.kt
  app/src/main/java/org/ole/planet/myplanet/ui/userprofile/BecomeMemberActivity.kt
  app/src/main/java/org/ole/planet/myplanet/ui/viewer/AudioPlayerActivity.kt
  app/src/main/java/org/ole/planet/myplanet/ui/viewer/CSVViewerActivity.kt
  app/src/main/java/org/ole/planet/myplanet/ui/viewer/ImageViewerActivity.kt
  app/src/main/java/org/ole/planet/myplanet/ui/viewer/MarkdownViewerActivity.kt
  app/src/main/java/org/ole/planet/myplanet/ui/viewer/PDFReaderActivity.kt
  app/src/main/java/org/ole/planet/myplanet/ui/viewer/TextFileViewerActivity.kt
  app/src/main/java/org/ole/planet/myplanet/ui/viewer/VideoPlayerActivity.kt
  app/src/main/java/org/ole/planet/myplanet/ui/viewer/WebViewActivity.kt
  app/src/main/java/org/ole/planet/myplanet/utilities/EdgeToEdgeUtil.kt
  app/src/main/java/org/ole/planet/myplanet/utilities/EdgeToEdgeUtils.kt
Labels: priority, peer review

#7230 sync: smoother version checks (fixes #7229)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/datamanager/Service.kt
Labels: peer review

#7232 sync: smoother server reachability (fixes #7231)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/dashboard/BellDashboardFragment.kt
Labels: peer review

#7205 all: less `runOnUiThread` is more `lifecycleScope` (fixes #7241)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/base/BaseRealtimeFragment.kt
  app/src/main/java/org/ole/planet/myplanet/base/BaseResourceFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/chat/ChatHistoryListFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/community/CommunityFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/courses/CoursesFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/enterprises/FinanceFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/enterprises/ReportsFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/feedback/FeedbackListFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/myhealth/MyHealthFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/resources/RealtimeLibraryFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/resources/ResourcesFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/survey/SurveyFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/sync/RealtimeSyncMixin.kt
  app/src/main/java/org/ole/planet/myplanet/ui/team/PlanFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/team/TeamDetailFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/team/TeamFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/team/teamTask/TeamTaskFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/userprofile/AchievementFragment.kt
Labels: ready to merge, peer review, codex, ⭐⭐⭐.

#7193 chat: smoother history diffing (fixes #7242)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/chat/ChatHistoryListAdapter.kt
Labels: ready to merge, peer review, codex, ⭐⭐⭐.

#7204 all: smoother `RetryUtils.kt` suspending (fixes #7243)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/datamanager/ApiClient.kt
  app/src/main/java/org/ole/planet/myplanet/service/UploadToShelfService.kt
  app/src/main/java/org/ole/planet/myplanet/utilities/RetryUtils.kt
Labels: ready to merge, peer review, codex, ⭐⭐⭐.

#7222 all: smoother `DialogUtils.kt` (fixes #7244)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/utilities/DialogUtils.kt
Labels: ready to merge, peer review, codex, ⭐⭐., ⭐⭐⭐'

#7226 all: smoother feedback repository (fixes #7245)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/repository/FeedbackRepository.kt
  app/src/main/java/org/ole/planet/myplanet/repository/FeedbackRepositoryImpl.kt
Labels: ready to merge, peer review, codex, ⭐⭐⭐., ⭐⭐⭐'

#7227 all: smoother `DownloadUtils.kt` (fixes #7246)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/utilities/DownloadUtils.kt
Labels: ready to merge, peer review, codex, ⭐⭐⭐., ⭐⭐⭐'

#7211 sync: smoother downloads (fixes #7267)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/datamanager/ApiInterface.kt
  app/src/main/java/org/ole/planet/myplanet/datamanager/DownloadWorker.kt
  app/src/main/java/org/ole/planet/myplanet/datamanager/MyDownloadService.kt
  app/src/main/java/org/ole/planet/myplanet/ui/resources/ResourceDetailFragment.kt
Labels: ready to merge, peer review, codex, ⭐⭐⭐., ⭐⭐⭐'

#7249 community: smoother link realm handling (fixes #7270)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/community/AddLinkFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/team/AdapterTeam.kt
Labels: ready to merge, codex, ⭐⭐⭐., ⭐⭐⭐'

#7254 teams: smoother leaders binding (fixes #7273)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/community/LeadersFragment.kt
Labels: ready to merge, codex, ⭐⭐⭐., ⭐⭐⭐'

#7258 sync: smoother survey uploading (fixes #7257)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/service/ServerReachabilityWorker.kt
Labels: ready to merge, peer review

#7260 myhealth: smoother examination adding (fixes #7236)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/myhealth/AddExaminationActivity.kt
Labels: ready to merge, peer review

#7261 all: smoother `TimeUtils.kt` (fixes #7235)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/utilities/TimeUtils.kt
Labels: ready to merge, peer review

#7265 teams: smoother voices diffing (fixes #7293)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/community/CommunityFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/news/AdapterNews.kt
  app/src/main/java/org/ole/planet/myplanet/ui/news/NewsActions.kt
  app/src/main/java/org/ole/planet/myplanet/ui/news/NewsFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/news/ReplyActivity.kt
  app/src/main/java/org/ole/planet/myplanet/ui/team/MyTeamsDetailFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/team/teamDiscussion/DiscussionListFragment.kt
Labels: ready to merge, ⭐⭐⭐', ⭐⭐⭐`

#7276 mylife: smoother mypersonals diffing (fixes #7294)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/myPersonals/AdapterMyPersonal.kt
  app/src/main/java/org/ole/planet/myplanet/ui/myPersonals/MyPersonalsFragment.kt
Labels: ready to merge, ⭐⭐⭐', ⭐⭐⭐`

#7278 mylife: smoother dictionary realm closing (fixes #7295)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/dictionary/DictionaryActivity.kt
Labels: ready to merge, codex, ⭐⭐⭐., ⭐⭐⭐', ⭐⭐⭐`

#7279 resources: smoother detail realm handling (fixes #7296)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/resources/ResourceDetailFragment.kt
Labels: ready to merge, codex, ⭐⭐⭐., ⭐⭐⭐', ⭐⭐⭐`

#7280 resources: smoother pdf reader realm handling (fixes #7297)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/viewer/PDFReaderActivity.kt
Labels: ready to merge, codex, ⭐⭐⭐., ⭐⭐⭐', ⭐⭐⭐`

#7283 all: smoother `FileUtils.kt` context handling (fixes #7298)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/base/BaseContainerFragment.kt
  app/src/main/java/org/ole/planet/myplanet/base/BaseNewsFragment.kt
  app/src/main/java/org/ole/planet/myplanet/datamanager/DownloadWorker.kt
  app/src/main/java/org/ole/planet/myplanet/datamanager/MyDownloadService.kt
  app/src/main/java/org/ole/planet/myplanet/datamanager/Service.kt
  app/src/main/java/org/ole/planet/myplanet/model/RealmMyLibrary.kt
  app/src/main/java/org/ole/planet/myplanet/ui/SettingActivity.kt
  app/src/main/java/org/ole/planet/myplanet/ui/dashboard/BaseDashboardFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardActivity.kt
  app/src/main/java/org/ole/planet/myplanet/ui/dictionary/DictionaryActivity.kt
  app/src/main/java/org/ole/planet/myplanet/ui/news/NewsDetailActivity.kt
  app/src/main/java/org/ole/planet/myplanet/ui/news/NewsFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/sync/LoginActivity.kt
  app/src/main/java/org/ole/planet/myplanet/ui/sync/SyncActivity.kt
  app/src/main/java/org/ole/planet/myplanet/ui/team/teamDiscussion/DiscussionListFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/viewer/VideoPlayerActivity.kt
  app/src/main/java/org/ole/planet/myplanet/utilities/CameraUtils.kt
  app/src/main/java/org/ole/planet/myplanet/utilities/FileUtils.kt
  app/src/main/java/org/ole/planet/myplanet/utilities/ResourceOpener.kt
Labels: ready to merge, codex, ⭐⭐⭐., ⭐⭐⭐', ⭐⭐⭐`

#7284 dashboard: smoother profile (fixes #7299)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/userprofile/UserDetailFragment.kt
Labels: ready to merge, codex, ⭐⭐⭐., ⭐⭐⭐'

#7287 courses: smoother list diffing (fixes #7300)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/courses/AdapterCourses.kt
  app/src/main/java/org/ole/planet/myplanet/ui/courses/CoursesFragment.kt
Labels: ready to merge, peer review, codex, ⭐⭐⭐., ⭐⭐⭐', ⭐⭐⭐`

#7288 courses: smoother my submissions diffing (fixes #7301)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/submission/AdapterMySubmission.kt
Labels: ready to merge, codex, ⭐⭐⭐., ⭐⭐⭐'

#7277 teams: smoother list diffing (fixes #7330)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/sync/LoginActivity.kt
  app/src/main/java/org/ole/planet/myplanet/ui/team/teamCourse/AdapterTeamCourse.kt
  app/src/main/java/org/ole/planet/myplanet/ui/team/teamCourse/TeamCourseFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/userprofile/TeamListAdapter.kt
Labels: priority, ready to merge, ⭐⭐⭐'

#7304 mylife: smoother dictionary realm handling (fixes #7331)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/dictionary/DictionaryActivity.kt
Labels: ready to merge, codex, ⭐⭐⭐., ⭐⭐⭐'

#7305 resources: smoother repository addition (fixes #7332)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/repository/LibraryRepository.kt
  app/src/main/java/org/ole/planet/myplanet/repository/LibraryRepositoryImpl.kt
  app/src/main/java/org/ole/planet/myplanet/ui/resources/AddResourceActivity.kt
Labels: priority, ready to merge, codex, ⭐⭐⭐., ⭐⭐⭐'

#7308 resources: smoother rating view model (fixes #7334)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/rating/RatingFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/rating/RatingViewModel.kt
Labels: priority, ready to merge, experiment, ⭐⭐⭐'

#7309 all: smoother feedback repository realm flowing (fixes #7335)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/repository/FeedbackRepositoryImpl.kt
  app/src/main/java/org/ole/planet/myplanet/repository/RealmRepository.kt
Labels: priority, ready to merge, codex, ⭐⭐⭐., ⭐⭐⭐'

#7328 mylife: smoother myhealth examination creation (fixes #2077)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/myhealth/AddExaminationActivity.kt
  app/src/main/java/org/ole/planet/myplanet/ui/myhealth/AddMyHealthActivity.kt
Labels: ready to merge, peer review, ⭐⭐⭐.

#7338 courses: smoother filters (fixes #7319)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/courses/AdapterCourses.kt
  app/src/main/java/org/ole/planet/myplanet/ui/courses/CoursesFragment.kt
Labels: priority, peer review, ⭐⭐⭐'

#7354 sync: smoother resources transaction realm handling (fixes #7353)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/datamanager/DatabaseService.kt
Labels: priority, peer review

#7341 resources: smoother creation binding (fixes #7359)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/resources/AddResourceFragment.kt
Labels: codex, ⭐⭐⭐., ⭐⭐⭐'

#7355 dashboard: smoother notification reading (fixes #7158)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/dashboard/notification/AdapterNotification.kt
  app/src/main/java/org/ole/planet/myplanet/ui/dashboard/notification/NotificationsFragment.kt
Labels: priority, codex, ⭐⭐⭐.

#7343 teams: smoother calendar event details binding (fixes #7361)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/mymeetup/MyMeetupDetailFragment.kt
Labels: codex, ⭐⭐⭐., ⭐⭐⭐'

#7344 teams: smoother voices realm closing (fixes #7364)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/news/NewsFragment.kt
Labels: codex, ⭐⭐⭐., ⭐⭐⭐'

#7345 resources: smoother rating view model realm closing (fixes #7365)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/rating/RatingViewModel.kt
Labels: codex, ⭐⭐⭐., ⭐⭐⭐'

#7346 mylife: smoother myhealth creation realm handling (fixes #7366)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/myhealth/AddMyHealthActivity.kt
Labels: codex, ⭐⭐⭐., ⭐⭐⭐'

#7348 courses: smoother submission repository exams (fixes #7367)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/repository/SubmissionRepository.kt
  app/src/main/java/org/ole/planet/myplanet/repository/SubmissionRepositoryImpl.kt
  app/src/main/java/org/ole/planet/myplanet/ui/submission/MySubmissionFragment.kt
Labels: codex, ⭐⭐., ⭐⭐'

#7349 teams: smoother submission repository survey titles (fixes #7368)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/repository/SubmissionRepositoryImpl.kt
Labels: codex, ⭐⭐⭐., ⭐⭐⭐'

#7370 all: smoother repository bindings sorting (fixes #7371)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/di/RepositoryModule.kt
Labels: codex

#7369 all: smoother imports (fixes #7372)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/base/BaseNewsFragment.kt
  app/src/main/java/org/ole/planet/myplanet/datamanager/DownloadWorker.kt
  app/src/main/java/org/ole/planet/myplanet/datamanager/MyDownloadService.kt
  app/src/main/java/org/ole/planet/myplanet/ui/community/CommunityFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/courses/AdapterCourses.kt
  app/src/main/java/org/ole/planet/myplanet/ui/enterprises/FinanceFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/enterprises/ReportsFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/rating/RatingFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/resources/RealtimeLibraryFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/team/PlanFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/team/TeamFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/team/teamTask/TeamTaskFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/viewer/PDFReaderActivity.kt
  app/src/main/java/org/ole/planet/myplanet/utilities/EdgeToEdgeUtils.kt
  app/src/main/java/org/ole/planet/myplanet/utilities/FileUtils.kt
Labels: codex

#7390 teams: smoother calendar my events detail realm handling (fixes #7408)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/mymeetup/MyMeetupDetailFragment.kt
Labels: ready to merge, codex, ⭐⭐⭐., ⭐⭐⭐'

#7395 all: smoother feedback repository constructor (fixes #7412)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/repository/FeedbackRepositoryImpl.kt
Labels: ready to merge, codex, ⭐⭐⭐., ⭐⭐⭐'

#7393 all: smoother user repository findfirst (fixes #7414)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/repository/RealmRepository.kt
  app/src/main/java/org/ole/planet/myplanet/repository/UserRepositoryImpl.kt
Labels: ready to merge, codex, ⭐⭐⭐., ⭐⭐⭐', ⭐⭐⭐`

#7394 all: smoother submission repository exams lookup (fixes #7415)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/repository/SubmissionRepositoryImpl.kt
Labels: ready to merge, codex, ⭐⭐⭐., ⭐⭐⭐', ⭐⭐⭐`

#7418 resources: smoother csv downloads (fixes #7317)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/datamanager/MyDownloadService.kt
  app/src/main/java/org/ole/planet/myplanet/utilities/DownloadUtils.kt
Labels: peer review, ⭐⭐⭐', ⭐⭐⭐`

#7432 chat: smoother detail realm handling (fixes #7450)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/chat/ChatDetailFragment.kt
Labels: codex, ⭐⭐⭐., ⭐⭐⭐', ⭐⭐⭐`

#7427 courses: smoother joining (fixes #7425)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/courses/AdapterCourses.kt
  app/src/main/java/org/ole/planet/myplanet/ui/courses/CoursesFragment.kt
Labels: peer review, ⭐⭐⭐', ⭐⭐⭐`

#7435 resources: smoother library repository lookup (fixes #7452)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/base/BaseContainerFragment.kt
  app/src/main/java/org/ole/planet/myplanet/repository/LibraryRepository.kt
  app/src/main/java/org/ole/planet/myplanet/repository/LibraryRepositoryImpl.kt
Labels: ready to merge, codex, ⭐⭐⭐., ⭐⭐⭐', ⭐⭐⭐`

#7438 all: smoother submission repository list queries (fixes #7456)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/repository/SubmissionRepositoryImpl.kt
Labels: ready to merge, codex, ⭐⭐⭐., ⭐⭐⭐'

#7440 teams: smoother voices replies callback diffing (fixes #7457)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/news/GrandChildAdapter.kt
Labels: ready to merge, codex, ⭐⭐⭐., ⭐⭐⭐'

#7439 resources: smoother pdf reader repository scoping (fixes #7458)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/viewer/PDFReaderActivity.kt
Labels: ready to merge, codex, ⭐⭐⭐., ⭐⭐⭐'

#7459 sync: smoother uploading (fixes #7155)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/datamanager/Service.kt
  app/src/main/java/org/ole/planet/myplanet/ui/sync/SyncActivity.kt
Labels: ⭐⭐⭐', ⭐⭐⭐`

#7546 resources: smoother opening (fixes #7402)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/service/UserProfileDbHandler.kt
Labels: priority, ready to merge, peer review, ⭐⭐⭐', ⭐⭐⭐`

#7547 login: smoother offline asyncing (fixes #7498)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/service/UserProfileDbHandler.kt
  app/src/main/java/org/ole/planet/myplanet/ui/sync/SyncActivity.kt
Labels: priority, ready to merge, peer review, ⭐⭐⭐', ⭐⭐⭐`

#7550 courses: smoother detail realm handling (fixes #7564)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/courses/AdapterSteps.kt
  app/src/main/java/org/ole/planet/myplanet/ui/courses/CourseDetailFragment.kt
Labels: small change, ready to merge, codex, ⭐⭐⭐., ⭐⭐⭐`

#7522 resources: library repository detail by id (fixes #7566)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/repository/LibraryRepository.kt
  app/src/main/java/org/ole/planet/myplanet/repository/LibraryRepositoryImpl.kt
  app/src/main/java/org/ole/planet/myplanet/ui/resources/ResourceDetailFragment.kt
Labels: ready to merge, codex, ⭐⭐⭐., ⭐⭐⭐'

#7553 mylife: smoother achievement context (fixes #7567)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/userprofile/AchievementFragment.kt
Labels: small change, ready to merge, codex, ⭐⭐⭐., ⭐⭐⭐`

#7533 teams: smoother voices scrolling (fixes #7499)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/news/NewsFragment.kt
Labels: duplicate, ready to merge, peer review, ⭐⭐⭐.

#7509 courses: smoother filter refreshing (fixes #7489)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/courses/CoursesFragment.kt
Labels: question, priority, codex, ⭐⭐⭐.

#7552 courses: smoother steps realm handling (fixes #7568)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/courses/CourseStepFragment.kt
Labels: codex, ⭐⭐⭐.

#7514 all: smoother `DialogUtils.kt` (fixes #7569)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/courses/TakeCourseFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/userprofile/EditAchievementFragment.kt
  app/src/main/java/org/ole/planet/myplanet/utilities/DialogUtils.kt
Labels: ready to merge, codex, ⭐⭐⭐., ⭐⭐⭐'

#7570 all: smoother imports (fixes #7573)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/base/BaseContainerFragment.kt
  app/src/main/java/org/ole/planet/myplanet/repository/FeedbackRepositoryImpl.kt
  app/src/main/java/org/ole/planet/myplanet/repository/NotificationRepositoryImpl.kt
  app/src/main/java/org/ole/planet/myplanet/repository/SubmissionRepositoryImpl.kt
  app/src/main/java/org/ole/planet/myplanet/ui/courses/AdapterSteps.kt
  app/src/main/java/org/ole/planet/myplanet/ui/exam/TakeExamFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/myPersonals/MyPersonalsFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/myhealth/AddMyHealthActivity.kt
  app/src/main/java/org/ole/planet/myplanet/ui/resources/CollectionsFragment.kt
Labels: codex

#7463 teams: smoother member joining realm handling (fixes #7595)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/team/teamMember/AdapterJoinedMember.kt
  app/src/main/java/org/ole/planet/myplanet/ui/team/teamMember/JoinedMemberFragment.kt
Labels: priority, experiment, codex, ⭐⭐., ⭐⭐⭐'

#7581 resources: smoother base receivers (fixes #7597)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/base/BaseResourceFragment.kt
Labels: ready to merge, codex, ⭐⭐⭐., ⭐⭐⭐', ⭐⭐⭐`

#7589 dashboard: smoother profile image binding (fixes #7488)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/userprofile/UserProfileFragment.kt
Labels: question, codex, ⭐⭐⭐., ⭐⭐⭐'

#7583 teams: smoother team repository (fixes #7615)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/repository/TeamRepository.kt
  app/src/main/java/org/ole/planet/myplanet/repository/TeamRepositoryImpl.kt
  app/src/main/java/org/ole/planet/myplanet/ui/team/AdapterTeamList.kt
  app/src/main/java/org/ole/planet/myplanet/ui/team/TeamFragment.kt
Labels: codex, ⭐⭐⭐., ⭐⭐⭐'

#7609 teams: less calendar adapter is more (fixes #7619)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/enterprises/AdapterCalendar.kt
  app/src/main/res/layout/row_team_calendar.xml
Labels: codex, ⭐⭐⭐., ⭐⭐⭐', ⭐⭐⭐`

#7610 all: less course repository operations is more (fixes #7620)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/repository/CourseRepository.kt
  app/src/main/java/org/ole/planet/myplanet/repository/CourseRepositoryImpl.kt
Labels: codex, ⭐⭐⭐., ⭐⭐⭐', ⭐⭐⭐`

#7611 all: less library repository method is more (fixes #7620)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/repository/LibraryRepository.kt
  app/src/main/java/org/ole/planet/myplanet/repository/LibraryRepositoryImpl.kt
Labels: codex, ⭐⭐⭐., ⭐⭐⭐', ⭐⭐⭐`

#7584 courses: smoother submission repository exam step count (fixes #7622)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/repository/SubmissionRepository.kt
  app/src/main/java/org/ole/planet/myplanet/repository/SubmissionRepositoryImpl.kt
  app/src/main/java/org/ole/planet/myplanet/ui/courses/AdapterSteps.kt
  app/src/main/java/org/ole/planet/myplanet/ui/courses/CourseDetailFragment.kt
Labels: codex, ⭐⭐⭐., ⭐⭐⭐'

#7586 teams: smoother news repository community support (fixes #7626)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/repository/NewsRepository.kt
  app/src/main/java/org/ole/planet/myplanet/repository/NewsRepositoryImpl.kt
  app/src/main/java/org/ole/planet/myplanet/ui/community/CommunityFragment.kt
Labels: experiment, codex, ⭐⭐⭐., ⭐⭐⭐'

#7625 all: less realtime library fragment is more (fixes #7631)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/resources/RealtimeLibraryFragment.kt
Labels: codex

#7639 resources: less library repository methods is more (fixes #7662)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/repository/LibraryRepository.kt
  app/src/main/java/org/ole/planet/myplanet/repository/LibraryRepositoryImpl.kt
  app/src/main/java/org/ole/planet/myplanet/ui/resources/ResourceDetailFragment.kt
Labels: triage, less, codex, ⭐⭐⭐., ⭐⭐⭐'

#7641 all: less submission repository methods is more (fixes #7663)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/repository/SubmissionRepository.kt
  app/src/main/java/org/ole/planet/myplanet/repository/SubmissionRepositoryImpl.kt
Labels: triage, less, codex, ⭐⭐⭐., ⭐⭐⭐'

#7643 sync: less progress broadcast receiver is more (fixes #7665)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/callback/ProgressBroadcastReceiver.kt
Labels: triage, less, codex, ⭐⭐⭐., ⭐⭐⭐'

#7654 resources: smoother mylibrary refreshing (fixes #7531)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/resources/ResourcesFragment.kt
Labels: priority, ready to merge, ⭐⭐⭐'

#7655 chat: smoother history saving (fixes #7530)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/chat/ChatDetailFragment.kt
Labels: priority, ready to merge, ⭐⭐⭐'

#7652 all: smoother `NotificationUtils.kt` marking (fixes #7669)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/utilities/NotificationUtils.kt
Labels: ready to merge, codex, ⭐⭐⭐., ⭐⭐⭐'

#7651 all: smoother team repository service details (fixes #7670)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/repository/TeamRepository.kt
  app/src/main/java/org/ole/planet/myplanet/repository/TeamRepositoryImpl.kt
  app/src/main/java/org/ole/planet/myplanet/ui/community/ServicesFragment.kt
Labels: ready to merge, codex, ⭐⭐⭐., ⭐⭐⭐'

#7635 courses: smoother progress zero question exams (fixes #7674)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/courses/CourseProgressActivity.kt
Labels: triage, small change, ready to merge, codex, ⭐⭐⭐., ⭐⭐⭐'

#7637 chat: smoother view visibility resetting (fixes #7675)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/chat/ChatAdapter.kt
Labels: triage, small change, ready to merge, codex, ⭐⭐⭐., ⭐⭐⭐'

#7680 sync: less reset circuit breaker is more (fixes #7711)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/service/sync/CircuitBreaker.kt
Labels: triage, small change, less, ready to merge, codex, ⭐⭐⭐.

#7685 all: less library repository operations is more (fixes #7716)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/repository/LibraryRepository.kt
  app/src/main/java/org/ole/planet/myplanet/repository/LibraryRepositoryImpl.kt
Labels: triage, small change, less, ready to merge, codex, ⭐⭐⭐.

#7686 all: less team repository leader looking is more (fixes #7717)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/repository/TeamRepository.kt
  app/src/main/java/org/ole/planet/myplanet/repository/TeamRepositoryImpl.kt
Labels: triage, small change, less, ready to merge, codex, ⭐⭐⭐.

#7700 all: smoother rating repository view model (fixes #7741)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/repository/RatingRepository.kt
  app/src/main/java/org/ole/planet/myplanet/repository/RatingRepositoryImpl.kt
  app/src/main/java/org/ole/planet/myplanet/ui/rating/RatingViewModel.kt
Labels: ready to merge, codex, ⭐⭐⭐., ⭐⭐⭐'

#7703 teams: smoother detail repository lookups (fixes #7742)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/team/TeamDetailFragment.kt
Labels: ready to merge, codex, ⭐⭐⭐., ⭐⭐⭐'

#7705 teams: smoother tab scrolling (fixes #7494)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/team/TeamDetailFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/team/TeamPagerAdapter.kt
Labels: ready to merge, peer review, ⭐⭐⭐', ⭐⭐⭐`

#7722 teams: smoother voices image uploading (fixes #7706)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/news/ReplyActivity.kt
Labels: ready to merge, peer review, ⭐⭐⭐', ⭐⭐⭐`

#7724 all: less search repository is more (fixes #7745)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/di/RepositoryModule.kt
  app/src/main/java/org/ole/planet/myplanet/repository/SearchRepository.kt
  app/src/main/java/org/ole/planet/myplanet/repository/SearchRepositoryImpl.kt
  app/src/main/java/org/ole/planet/myplanet/ui/courses/CoursesViewModel.kt
Labels: triage, less, ready to merge, codex, ⭐⭐⭐., ⭐⭐⭐`

#7725 teams: less voices detail is more (fixes #7746)
  app/build.gradle
  app/src/lite/AndroidManifest.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/ole/planet/myplanet/ui/news/NewsDetailActivity.kt
  app/src/main/res/layout/activity_news_detail.xml
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-ne/strings.xml
  app/src/main/res/values-so/strings.xml
  app/src/main/res/values/strings.xml
Labels: triage, less, ready to merge, codex, ⭐⭐⭐.

#7738 resources: smoother download dialog (fixes #7532)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/base/BaseResourceFragment.kt
Labels: ready to merge, codex, ⭐⭐⭐.

#7736 resources: smoother searching (fixes #7417)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/resources/ResourcesFragment.kt
Labels: triage, ready to merge, codex, ⭐⭐⭐., ⭐⭐⭐'

#7737 all: smoother notification binding (fixes #7699)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/dashboard/notification/NotificationsFragment.kt
Labels: triage, ready to merge, codex, ⭐⭐⭐., ⭐⭐⭐'

#7735 teams: smoother survey sort diffing (fixes #7750)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/survey/AdapterSurvey.kt
Labels: ready to merge, codex, ⭐⭐⭐., ⭐⭐⭐'

#7751 all: smoother imports (fixes #7753)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/model/RealmMyTeam.kt
  app/src/main/java/org/ole/planet/myplanet/repository/TeamRepositoryImpl.kt
  app/src/main/java/org/ole/planet/myplanet/ui/community/ServicesFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/exam/TakeExamFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/news/NewsActions.kt
  app/src/main/java/org/ole/planet/myplanet/ui/news/NewsFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/sync/SyncActivity.kt
  app/src/main/java/org/ole/planet/myplanet/ui/team/AdapterTeamList.kt
  app/src/main/java/org/ole/planet/myplanet/ui/team/teamDiscussion/DiscussionListFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/team/teamMember/AdapterMemberRequest.kt
  app/src/main/java/org/ole/planet/myplanet/ui/team/teamMember/MembersFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/viewer/PDFReaderActivity.kt
  app/src/main/java/org/ole/planet/myplanet/utilities/DownloadUtils.kt
Labels: codex

#7763 dashboard: less fragment is more (fixes #7796)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/sync/DashboardElementActivity.kt
  app/src/main/res/layout/fragment_home.xml
Labels: triage, small change, less, codex, ⭐⭐⭐.

#7814 all: less `TimeUtils.kt` is more (fixes #7848)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/utilities/TimeUtils.kt
Labels: triage, less, ready to merge, codex, ⭐⭐⭐.

#7817 all: less realm repository is more (fixes #7849)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/repository/RealmRepository.kt
Labels: triage, less, ready to merge, codex, ⭐⭐⭐.

#7827 teams: smoother list filtering (fixes #7822)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/model/RealmMyTeam.kt
Labels: priority, ready to merge, ⭐⭐⭐', ⭐⭐⭐`

#7823 all: smoother realm repository async helper (fixes #7850)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/repository/CourseRepositoryImpl.kt
  app/src/main/java/org/ole/planet/myplanet/repository/LibraryRepositoryImpl.kt
  app/src/main/java/org/ole/planet/myplanet/repository/RealmRepository.kt
  app/src/main/java/org/ole/planet/myplanet/repository/SubmissionRepositoryImpl.kt
  app/src/main/java/org/ole/planet/myplanet/repository/TeamRepositoryImpl.kt
Labels: triage, small change, ready to merge, experiment, codex, ⭐⭐⭐., ⭐⭐⭐', ⭐⭐`

#7825 teams: smoother voices replying (fixes #7851)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/news/ReplyActivity.kt
Labels: small change, ready to merge, codex, ⭐⭐⭐., ⭐⭐⭐', ⭐⭐⭐`

#7833 teams: smoother voices replies sorting (fixes #7853)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/repository/NewsRepositoryImpl.kt
Labels: small change, ready to merge, codex, ⭐⭐⭐., ⭐⭐⭐', ⭐⭐⭐`

#7865 teams: less detail content layout is more (fixes #7892)
  app/build.gradle
  app/src/main/res/layout/content_team_detail_tab.xml
Labels: triage, less, ready to merge, codex, ⭐⭐⭐., ⭐⭐⭐', ⭐⭐⭐`

#7873 teams: less detail layouts is more (fixes #7891)
  app/build.gradle
  app/src/main/res/layout/content_teams_detail.xml
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-ne/strings.xml
  app/src/main/res/values-so/strings.xml
  app/src/main/res/values/strings.xml
Labels: triage, less, ready to merge, codex, ⭐⭐⭐., ⭐⭐⭐`

#7867 all: less alert layout is more (fixes #7895)
  app/build.gradle
  app/src/main/res/layout/alert_other_info.xml
Labels: triage, less, ready to merge, codex, ⭐⭐⭐., ⭐⭐⭐`

#7874 all: less alert add link layout is more (fixes #7901)
  app/build.gradle
  app/src/main/res/layout/alert_add_link.xml
Labels: triage, less, ready to merge, codex, ⭐⭐⭐., ⭐⭐⭐`

#7842 all: smoother `Utilities.kt` toasting (fixes #7902)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/SettingActivity.kt
  app/src/main/java/org/ole/planet/myplanet/ui/feedback/FeedbackFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/myPersonals/AdapterMyPersonal.kt
  app/src/main/java/org/ole/planet/myplanet/ui/resources/AddResourceFragment.kt
  app/src/main/java/org/ole/planet/myplanet/utilities/Utilities.kt
Labels: ready to merge, codex, ⭐⭐⭐., ⭐⭐⭐`

#7875 teams: smoother preference sharing (fixes #7903)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/team/TeamFragment.kt
Labels: small change, ready to merge, codex, ⭐⭐⭐., ⭐⭐⭐'

#7884 teams: smoother voices user caching (fixes #7906)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/news/AdapterNews.kt
Labels: ready to merge, experiment, codex, ⭐⭐⭐., ⭐⭐⭐'

#7885 all: smoother notifications resources filtering (fixes #7907)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/repository/NotificationRepositoryImpl.kt
Labels: small change, ready to merge, codex, ⭐⭐⭐., ⭐⭐⭐'

#7888 all: smoother chat repository history listing (fixes #7910)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/di/RepositoryModule.kt
  app/src/main/java/org/ole/planet/myplanet/repository/ChatRepository.kt
  app/src/main/java/org/ole/planet/myplanet/repository/ChatRepositoryImpl.kt
  app/src/main/java/org/ole/planet/myplanet/ui/chat/ChatHistoryListFragment.kt
Labels: ready to merge, experiment, codex, ⭐⭐⭐., ⭐⭐⭐'

#7913 courses: less progress repository is more (fixes #7938)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/di/RepositoryModule.kt
  app/src/main/java/org/ole/planet/myplanet/repository/CourseProgressRepository.kt
  app/src/main/java/org/ole/planet/myplanet/repository/CourseProgressRepositoryImpl.kt
Labels: triage, less, ready to merge, codex, ⭐⭐⭐.

#7914 sync: less metric export is more (fixes #7939)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/service/sync/SyncPerformanceMonitor.kt
Labels: triage, less, ready to merge, codex, ⭐⭐⭐.

#7941 sync: less realm transaction is more (fixes #7966)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/service/sync/RealmConnectionPool.kt
Labels: triage, less, ready to merge, codex, ⭐⭐⭐.

#7942 courses: less completion counter is more (fixes #7967)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/courses/MyProgressFragment.kt
Labels: triage, less, ready to merge, codex, ⭐⭐⭐.

#7946 sync: less batch callback is more (fixes #7971)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/callback/RealtimeSyncListener.kt
  app/src/main/java/org/ole/planet/myplanet/service/sync/RealtimeSyncCoordinator.kt
Labels: triage, less, ready to merge, codex, ⭐⭐⭐.

#7948 resources: less rating repository is more (fixes #7973)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/repository/RatingRepository.kt
  app/src/main/java/org/ole/planet/myplanet/repository/RatingRepositoryImpl.kt
Labels: triage, less, ready to merge, codex, ⭐⭐⭐.

#7949 all: less network module qualifier is more (fixes #7974)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/di/NetworkModule.kt
Labels: triage, less, ready to merge, codex, ⭐⭐⭐.

#7950 sync: less text validation is more (fixes #7975)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/sync/ProcessUserDataActivity.kt
Labels: triage, less, ready to merge, codex, ⭐⭐⭐.

#7951 teams: less update courses list is more (fixes #7976)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/team/teamCourse/TeamCourseFragment.kt
Labels: triage, less, ready to merge, codex, ⭐⭐⭐.

#7952 courses: less factory is more (fixes #7977)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/courses/CoursesFragment.kt
Labels: triage, less, ready to merge, codex, ⭐⭐⭐.

#7953 teams: smoother unmembering (fixes #7919)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/team/teamMember/AdapterJoinedMember.kt
  app/src/main/java/org/ole/planet/myplanet/ui/team/teamMember/JoinedMemberFragment.kt
Labels: priority, ready to merge, ⭐⭐⭐', ⭐⭐⭐`

#7956 all: smoother `SecurePrefs.kt` creation handling (fixes #7837)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/utilities/SecurePrefs.kt
Labels: priority, ready to merge, codex, ⭐⭐⭐., ⭐⭐⭐`

#7876 dashboard: smoother activity user profile handling (fixes #7980)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/dashboard/MyActivityFragment.kt
Labels: small change, priority, ready to merge, codex, ⭐⭐⭐'

#7931 chats: smoother history lists caching (fixes #7940)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/repository/ChatRepository.kt
  app/src/main/java/org/ole/planet/myplanet/repository/ChatRepositoryImpl.kt
  app/src/main/java/org/ole/planet/myplanet/ui/chat/ChatHistoryListAdapter.kt
  app/src/main/java/org/ole/planet/myplanet/ui/chat/ChatHistoryListFragment.kt
Labels: ready to merge, codex, ⭐⭐⭐., ⭐⭐⭐', ⭐⭐⭐`

#7983 all: smoother imports (fixes #7984)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/repository/TeamRepositoryImpl.kt
  app/src/main/java/org/ole/planet/myplanet/ui/chat/ChatHistoryListFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/courses/MyProgressFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/exam/BaseExamFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/exam/TakeExamFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/news/NewsLabelManager.kt
  app/src/main/java/org/ole/planet/myplanet/ui/resources/AdapterResource.kt
  app/src/main/java/org/ole/planet/myplanet/ui/sync/ProcessUserDataActivity.kt
  app/src/main/java/org/ole/planet/myplanet/ui/team/TeamFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/team/teamResource/TeamResourceFragment.kt
Labels: codex, ⭐⭐⭐.

#7989 sync: less realm pool stats is more (fixes #7997)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/service/sync/RealmConnectionPool.kt
Labels: triage, less, ready to merge, codex, ⭐⭐⭐.

#7990 sync: less shutdown paths is more (fixes #7998)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/service/ImprovedSyncManager.kt
  app/src/main/java/org/ole/planet/myplanet/service/sync/RealmConnectionPool.kt
Labels: triage, less, ready to merge, codex, ⭐⭐⭐.

#7991 sync: less adaptive batch processor retrying is more (fixes #7999)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/service/sync/AdaptiveBatchProcessor.kt
Labels: triage, less, ready to merge, codex, ⭐⭐⭐.

#7992 sync: less circuit breaker utilities is more (fixes #8000)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/service/sync/CircuitBreaker.kt
Labels: triage, less, ready to merge, codex, ⭐⭐⭐.

#7993 sync: less realtime metrics flow is more (fixes #8001)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/service/sync/SyncPerformanceMonitor.kt
Labels: triage, less, ready to merge, codex, ⭐⭐⭐.

#7985 teams: smoother survey sorting (fixes #7925)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/survey/SurveyFragment.kt
Labels: priority, ready to merge, peer review, ⭐⭐⭐`

#7996 teams: smoother task filtering (fixes #7995)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/team/teamTask/TeamTaskFragment.kt
Labels: priority, ready to merge, peer review, ⭐⭐⭐`

#7959 teams: smoother user profile detaching (fixes #8003)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/team/AdapterTeamList.kt
  app/src/main/java/org/ole/planet/myplanet/ui/team/TeamFragment.kt
Labels: small change, ready to merge, codex, ⭐⭐⭐., ⭐⭐⭐`

#7962 resources: smoother notification repository counting (fixes #8006)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/repository/NotificationRepositoryImpl.kt
Labels: small change, ready to merge, codex, ⭐⭐⭐., ⭐⭐⭐`

#7965 teams: smoother voices member navigation handling (fixes #8008)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/base/BaseNewsFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/news/AdapterNews.kt
  app/src/main/java/org/ole/planet/myplanet/ui/news/NewsActions.kt
  app/src/main/java/org/ole/planet/myplanet/ui/news/ReplyActivity.kt
Labels: triage, ready to merge, experiment, codex, ⭐⭐⭐., ⭐⭐⭐`

#8012 resources: less video player binding is more (fixes #8034)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/viewer/VideoPlayerActivity.kt
  app/src/main/java/org/ole/planet/myplanet/ui/viewer/VideoPlayerModule.kt
Labels: triage, less, ready to merge, experiment, codex, ⭐⭐⭐., ⭐⭐⭐'

#8014 all: less set theme mode is more (fixes #8036)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/MainApplication.kt
Labels: triage, less, ready to merge, codex, ⭐⭐⭐., ⭐⭐⭐'

#8015 all: less stream conversion is more (fixes #8037)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/utilities/FileUtils.kt
Labels: triage, less, ready to merge, codex, ⭐⭐⭐., ⭐⭐⭐'

#8016 all: less entry chip is more (fixes #8038)
  app/build.gradle
  app/src/main/res/xml/entry_chip.xml
Labels: triage, less, ready to merge, codex, ⭐⭐⭐., ⭐⭐⭐'

#7987 teams: smoother leader assigning (fixes #7923)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/team/teamMember/AdapterJoinedMember.kt
  app/src/main/java/org/ole/planet/myplanet/ui/team/teamMember/JoinedMemberFragment.kt
Labels: priority, ready to merge, ⭐⭐⭐', ⭐⭐⭐`

#8010 teams: smoother tasks refreshing (fixes #8009)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/team/teamTask/TeamTaskFragment.kt
Labels: priority, ready to merge, ⭐⭐⭐', ⭐⭐⭐`

#8017 courses: smoother exam user profile handling (fixes #8039)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/exam/UserInformationFragment.kt
Labels: small change, ready to merge, codex, ⭐⭐⭐., ⭐⭐⭐', ⭐⭐⭐`

#8018 courses: smoother join user profile handling (fixes #8040)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/courses/TakeCourseFragment.kt
Labels: small change, ready to merge, codex, ⭐⭐⭐., ⭐⭐⭐', ⭐⭐⭐`

#8021 mylife: smoother mypersonal repository resources user handling (fixes #8042)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/repository/MyPersonalRepositoryImpl.kt
Labels: small change, ready to merge, codex, ⭐⭐⭐., ⭐⭐⭐', ⭐⭐⭐`
