Repository open-learning-exchange/myplanet, pull requests merged in 2025-04, with the labels that each got.

#5586 all: smoother ui urls (fixes #5562)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/SettingActivity.kt
  app/src/main/java/org/ole/planet/myplanet/ui/chat/ChatDetailFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/chat/ChatHistoryListAdapter.kt
  app/src/main/java/org/ole/planet/myplanet/ui/courses/CoursesFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/exam/UserInformationFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/myhealth/AdapterHealthExamination.kt
  app/src/main/java/org/ole/planet/myplanet/ui/news/AdapterNews.kt
  app/src/main/java/org/ole/planet/myplanet/ui/news/NewsFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/resources/AddResourceFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/resources/ResourcesFilterFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/resources/ResourcesFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/sync/DashboardElementActivity.kt
  app/src/main/java/org/ole/planet/myplanet/ui/sync/ProcessUserDataActivity.kt
  app/src/main/java/org/ole/planet/myplanet/ui/sync/SyncActivity.kt
  app/src/main/java/org/ole/planet/myplanet/ui/team/AdapterTeamList.kt
  app/src/main/java/org/ole/planet/myplanet/ui/userprofile/AchievementFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/userprofile/UserProfileFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/viewer/VideoPlayerActivity.kt
  app/src/main/java/org/ole/planet/myplanet/ui/viewer/WebViewActivity.kt
Labels: ready to merge, peer review

#5589 sync: smoother foreground toast (fixes #5529)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/service/AutoSyncWorker.kt
Labels: priority, ready to merge, peer review

#5597 all: smoother navigation (fixes #5579)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardActivity.kt
  app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardActivity.kt.lite
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-ne/strings.xml
  app/src/main/res/values-so/strings.xml
  app/src/main/res/values/strings.xml
Labels: ready to merge

#5594 dashboard: smoother profile form (fixes #5581)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/exam/UserInformationFragment.kt
Labels: ready to merge

#5596 dashboard: smoother profile buttons (fixes #5595)
  app/build.gradle
  app/src/main/res/layout/edit_profile_dialog.xml
Labels: ready to merge

#5591 mylife: smoother myhealth records (fixes #5590)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/myhealth/MyHealthFragment.kt
Labels: ready to merge

#5599 sync: smoother realm transactions (fixes #5598)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/model/RealmAchievement.kt
  app/src/main/java/org/ole/planet/myplanet/model/RealmCertification.kt
  app/src/main/java/org/ole/planet/myplanet/model/RealmChatHistory.kt
  app/src/main/java/org/ole/planet/myplanet/model/RealmCourseProgress.kt
  app/src/main/java/org/ole/planet/myplanet/model/RealmExamQuestion.kt
  app/src/main/java/org/ole/planet/myplanet/model/RealmFeedback.kt
  app/src/main/java/org/ole/planet/myplanet/model/RealmMeetup.kt
  app/src/main/java/org/ole/planet/myplanet/model/RealmMyHealthPojo.kt
  app/src/main/java/org/ole/planet/myplanet/model/RealmNews.kt
  app/src/main/java/org/ole/planet/myplanet/model/RealmOfflineActivity.kt
  app/src/main/java/org/ole/planet/myplanet/model/RealmRating.kt
  app/src/main/java/org/ole/planet/myplanet/model/RealmStepExam.kt
  app/src/main/java/org/ole/planet/myplanet/model/RealmSubmission.kt
  app/src/main/java/org/ole/planet/myplanet/model/RealmTag.kt
  app/src/main/java/org/ole/planet/myplanet/model/RealmTeamLog.kt
  app/src/main/java/org/ole/planet/myplanet/model/RealmTeamTask.kt
  app/src/main/java/org/ole/planet/myplanet/service/SyncManager.kt
  app/src/main/java/org/ole/planet/myplanet/service/TransactionSyncManager.kt
  app/src/main/java/org/ole/planet/myplanet/ui/exam/TakeExamFragment.kt
Labels: priority, ready to merge, peer review

#5601 teams: smoother event details (fixes #5549)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/enterprises/EnterpriseCalendarFragment.kt
  app/src/main/res/layout/fragment_enterprise_calendar.xml
  app/src/main/res/layout/item_meetup.xml
  app/src/main/res/layout/meetup_dialog.xml
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-ne/strings.xml
  app/src/main/res/values-so/strings.xml
  app/src/main/res/values/strings.xml
Labels: peer review

#5610 teams: smoother voices creation (fixes #5608)
  app/build.gradle
  app/src/main/res/layout/fragment_news.xml
Labels: ready to merge

#5621 teams: smoother list buttons (fixes #5613)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/team/AdapterTeamList.kt
Labels: ready to merge

#5629 teams: smoother members list (fixes #5626)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/team/teamMember/AdapterJoinedMember.kt
  app/src/main/java/org/ole/planet/myplanet/ui/team/teamMember/JoinedMemberFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/team/teamMember/MembersFragment.kt
Labels: ready to merge, peer review

#5625 login: smoother community calendar (fixes #5619)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/enterprises/EnterpriseCalendarFragment.kt
Labels: ready to merge

#5631 teams: smoother calendar recurring frequency (fixes #5630)
  app/build.gradle
  app/src/main/res/layout/add_meetup.xml
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-ne/strings.xml
  app/src/main/res/values-so/strings.xml
  app/src/main/res/values/strings.xml
Labels: ready to merge

#5602 mylife: smoother myachievements view (fixes #5600)
  app/build.gradle
  app/src/main/res/layout/fragment_achievement.xml
  app/src/main/res/layout/row_achievement.xml
  app/src/main/res/layout/row_other_info.xml
Labels: ready to merge

#5628 teams: smoother calendar (fixes #5566)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/community/CommunityPagerAdapter.kt
  app/src/main/java/org/ole/planet/myplanet/ui/team/TeamCalendarFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/team/TeamPagerAdapter.kt
  app/src/main/res/layout/fragment_enterprise_calendar.xml
Labels: ready to merge

#5635 sync: smoother configuration (fixes #5634)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/utilities/DialogUtils.kt
Labels: ready to merge

#5648 mylife: smoother myhealth records sparse (fixes #5645)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/myhealth/MyHealthFragment.kt
  app/src/main/res/layout/fragment_vital_sign.xml
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-ne/strings.xml
  app/src/main/res/values-so/strings.xml
  app/src/main/res/values/strings.xml
Labels: ready to merge

#5641 dashboard: smoother view (fixes #5640)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardActivity.kt
  app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardActivity.kt.lite
  app/src/main/java/org/ole/planet/myplanet/utilities/BottomNavigationViewHelper.kt
Labels: ready to merge

#5639 sync: smoother configuration beta enabled (fixes #5638)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/sync/SyncActivity.kt
Labels: ready to merge

#5649 teams: smoother finances records dates (fixes #5622)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/enterprises/FinanceFragment.kt
Labels: ready to merge

#5664 login: smoother team handling (fixes #5663)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/team/AdapterTeamList.kt
Labels: ready to merge

#5661 sync: smoother configuration beta enabled (fixes #5660)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/service/SyncManager.kt
  app/src/main/java/org/ole/planet/myplanet/ui/SettingActivity.kt
Labels: ready to merge

#5682 teams: smoother event details (fixes #5651)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/team/TeamCalendarFragment.kt
Labels: ready to merge

#5636 teams: smoother calendar event date (fixes #5521)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/team/teamTask/TeamTaskFragment.kt
Labels: ready to merge

#5672 mylife: smoother myachievements view (fixes #5618)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/userprofile/AchievementFragment.kt
Labels: ready to merge

#5673 teams: smoother chat delete dialog dark mode (fixes #5671)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/news/AdapterNews.kt
Labels: ready to merge

#5650 teams: smoother calendar events creation (fixes #5611)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/model/RealmMeetup.kt
  app/src/main/java/org/ole/planet/myplanet/ui/mymeetup/AdapterMeetup.kt
  app/src/main/java/org/ole/planet/myplanet/ui/team/TeamCalendarFragment.kt
  app/src/main/res/layout/add_meetup.xml
  app/src/main/res/layout/item_meetup.xml
Labels: ready to merge

#5675 teams: smoother finances records date order (fixes #5624)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/enterprises/FinanceFragment.kt
Labels: ready to merge

#5678 sync: smoother caching (fixes #5676)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/datamanager/Service.kt
Labels: ready to merge

#5687 teams: smoother members priority sorting (fixes #5686)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/team/AdapterTeamList.kt
Labels: ready to merge

#5698 teams: smoother tasks filters light mode (fixes #5153)
  app/build.gradle
  app/src/main/res/layout/fragment_team_task.xml
Labels: ready to merge

#5695 login: revert fast register (fixes #5694)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/base/BaseResourceFragment.kt
  app/src/main/java/org/ole/planet/myplanet/datamanager/Service.kt
  app/src/main/java/org/ole/planet/myplanet/model/RealmUserModel.kt
  app/src/main/java/org/ole/planet/myplanet/service/UploadManager.kt
  app/src/main/java/org/ole/planet/myplanet/service/UserProfileDbHandler.kt
  app/src/main/java/org/ole/planet/myplanet/ui/sync/LoginActivity.kt
  app/src/main/java/org/ole/planet/myplanet/ui/sync/SyncActivity.kt
  app/src/main/java/org/ole/planet/myplanet/ui/userprofile/BecomeMemberActivity.kt
  app/src/main/java/org/ole/planet/myplanet/utilities/ServerUrlMapper.kt
Labels: don't merge, peer review

#5701 login: smoother team list (fixes #5692)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/sync/LoginActivity.kt
  app/src/main/res/layout/activity_login.xml
Labels: ready to merge

#5670 all: smoother progress dialog (fixes #5669)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/sync/ProcessUserDataActivity.kt
  app/src/main/java/org/ole/planet/myplanet/ui/sync/SyncActivity.kt
Labels: peer review

#5706 teams: smoother event detail buttons (fixes #5705)
  app/build.gradle
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-ne/strings.xml
  app/src/main/res/values-so/strings.xml
  app/src/main/res/values/strings.xml
Labels: ready to merge

#5727 chat: smoother realm transaction (fixes #5714)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/chat/ChatAdapter.kt
  app/src/main/java/org/ole/planet/myplanet/ui/chat/ChatDetailFragment.kt
Labels: ready to merge, peer review

#5725 teams: smoother calendar event creation (fixes #5724)
  app/build.gradle
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-ne/strings.xml
  app/src/main/res/values-so/strings.xml
  app/src/main/res/values/strings.xml
Labels: ready to merge, peer review

#5681 dashboard: smoother profile dialog edit (fixes #5680)
  app/build.gradle
  app/src/main/res/layout/edit_profile_dialog.xml
Labels: ready to merge, peer review

#5728 teams: smoother calendar events creation (fixes #5726)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/team/TeamCalendarFragment.kt
Labels: ready to merge

#5733 teams: smoother calendar event link (fixes #5732)
  app/build.gradle
  app/src/main/res/layout/item_meetup.xml
Labels: ready to merge

#5704 resources: smoother recording audio permissions (fixes #5702)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/resources/AddResourceFragment.kt
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-ne/strings.xml
  app/src/main/res/values-so/strings.xml
  app/src/main/res/values/strings.xml
Labels: ready to merge

#5736 login: smoother community (fixes #5734)
  app/build.gradle
  app/src/main/res/layout/fragment_team_detail.xml
Labels: ready to merge

#5693 resources: smoother creation buttons light mode (fixes #5691)
  app/build.gradle
  app/src/main/res/drawable/bg_multiselect_blue.xml
  app/src/main/res/layout/activity_add_resource.xml
Labels: peer review

#5750 all: smoother navigation focus (fixes #5741)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardActivity.kt
  app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardActivity.kt.lite
Labels: ready to merge

#5749 teams: smoother calendar event link validation (fixes #5748)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/team/TeamCalendarFragment.kt
Labels: ready to merge

#5739 mylife: smoother myhealth view (fixes #5737)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/myhealth/MyHealthFragment.kt
  app/src/main/res/layout/fragment_vital_sign.xml
Labels: ready to merge

#5464 chat: smoother provider selection (fixes #5463)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/model/ChatViewModel.kt
  app/src/main/java/org/ole/planet/myplanet/ui/chat/ChatDetailFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/chat/ChatHistoryListAdapter.kt
  app/src/main/java/org/ole/planet/myplanet/ui/chat/ChatHistoryListFragment.kt
Labels: ready to merge

#5353 teams: smoother survey reminder (fixes #5351)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/dashboard/BellDashboardFragment.kt
  app/src/main/res/layout/dialog_remind_later.xml
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-ne/strings.xml
  app/src/main/res/values-so/strings.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: ready to merge

#5765 sync: smoother upload (fixes #5656)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/service/UploadManager.kt
  app/src/main/java/org/ole/planet/myplanet/service/UploadToShelfService.kt
  app/src/main/java/org/ole/planet/myplanet/ui/sync/ProcessUserDataActivity.kt
Labels: ready to merge

#5774 teams: smoother survey sync (fixes #5773)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/model/RealmSubmission.kt
  app/src/main/java/org/ole/planet/myplanet/ui/exam/BaseExamFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/exam/TakeExamFragment.kt
Labels: ready to merge

#5781 teams: smoother guest user (fixes #5762)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/team/TeamDetailFragment.kt
Labels: ready to merge

#5782 courses: smoother guest mode (fixes #5763)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/courses/CoursesFragment.kt
Labels: ready to merge

#5786 teams: smoother calendar date (fixes #5683)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/team/TeamCalendarFragment.kt
Labels: ready to merge

#5761 login: smoother team selection (fixes #5754)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/sync/LoginActivity.kt
Labels: ready to merge

#5777 dashboard: smoother activity chart (fixes #5775)
  app/build.gradle
  app/src/main/res/layout/fragment_my_activity.xml
Labels: ready to merge

#5788 all: smoother logout (fixes #5374)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/service/UserProfileDbHandler.kt
  app/src/main/java/org/ole/planet/myplanet/ui/sync/DashboardElementActivity.kt
Labels: ready to merge

#5783 resources: smoother camera permissions (fixes #5745)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/resources/AddResourceFragment.kt
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-ne/strings.xml
  app/src/main/res/values-so/strings.xml
  app/src/main/res/values/strings.xml
Labels: ready to merge

#5766 mylife: smoother myhealth record birthday (fixes #5759)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/myhealth/AddMyHealthActivity.kt
Labels: ready to merge

#5785 teams: smoother calendar event creation (fixes #5764)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/team/TeamCalendarFragment.kt
Labels: ready to merge
