Repository open-learning-exchange/myplanet, pull requests merged in 2025-03, with the labels that each got.

#5358 teams: smoother survey submit (fixes #5352)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/exam/BaseExamFragment.kt
Labels: ready to merge

#5396 courses: smoother navigation buttons (fixes #5386)
  app/build.gradle
  app/src/main/res/layout/fragment_my_course.xml
Labels: ready to merge

#5399 login: smoother settings error dialog (fixes #5395)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/utilities/DialogUtils.kt
Labels: ready to merge

#5400 teams: smoother joining security (fixes #5381)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/team/teamMember/AdapterMemberRequest.kt
  app/src/main/res/layout/row_member_request.xml
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-ne/strings.xml
  app/src/main/res/values-so/strings.xml
  app/src/main/res/values/strings.xml
Labels: ready to merge

#5402 teams: smoother survey closing dialog (fixes #5401)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/exam/UserInformationFragment.kt
  app/src/main/res/layout/fragment_user_information.xml
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-ne/strings.xml
  app/src/main/res/values-so/strings.xml
  app/src/main/res/values/strings.xml
Labels: ready to merge

#5261 teams: smoother plan button (fixes #5259)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/team/PlanFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/team/TeamFragment.kt
  app/src/main/res/layout/fragment_plan.xml
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-ne/strings.xml
  app/src/main/res/values-so/strings.xml
  app/src/main/res/values/strings.xml
Labels: ready to merge

#5408 teams: smoother surveys submission dark mode (fixes #5359)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/exam/UserInformationFragment.kt
  app/src/main/res/layout/fragment_user_information.xml
Labels: ready to merge

#5406 login: less toasts is more (fixes #5405)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/base/BaseContainerFragment.kt
  app/src/main/java/org/ole/planet/myplanet/base/BaseContainerFragment.kt.lite
  app/src/main/java/org/ole/planet/myplanet/base/PermissionActivity.kt
  app/src/main/java/org/ole/planet/myplanet/base/PermissionActivity.kt.lite
Labels: peer review

#5409 all: smoother settings texts (fixes #5368)
  app/build.gradle
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-ne/strings.xml
  app/src/main/res/values/strings.xml
Labels: peer review

#5411 teams: smoother navigation details (fixes #5404)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/team/AdapterTeamList.kt
  app/src/main/java/org/ole/planet/myplanet/ui/team/TeamDetailFragment.kt
Labels: ready to merge

#5403 teams: smoother joining approve buttons (fixes #5367)
  app/build.gradle
  app/src/main/res/layout/row_member_request.xml
Labels: ready to merge

#5414 all: smoother feedback buttons (fixes #5413)
  app/build.gradle
  app/src/main/res/values/strings.xml
Labels: ready to merge

#4917 teams: smoother resources remove (fixes #4916)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/team/teamResource/AdapterTeamResource.kt
  app/src/main/java/org/ole/planet/myplanet/ui/team/teamResource/ResourceUpdateListner.kt
  app/src/main/java/org/ole/planet/myplanet/ui/team/teamResource/TeamResourceFragment.kt
Labels: ready to merge

#5426 all: smoother settings beta sync (fixes #5425)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/SettingActivity.kt
  app/src/main/res/xml/pref.xml
Labels: ready to merge

#5434 teams: smoother surveys search (fixes #5373)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/survey/SurveyFragment.kt
  app/src/main/res/layout/fragment_survey.xml
  app/src/main/res/layout/spinner_text.xml
Labels: ready to merge

#5394 login: smoother wifi dialog (fixes #5387)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/utilities/DialogUtils.kt
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-so/strings.xml
  app/src/main/res/values/strings.xml
Labels: ready to merge

#5436 teams: smoother logs (fixes #5435)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/team/TeamDetailFragment.kt
Labels: ready to merge

#5437 courses: smoother markdown tables (fixes #5433)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/utilities/Markdown.kt
Labels: ready to merge

#5392 resources: smoother details (fixes #5391)
  app/build.gradle
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-ne/strings.xml
  app/src/main/res/values-so/strings.xml
  app/src/main/res/values/strings.xml
Labels: ready to merge

#5407 teams: smoother survey buttons (fixes #5371)
  app/src/main/res/layout/fragment_user_information.xml
Labels: ready to merge, peer review

#5344 login: smoother language button (fixes #5343)
  app/build.gradle
  app/src/main/res/layout-large-land/activity_login.xml
  app/src/main/res/layout-night/activity_login.xml
  app/src/main/res/layout-normal-land/activity_login.xml
  app/src/main/res/layout-xlarge-land/activity_login.xml
  app/src/main/res/layout/activity_login.xml
Labels: ready to merge

#5390 teams: smoother survey upload (fixes #5389)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/model/RealmSubmission.kt
  app/src/main/java/org/ole/planet/myplanet/service/UploadManager.kt
Labels: peer review

#5397 chat: smoother history (fixes #5346)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/model/RealmChatHistory.kt
  app/src/main/java/org/ole/planet/myplanet/ui/chat/ChatDetailFragment.kt
Labels: peer review

#5424 sync: smoother logs anr (fixes #5423)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/MainApplication.kt
  app/src/main/java/org/ole/planet/myplanet/utilities/ANRWatchdog.kt
Labels: priority, peer review

#5441 courses: smoother mycourses selection (fixes #5440)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/base/BaseResourceFragment.kt
  app/src/main/res/layout/my_library_alertdialog.xml
Labels: peer review

#5442 chat: smoother history (fixes #5412)
  app/build.gradle
  app/src/main/res/layout/fragment_chat_history_list.xml
Labels: peer review

#5446 teams: smoother log creation (fixes #5445)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/team/TeamDetailFragment.kt
Labels: peer review

#5447 all: smoother service translations (fixes #5420)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/datamanager/Service.kt
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-ne/strings.xml
  app/src/main/res/values-so/strings.xml
  app/src/main/res/values/strings.xml
Labels: ready to merge

#5452 teams: smoother surveys filter dark mode (fixes #5451)
  app/build.gradle
  app/src/main/res/values/styles.xml
Labels: ready to merge

#5453 teams: smoother surveys list (fixes #5428)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/survey/SurveyFragment.kt
Labels: ready to merge

#5455 resources: smoother bulk download (fixes #5454)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/datamanager/MyDownloadService.kt
Labels: ready to merge

#5329 mylife: smoother myhealth profile (fixes #5312)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/myhealth/AddMyHealthActivity.kt
  app/src/main/res/layout/activity_add_my_health.xml
  app/src/main/res/layout/spinner_item_white.xml
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-ne/strings.xml
  app/src/main/res/values-so/strings.xml
  app/src/main/res/values/strings.xml
Labels: changes requested, merge conflict

#5460 chat: smoother typing animation (fixes #5393)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/chat/ChatAdapter.kt
Labels: peer review

#5462 teams: smoother surveys description (fixes #5461)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/model/RealmStepExam.kt
  app/src/main/java/org/ole/planet/myplanet/ui/survey/AdapterSurvey.kt
  app/src/main/res/layout/row_survey.xml
Labels: ready to merge, peer review

#5450 login: smoother welcome toast (fixes #5430)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/sync/LoginActivity.kt
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-ne/strings.xml
  app/src/main/res/values-so/strings.xml
  app/src/main/res/values/strings.xml
Labels: ready to merge

#5467 resources: smoother download dialog (fixes #5465)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/base/BaseResourceFragment.kt
  app/src/main/res/layout/my_library_alertdialog.xml
Labels: ready to merge

#5485 teams: smoother survey submission (fixes #5484)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/survey/AdapterSurvey.kt
Labels: ready to merge

#5481 all: smoother disclaimer email (fixes #5480)
  app/build.gradle
  app/src/main/res/layout/fragment_disclaimer.xml
Labels: ready to merge

#5456 chat: smoother search translations (fixes #5444)
  app/build.gradle
  app/src/main/res/layout/fragment_chat_history_list.xml
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-ne/strings.xml
  app/src/main/res/values-so/strings.xml
  app/src/main/res/values/strings.xml
Labels: ready to merge

#5492 teams: smoother survey date filter (fixes #5491)
  app/build.gradle
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-ne/strings.xml
  app/src/main/res/values-so/strings.xml
  app/src/main/res/values/strings.xml
Labels: ready to merge

#5495 teams: smoother search (fixes #5479)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/team/TeamFragment.kt
Labels: ready to merge

#5494 dashboard: smoother mysurveys translation (fixes #5372)
  app/build.gradle
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-ne/strings.xml
  app/src/main/res/values-so/strings.xml
  app/src/main/res/values/strings.xml
Labels: ready to merge, peer review

#5496 teams: smoother survey order title (fixes #5478)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/survey/AdapterSurvey.kt
Labels: ready to merge, peer review

#5503 chat: smoother search dark mode (fixes #5499)
  app/build.gradle
  app/src/main/res/layout/fragment_chat_history_list.xml
Labels: ready to merge

#5498 sync: smoother dialog (fixes #5332)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/sync/SyncActivity.kt
Labels: peer review

#5487 teams: smoother survey recording (fixes #5474)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/exam/BaseExamFragment.kt
Labels: ready to merge, peer review

#5512 teams: smoother survey search (fixes #5477)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/survey/AdapterSurvey.kt
  app/src/main/java/org/ole/planet/myplanet/ui/survey/SurveyFragment.kt
Labels: ready to merge

#5527 teams: smoother task creation (fixes #5520)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/team/teamTask/TeamTaskFragment.kt
Labels: peer review

#5545 sync: smoother serialization (fixes #5544)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/model/RealmUserModel.kt
Labels: ready to merge, peer review

#5543 all: smoother notifications (fixes #5542)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardActivity.kt
  app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardActivity.kt.lite
Labels: ready to merge, peer review

#5536 login: smoother register (fixes #5532)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/datamanager/Service.kt
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-ne/strings.xml
  app/src/main/res/values-so/strings.xml
  app/src/main/res/values/strings.xml
Labels: ready to merge, peer review

#5540 teams: smoother voices titles (fixes #5524)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/model/RealmUserModel.kt
  app/src/main/java/org/ole/planet/myplanet/ui/news/AdapterNews.kt
Labels: ready to merge, peer review

#5489 teams: smoother voices editing (fixes #5471)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/model/RealmNews.kt
  app/src/main/java/org/ole/planet/myplanet/ui/news/AdapterNews.kt
  app/src/main/res/layout/row_news.xml
Labels: ready to merge, peer review

#5548 teams: smoother calendar (fixes #5547)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/enterprises/EnterpriseCalendarFragment.kt
Labels: peer review

#5554 mylife: smoother mysurveys (fixes #5552)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/dashboard/BaseDashboardFragmentPlugin.kt
Labels: peer review

#5551 all: smoother base container (fixes #5550)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/base/BaseContainerFragment.kt
  app/src/main/java/org/ole/planet/myplanet/base/BaseContainerFragment.kt.lite
Labels: peer review

#5559 all: smoother models (fixes #5558)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/model/RealmMyCourse.kt
  app/src/main/java/org/ole/planet/myplanet/model/RealmUserModel.kt
Labels: ready to merge

#5561 all: smoother sync service (fixes #5560)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/service/AutoSyncWorker.kt
  app/src/main/java/org/ole/planet/myplanet/service/SyncManager.kt
Labels: ready to merge, peer review

#5557 sync: smoother beta (fixes #5483)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/service/AutoSyncWorker.kt
  app/src/main/java/org/ole/planet/myplanet/service/SyncManager.kt
  app/src/main/java/org/ole/planet/myplanet/ui/sync/SyncActivity.kt
Labels: priority, ready to merge

#5509 login: smoother registering (fixes #5482)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/base/BaseResourceFragment.kt
  app/src/main/java/org/ole/planet/myplanet/datamanager/Service.kt
  app/src/main/java/org/ole/planet/myplanet/model/RealmUserModel.kt
  app/src/main/java/org/ole/planet/myplanet/service/UploadManager.kt
  app/src/main/java/org/ole/planet/myplanet/service/UserProfileDbHandler.kt
  app/src/main/java/org/ole/planet/myplanet/ui/sync/LoginActivity.kt
  app/src/main/java/org/ole/planet/myplanet/ui/sync/SyncActivity.kt
  app/src/main/java/org/ole/planet/myplanet/ui/userprofile/BecomeMemberActivity.kt
  app/src/main/java/org/ole/planet/myplanet/utilities/ServerUrlMapper.kt
Labels: priority, peer review, changes requested

#5564 all: smoother utilities (fixes #5563)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/utilities/FileUtils.kt
  app/src/main/java/org/ole/planet/myplanet/utilities/LocaleHelper.kt
  app/src/main/java/org/ole/planet/myplanet/utilities/Markdown.kt
  app/src/main/java/org/ole/planet/myplanet/utilities/NetworkUtils.kt
  app/src/main/java/org/ole/planet/myplanet/utilities/ServerUrlMapper.kt
  app/src/main/java/org/ole/planet/myplanet/utilities/Utilities.kt
Labels: ready to merge

#5585 sync: smoother dialog dismiss (fixes #5584)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/ui/sync/SyncActivity.kt
Labels: ready to merge

#5570 teams: smoother calendar events (fixes #5567)
  app/build.gradle
  app/src/main/java/org/ole/planet/myplanet/model/RealmMeetup.kt
  app/src/main/java/org/ole/planet/myplanet/service/AutoSyncWorker.kt
  app/src/main/java/org/ole/planet/myplanet/service/UploadManager.kt
  app/src/main/java/org/ole/planet/myplanet/ui/enterprises/EnterpriseCalendarFragment.kt
  app/src/main/java/org/ole/planet/myplanet/ui/sync/ProcessUserDataActivity.kt
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-ne/strings.xml
  app/src/main/res/values-so/strings.xml
  app/src/main/res/values/strings.xml
Labels: ready to merge, peer review
